export enum ETabKey {
  Activity = 'activity',
  Badge = 'badge',
  Cognitive = 'cognitive',
  Forum = 'forum',
  Help = 'help',
  Mood = 'mood',
  Nutrition = 'nutrition',
  Program = 'program',
  Project = 'project',
  Resource = 'resource',
  Service = 'service',
  Skill = 'skill',
  UrbanIssue = 'urban_issue',
  Wellness = 'wellness',
}
