
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Valence = {
  positive: 'positive',
  negative: 'negative',
  neutre: 'neutre'
} as const

export type Valence = (typeof Valence)[keyof typeof Valence]


export const Role = {
  admin: 'admin',
  member: 'member'
} as const

export type Role = (typeof Role)[keyof typeof Role]
