
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `badge` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model badge
 * 
 */
export type badgeModel = runtime.Types.Result.DefaultSelection<Prisma.$badgePayload>

export type AggregateBadge = {
  _count: BadgeCountAggregateOutputType | null
  _avg: BadgeAvgAggregateOutputType | null
  _sum: BadgeSumAggregateOutputType | null
  _min: BadgeMinAggregateOutputType | null
  _max: BadgeMaxAggregateOutputType | null
}

export type BadgeAvgAggregateOutputType = {
  level: number | null
  categoryId: number | null
}

export type BadgeSumAggregateOutputType = {
  level: number | null
  categoryId: number | null
}

export type BadgeMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  icon: string | null
  level: number | null
  createdAt: Date | null
  updatedAt: Date | null
  userBadgeId: string | null
  categoryId: number | null
  userId: string | null
}

export type BadgeMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  icon: string | null
  level: number | null
  createdAt: Date | null
  updatedAt: Date | null
  userBadgeId: string | null
  categoryId: number | null
  userId: string | null
}

export type BadgeCountAggregateOutputType = {
  id: number
  name: number
  description: number
  icon: number
  level: number
  createdAt: number
  updatedAt: number
  userBadgeId: number
  categoryId: number
  userId: number
  _all: number
}


export type BadgeAvgAggregateInputType = {
  level?: true
  categoryId?: true
}

export type BadgeSumAggregateInputType = {
  level?: true
  categoryId?: true
}

export type BadgeMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  icon?: true
  level?: true
  createdAt?: true
  updatedAt?: true
  userBadgeId?: true
  categoryId?: true
  userId?: true
}

export type BadgeMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  icon?: true
  level?: true
  createdAt?: true
  updatedAt?: true
  userBadgeId?: true
  categoryId?: true
  userId?: true
}

export type BadgeCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  icon?: true
  level?: true
  createdAt?: true
  updatedAt?: true
  userBadgeId?: true
  categoryId?: true
  userId?: true
  _all?: true
}

export type BadgeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which badge to aggregate.
   */
  where?: Prisma.badgeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of badges to fetch.
   */
  orderBy?: Prisma.badgeOrderByWithRelationInput | Prisma.badgeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.badgeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` badges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` badges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned badges
  **/
  _count?: true | BadgeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BadgeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BadgeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BadgeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BadgeMaxAggregateInputType
}

export type GetBadgeAggregateType<T extends BadgeAggregateArgs> = {
      [P in keyof T & keyof AggregateBadge]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBadge[P]>
    : Prisma.GetScalarType<T[P], AggregateBadge[P]>
}




export type badgeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.badgeWhereInput
  orderBy?: Prisma.badgeOrderByWithAggregationInput | Prisma.badgeOrderByWithAggregationInput[]
  by: Prisma.BadgeScalarFieldEnum[] | Prisma.BadgeScalarFieldEnum
  having?: Prisma.badgeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BadgeCountAggregateInputType | true
  _avg?: BadgeAvgAggregateInputType
  _sum?: BadgeSumAggregateInputType
  _min?: BadgeMinAggregateInputType
  _max?: BadgeMaxAggregateInputType
}

export type BadgeGroupByOutputType = {
  id: string
  name: string
  description: string | null
  icon: string | null
  level: number | null
  createdAt: Date
  updatedAt: Date | null
  userBadgeId: string | null
  categoryId: number
  userId: string | null
  _count: BadgeCountAggregateOutputType | null
  _avg: BadgeAvgAggregateOutputType | null
  _sum: BadgeSumAggregateOutputType | null
  _min: BadgeMinAggregateOutputType | null
  _max: BadgeMaxAggregateOutputType | null
}

type GetBadgeGroupByPayload<T extends badgeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BadgeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BadgeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BadgeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BadgeGroupByOutputType[P]>
      }
    >
  >



export type badgeWhereInput = {
  AND?: Prisma.badgeWhereInput | Prisma.badgeWhereInput[]
  OR?: Prisma.badgeWhereInput[]
  NOT?: Prisma.badgeWhereInput | Prisma.badgeWhereInput[]
  id?: Prisma.StringFilter<"badge"> | string
  name?: Prisma.StringFilter<"badge"> | string
  description?: Prisma.StringNullableFilter<"badge"> | string | null
  icon?: Prisma.StringNullableFilter<"badge"> | string | null
  level?: Prisma.IntNullableFilter<"badge"> | number | null
  createdAt?: Prisma.DateTimeFilter<"badge"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"badge"> | Date | string | null
  userBadgeId?: Prisma.StringNullableFilter<"badge"> | string | null
  categoryId?: Prisma.IntFilter<"badge"> | number
  userId?: Prisma.StringNullableFilter<"badge"> | string | null
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.categoryWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.userWhereInput> | null
  userBadges?: Prisma.UserBadgeListRelationFilter
}

export type badgeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  level?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  userBadgeId?: Prisma.SortOrderInput | Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.categoryOrderByWithRelationInput
  user?: Prisma.userOrderByWithRelationInput
  userBadges?: Prisma.userBadgeOrderByRelationAggregateInput
}

export type badgeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  categoryId?: number
  AND?: Prisma.badgeWhereInput | Prisma.badgeWhereInput[]
  OR?: Prisma.badgeWhereInput[]
  NOT?: Prisma.badgeWhereInput | Prisma.badgeWhereInput[]
  name?: Prisma.StringFilter<"badge"> | string
  description?: Prisma.StringNullableFilter<"badge"> | string | null
  icon?: Prisma.StringNullableFilter<"badge"> | string | null
  level?: Prisma.IntNullableFilter<"badge"> | number | null
  createdAt?: Prisma.DateTimeFilter<"badge"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"badge"> | Date | string | null
  userBadgeId?: Prisma.StringNullableFilter<"badge"> | string | null
  userId?: Prisma.StringNullableFilter<"badge"> | string | null
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.categoryWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.userWhereInput> | null
  userBadges?: Prisma.UserBadgeListRelationFilter
}, "id" | "categoryId">

export type badgeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  level?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  userBadgeId?: Prisma.SortOrderInput | Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.badgeCountOrderByAggregateInput
  _avg?: Prisma.badgeAvgOrderByAggregateInput
  _max?: Prisma.badgeMaxOrderByAggregateInput
  _min?: Prisma.badgeMinOrderByAggregateInput
  _sum?: Prisma.badgeSumOrderByAggregateInput
}

export type badgeScalarWhereWithAggregatesInput = {
  AND?: Prisma.badgeScalarWhereWithAggregatesInput | Prisma.badgeScalarWhereWithAggregatesInput[]
  OR?: Prisma.badgeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.badgeScalarWhereWithAggregatesInput | Prisma.badgeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"badge"> | string
  name?: Prisma.StringWithAggregatesFilter<"badge"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"badge"> | string | null
  icon?: Prisma.StringNullableWithAggregatesFilter<"badge"> | string | null
  level?: Prisma.IntNullableWithAggregatesFilter<"badge"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"badge"> | Date | string
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"badge"> | Date | string | null
  userBadgeId?: Prisma.StringNullableWithAggregatesFilter<"badge"> | string | null
  categoryId?: Prisma.IntWithAggregatesFilter<"badge"> | number
  userId?: Prisma.StringNullableWithAggregatesFilter<"badge"> | string | null
}

export type badgeCreateInput = {
  id?: string
  name: string
  description?: string | null
  icon?: string | null
  level?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  userBadgeId?: string | null
  category: Prisma.categoryCreateNestedOneWithoutBadgeInput
  user?: Prisma.userCreateNestedOneWithoutBadgeInput
  userBadges?: Prisma.userBadgeCreateNestedManyWithoutBadgeInput
}

export type badgeUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  icon?: string | null
  level?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  userBadgeId?: string | null
  categoryId: number
  userId?: string | null
  userBadges?: Prisma.userBadgeUncheckedCreateNestedManyWithoutBadgeInput
}

export type badgeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userBadgeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.categoryUpdateOneRequiredWithoutBadgeNestedInput
  user?: Prisma.userUpdateOneWithoutBadgeNestedInput
  userBadges?: Prisma.userBadgeUpdateManyWithoutBadgeNestedInput
}

export type badgeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userBadgeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userBadges?: Prisma.userBadgeUncheckedUpdateManyWithoutBadgeNestedInput
}

export type badgeCreateManyInput = {
  id?: string
  name: string
  description?: string | null
  icon?: string | null
  level?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  userBadgeId?: string | null
  categoryId: number
  userId?: string | null
}

export type badgeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userBadgeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type badgeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userBadgeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type badgeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  level?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userBadgeId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type badgeAvgOrderByAggregateInput = {
  level?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
}

export type badgeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  level?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userBadgeId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type badgeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  level?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userBadgeId?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type badgeSumOrderByAggregateInput = {
  level?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
}

export type BadgeListRelationFilter = {
  every?: Prisma.badgeWhereInput
  some?: Prisma.badgeWhereInput
  none?: Prisma.badgeWhereInput
}

export type badgeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BadgeScalarRelationFilter = {
  is?: Prisma.badgeWhereInput
  isNot?: Prisma.badgeWhereInput
}

export type badgeCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.badgeCreateWithoutCategoryInput, Prisma.badgeUncheckedCreateWithoutCategoryInput> | Prisma.badgeCreateWithoutCategoryInput[] | Prisma.badgeUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.badgeCreateOrConnectWithoutCategoryInput | Prisma.badgeCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.badgeCreateManyCategoryInputEnvelope
  connect?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
}

export type badgeUncheckedCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.badgeCreateWithoutCategoryInput, Prisma.badgeUncheckedCreateWithoutCategoryInput> | Prisma.badgeCreateWithoutCategoryInput[] | Prisma.badgeUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.badgeCreateOrConnectWithoutCategoryInput | Prisma.badgeCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.badgeCreateManyCategoryInputEnvelope
  connect?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
}

export type badgeUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.badgeCreateWithoutCategoryInput, Prisma.badgeUncheckedCreateWithoutCategoryInput> | Prisma.badgeCreateWithoutCategoryInput[] | Prisma.badgeUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.badgeCreateOrConnectWithoutCategoryInput | Prisma.badgeCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.badgeUpsertWithWhereUniqueWithoutCategoryInput | Prisma.badgeUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.badgeCreateManyCategoryInputEnvelope
  set?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  disconnect?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  delete?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  connect?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  update?: Prisma.badgeUpdateWithWhereUniqueWithoutCategoryInput | Prisma.badgeUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.badgeUpdateManyWithWhereWithoutCategoryInput | Prisma.badgeUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.badgeScalarWhereInput | Prisma.badgeScalarWhereInput[]
}

export type badgeUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.badgeCreateWithoutCategoryInput, Prisma.badgeUncheckedCreateWithoutCategoryInput> | Prisma.badgeCreateWithoutCategoryInput[] | Prisma.badgeUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.badgeCreateOrConnectWithoutCategoryInput | Prisma.badgeCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.badgeUpsertWithWhereUniqueWithoutCategoryInput | Prisma.badgeUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.badgeCreateManyCategoryInputEnvelope
  set?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  disconnect?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  delete?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  connect?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  update?: Prisma.badgeUpdateWithWhereUniqueWithoutCategoryInput | Prisma.badgeUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.badgeUpdateManyWithWhereWithoutCategoryInput | Prisma.badgeUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.badgeScalarWhereInput | Prisma.badgeScalarWhereInput[]
}

export type badgeCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.badgeCreateWithoutUserInput, Prisma.badgeUncheckedCreateWithoutUserInput> | Prisma.badgeCreateWithoutUserInput[] | Prisma.badgeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.badgeCreateOrConnectWithoutUserInput | Prisma.badgeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.badgeCreateManyUserInputEnvelope
  connect?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
}

export type badgeUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.badgeCreateWithoutUserInput, Prisma.badgeUncheckedCreateWithoutUserInput> | Prisma.badgeCreateWithoutUserInput[] | Prisma.badgeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.badgeCreateOrConnectWithoutUserInput | Prisma.badgeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.badgeCreateManyUserInputEnvelope
  connect?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
}

export type badgeUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.badgeCreateWithoutUserInput, Prisma.badgeUncheckedCreateWithoutUserInput> | Prisma.badgeCreateWithoutUserInput[] | Prisma.badgeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.badgeCreateOrConnectWithoutUserInput | Prisma.badgeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.badgeUpsertWithWhereUniqueWithoutUserInput | Prisma.badgeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.badgeCreateManyUserInputEnvelope
  set?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  disconnect?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  delete?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  connect?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  update?: Prisma.badgeUpdateWithWhereUniqueWithoutUserInput | Prisma.badgeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.badgeUpdateManyWithWhereWithoutUserInput | Prisma.badgeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.badgeScalarWhereInput | Prisma.badgeScalarWhereInput[]
}

export type badgeUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.badgeCreateWithoutUserInput, Prisma.badgeUncheckedCreateWithoutUserInput> | Prisma.badgeCreateWithoutUserInput[] | Prisma.badgeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.badgeCreateOrConnectWithoutUserInput | Prisma.badgeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.badgeUpsertWithWhereUniqueWithoutUserInput | Prisma.badgeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.badgeCreateManyUserInputEnvelope
  set?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  disconnect?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  delete?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  connect?: Prisma.badgeWhereUniqueInput | Prisma.badgeWhereUniqueInput[]
  update?: Prisma.badgeUpdateWithWhereUniqueWithoutUserInput | Prisma.badgeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.badgeUpdateManyWithWhereWithoutUserInput | Prisma.badgeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.badgeScalarWhereInput | Prisma.badgeScalarWhereInput[]
}

export type badgeCreateNestedOneWithoutUserBadgesInput = {
  create?: Prisma.XOR<Prisma.badgeCreateWithoutUserBadgesInput, Prisma.badgeUncheckedCreateWithoutUserBadgesInput>
  connectOrCreate?: Prisma.badgeCreateOrConnectWithoutUserBadgesInput
  connect?: Prisma.badgeWhereUniqueInput
}

export type badgeUpdateOneRequiredWithoutUserBadgesNestedInput = {
  create?: Prisma.XOR<Prisma.badgeCreateWithoutUserBadgesInput, Prisma.badgeUncheckedCreateWithoutUserBadgesInput>
  connectOrCreate?: Prisma.badgeCreateOrConnectWithoutUserBadgesInput
  upsert?: Prisma.badgeUpsertWithoutUserBadgesInput
  connect?: Prisma.badgeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.badgeUpdateToOneWithWhereWithoutUserBadgesInput, Prisma.badgeUpdateWithoutUserBadgesInput>, Prisma.badgeUncheckedUpdateWithoutUserBadgesInput>
}

export type badgeCreateWithoutCategoryInput = {
  id?: string
  name: string
  description?: string | null
  icon?: string | null
  level?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  userBadgeId?: string | null
  user?: Prisma.userCreateNestedOneWithoutBadgeInput
  userBadges?: Prisma.userBadgeCreateNestedManyWithoutBadgeInput
}

export type badgeUncheckedCreateWithoutCategoryInput = {
  id?: string
  name: string
  description?: string | null
  icon?: string | null
  level?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  userBadgeId?: string | null
  userId?: string | null
  userBadges?: Prisma.userBadgeUncheckedCreateNestedManyWithoutBadgeInput
}

export type badgeCreateOrConnectWithoutCategoryInput = {
  where: Prisma.badgeWhereUniqueInput
  create: Prisma.XOR<Prisma.badgeCreateWithoutCategoryInput, Prisma.badgeUncheckedCreateWithoutCategoryInput>
}

export type badgeCreateManyCategoryInputEnvelope = {
  data: Prisma.badgeCreateManyCategoryInput | Prisma.badgeCreateManyCategoryInput[]
  skipDuplicates?: boolean
}

export type badgeUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.badgeWhereUniqueInput
  update: Prisma.XOR<Prisma.badgeUpdateWithoutCategoryInput, Prisma.badgeUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.badgeCreateWithoutCategoryInput, Prisma.badgeUncheckedCreateWithoutCategoryInput>
}

export type badgeUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.badgeWhereUniqueInput
  data: Prisma.XOR<Prisma.badgeUpdateWithoutCategoryInput, Prisma.badgeUncheckedUpdateWithoutCategoryInput>
}

export type badgeUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.badgeScalarWhereInput
  data: Prisma.XOR<Prisma.badgeUpdateManyMutationInput, Prisma.badgeUncheckedUpdateManyWithoutCategoryInput>
}

export type badgeScalarWhereInput = {
  AND?: Prisma.badgeScalarWhereInput | Prisma.badgeScalarWhereInput[]
  OR?: Prisma.badgeScalarWhereInput[]
  NOT?: Prisma.badgeScalarWhereInput | Prisma.badgeScalarWhereInput[]
  id?: Prisma.StringFilter<"badge"> | string
  name?: Prisma.StringFilter<"badge"> | string
  description?: Prisma.StringNullableFilter<"badge"> | string | null
  icon?: Prisma.StringNullableFilter<"badge"> | string | null
  level?: Prisma.IntNullableFilter<"badge"> | number | null
  createdAt?: Prisma.DateTimeFilter<"badge"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"badge"> | Date | string | null
  userBadgeId?: Prisma.StringNullableFilter<"badge"> | string | null
  categoryId?: Prisma.IntFilter<"badge"> | number
  userId?: Prisma.StringNullableFilter<"badge"> | string | null
}

export type badgeCreateWithoutUserInput = {
  id?: string
  name: string
  description?: string | null
  icon?: string | null
  level?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  userBadgeId?: string | null
  category: Prisma.categoryCreateNestedOneWithoutBadgeInput
  userBadges?: Prisma.userBadgeCreateNestedManyWithoutBadgeInput
}

export type badgeUncheckedCreateWithoutUserInput = {
  id?: string
  name: string
  description?: string | null
  icon?: string | null
  level?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  userBadgeId?: string | null
  categoryId: number
  userBadges?: Prisma.userBadgeUncheckedCreateNestedManyWithoutBadgeInput
}

export type badgeCreateOrConnectWithoutUserInput = {
  where: Prisma.badgeWhereUniqueInput
  create: Prisma.XOR<Prisma.badgeCreateWithoutUserInput, Prisma.badgeUncheckedCreateWithoutUserInput>
}

export type badgeCreateManyUserInputEnvelope = {
  data: Prisma.badgeCreateManyUserInput | Prisma.badgeCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type badgeUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.badgeWhereUniqueInput
  update: Prisma.XOR<Prisma.badgeUpdateWithoutUserInput, Prisma.badgeUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.badgeCreateWithoutUserInput, Prisma.badgeUncheckedCreateWithoutUserInput>
}

export type badgeUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.badgeWhereUniqueInput
  data: Prisma.XOR<Prisma.badgeUpdateWithoutUserInput, Prisma.badgeUncheckedUpdateWithoutUserInput>
}

export type badgeUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.badgeScalarWhereInput
  data: Prisma.XOR<Prisma.badgeUpdateManyMutationInput, Prisma.badgeUncheckedUpdateManyWithoutUserInput>
}

export type badgeCreateWithoutUserBadgesInput = {
  id?: string
  name: string
  description?: string | null
  icon?: string | null
  level?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  userBadgeId?: string | null
  category: Prisma.categoryCreateNestedOneWithoutBadgeInput
  user?: Prisma.userCreateNestedOneWithoutBadgeInput
}

export type badgeUncheckedCreateWithoutUserBadgesInput = {
  id?: string
  name: string
  description?: string | null
  icon?: string | null
  level?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  userBadgeId?: string | null
  categoryId: number
  userId?: string | null
}

export type badgeCreateOrConnectWithoutUserBadgesInput = {
  where: Prisma.badgeWhereUniqueInput
  create: Prisma.XOR<Prisma.badgeCreateWithoutUserBadgesInput, Prisma.badgeUncheckedCreateWithoutUserBadgesInput>
}

export type badgeUpsertWithoutUserBadgesInput = {
  update: Prisma.XOR<Prisma.badgeUpdateWithoutUserBadgesInput, Prisma.badgeUncheckedUpdateWithoutUserBadgesInput>
  create: Prisma.XOR<Prisma.badgeCreateWithoutUserBadgesInput, Prisma.badgeUncheckedCreateWithoutUserBadgesInput>
  where?: Prisma.badgeWhereInput
}

export type badgeUpdateToOneWithWhereWithoutUserBadgesInput = {
  where?: Prisma.badgeWhereInput
  data: Prisma.XOR<Prisma.badgeUpdateWithoutUserBadgesInput, Prisma.badgeUncheckedUpdateWithoutUserBadgesInput>
}

export type badgeUpdateWithoutUserBadgesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userBadgeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.categoryUpdateOneRequiredWithoutBadgeNestedInput
  user?: Prisma.userUpdateOneWithoutBadgeNestedInput
}

export type badgeUncheckedUpdateWithoutUserBadgesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userBadgeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type badgeCreateManyCategoryInput = {
  id?: string
  name: string
  description?: string | null
  icon?: string | null
  level?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  userBadgeId?: string | null
  userId?: string | null
}

export type badgeUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userBadgeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user?: Prisma.userUpdateOneWithoutBadgeNestedInput
  userBadges?: Prisma.userBadgeUpdateManyWithoutBadgeNestedInput
}

export type badgeUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userBadgeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userBadges?: Prisma.userBadgeUncheckedUpdateManyWithoutBadgeNestedInput
}

export type badgeUncheckedUpdateManyWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userBadgeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type badgeCreateManyUserInput = {
  id?: string
  name: string
  description?: string | null
  icon?: string | null
  level?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  userBadgeId?: string | null
  categoryId: number
}

export type badgeUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userBadgeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.categoryUpdateOneRequiredWithoutBadgeNestedInput
  userBadges?: Prisma.userBadgeUpdateManyWithoutBadgeNestedInput
}

export type badgeUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userBadgeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.IntFieldUpdateOperationsInput | number
  userBadges?: Prisma.userBadgeUncheckedUpdateManyWithoutBadgeNestedInput
}

export type badgeUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  level?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userBadgeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type BadgeCountOutputType
 */

export type BadgeCountOutputType = {
  userBadges: number
}

export type BadgeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userBadges?: boolean | BadgeCountOutputTypeCountUserBadgesArgs
}

/**
 * BadgeCountOutputType without action
 */
export type BadgeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BadgeCountOutputType
   */
  select?: Prisma.BadgeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BadgeCountOutputType without action
 */
export type BadgeCountOutputTypeCountUserBadgesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.userBadgeWhereInput
}


export type badgeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  icon?: boolean
  level?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userBadgeId?: boolean
  categoryId?: boolean
  userId?: boolean
  category?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.badge$userArgs<ExtArgs>
  userBadges?: boolean | Prisma.badge$userBadgesArgs<ExtArgs>
  _count?: boolean | Prisma.BadgeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["badge"]>

export type badgeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  icon?: boolean
  level?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userBadgeId?: boolean
  categoryId?: boolean
  userId?: boolean
  category?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.badge$userArgs<ExtArgs>
}, ExtArgs["result"]["badge"]>

export type badgeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  icon?: boolean
  level?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userBadgeId?: boolean
  categoryId?: boolean
  userId?: boolean
  category?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.badge$userArgs<ExtArgs>
}, ExtArgs["result"]["badge"]>

export type badgeSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  icon?: boolean
  level?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userBadgeId?: boolean
  categoryId?: boolean
  userId?: boolean
}

export type badgeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "icon" | "level" | "createdAt" | "updatedAt" | "userBadgeId" | "categoryId" | "userId", ExtArgs["result"]["badge"]>
export type badgeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.badge$userArgs<ExtArgs>
  userBadges?: boolean | Prisma.badge$userBadgesArgs<ExtArgs>
  _count?: boolean | Prisma.BadgeCountOutputTypeDefaultArgs<ExtArgs>
}
export type badgeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.badge$userArgs<ExtArgs>
}
export type badgeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.badge$userArgs<ExtArgs>
}

export type $badgePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "badge"
  objects: {
    category: Prisma.$categoryPayload<ExtArgs>
    user: Prisma.$userPayload<ExtArgs> | null
    userBadges: Prisma.$userBadgePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
    icon: string | null
    level: number | null
    createdAt: Date
    updatedAt: Date | null
    userBadgeId: string | null
    categoryId: number
    userId: string | null
  }, ExtArgs["result"]["badge"]>
  composites: {}
}

export type badgeGetPayload<S extends boolean | null | undefined | badgeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$badgePayload, S>

export type badgeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<badgeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BadgeCountAggregateInputType | true
  }

export interface badgeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['badge'], meta: { name: 'badge' } }
  /**
   * Find zero or one Badge that matches the filter.
   * @param {badgeFindUniqueArgs} args - Arguments to find a Badge
   * @example
   * // Get one Badge
   * const badge = await prisma.badge.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends badgeFindUniqueArgs>(args: Prisma.SelectSubset<T, badgeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__badgeClient<runtime.Types.Result.GetResult<Prisma.$badgePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Badge that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {badgeFindUniqueOrThrowArgs} args - Arguments to find a Badge
   * @example
   * // Get one Badge
   * const badge = await prisma.badge.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends badgeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, badgeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__badgeClient<runtime.Types.Result.GetResult<Prisma.$badgePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Badge that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {badgeFindFirstArgs} args - Arguments to find a Badge
   * @example
   * // Get one Badge
   * const badge = await prisma.badge.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends badgeFindFirstArgs>(args?: Prisma.SelectSubset<T, badgeFindFirstArgs<ExtArgs>>): Prisma.Prisma__badgeClient<runtime.Types.Result.GetResult<Prisma.$badgePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Badge that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {badgeFindFirstOrThrowArgs} args - Arguments to find a Badge
   * @example
   * // Get one Badge
   * const badge = await prisma.badge.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends badgeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, badgeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__badgeClient<runtime.Types.Result.GetResult<Prisma.$badgePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Badges that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {badgeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Badges
   * const badges = await prisma.badge.findMany()
   * 
   * // Get first 10 Badges
   * const badges = await prisma.badge.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const badgeWithIdOnly = await prisma.badge.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends badgeFindManyArgs>(args?: Prisma.SelectSubset<T, badgeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$badgePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Badge.
   * @param {badgeCreateArgs} args - Arguments to create a Badge.
   * @example
   * // Create one Badge
   * const Badge = await prisma.badge.create({
   *   data: {
   *     // ... data to create a Badge
   *   }
   * })
   * 
   */
  create<T extends badgeCreateArgs>(args: Prisma.SelectSubset<T, badgeCreateArgs<ExtArgs>>): Prisma.Prisma__badgeClient<runtime.Types.Result.GetResult<Prisma.$badgePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Badges.
   * @param {badgeCreateManyArgs} args - Arguments to create many Badges.
   * @example
   * // Create many Badges
   * const badge = await prisma.badge.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends badgeCreateManyArgs>(args?: Prisma.SelectSubset<T, badgeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Badges and returns the data saved in the database.
   * @param {badgeCreateManyAndReturnArgs} args - Arguments to create many Badges.
   * @example
   * // Create many Badges
   * const badge = await prisma.badge.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Badges and only return the `id`
   * const badgeWithIdOnly = await prisma.badge.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends badgeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, badgeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$badgePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Badge.
   * @param {badgeDeleteArgs} args - Arguments to delete one Badge.
   * @example
   * // Delete one Badge
   * const Badge = await prisma.badge.delete({
   *   where: {
   *     // ... filter to delete one Badge
   *   }
   * })
   * 
   */
  delete<T extends badgeDeleteArgs>(args: Prisma.SelectSubset<T, badgeDeleteArgs<ExtArgs>>): Prisma.Prisma__badgeClient<runtime.Types.Result.GetResult<Prisma.$badgePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Badge.
   * @param {badgeUpdateArgs} args - Arguments to update one Badge.
   * @example
   * // Update one Badge
   * const badge = await prisma.badge.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends badgeUpdateArgs>(args: Prisma.SelectSubset<T, badgeUpdateArgs<ExtArgs>>): Prisma.Prisma__badgeClient<runtime.Types.Result.GetResult<Prisma.$badgePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Badges.
   * @param {badgeDeleteManyArgs} args - Arguments to filter Badges to delete.
   * @example
   * // Delete a few Badges
   * const { count } = await prisma.badge.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends badgeDeleteManyArgs>(args?: Prisma.SelectSubset<T, badgeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Badges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {badgeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Badges
   * const badge = await prisma.badge.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends badgeUpdateManyArgs>(args: Prisma.SelectSubset<T, badgeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Badges and returns the data updated in the database.
   * @param {badgeUpdateManyAndReturnArgs} args - Arguments to update many Badges.
   * @example
   * // Update many Badges
   * const badge = await prisma.badge.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Badges and only return the `id`
   * const badgeWithIdOnly = await prisma.badge.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends badgeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, badgeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$badgePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Badge.
   * @param {badgeUpsertArgs} args - Arguments to update or create a Badge.
   * @example
   * // Update or create a Badge
   * const badge = await prisma.badge.upsert({
   *   create: {
   *     // ... data to create a Badge
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Badge we want to update
   *   }
   * })
   */
  upsert<T extends badgeUpsertArgs>(args: Prisma.SelectSubset<T, badgeUpsertArgs<ExtArgs>>): Prisma.Prisma__badgeClient<runtime.Types.Result.GetResult<Prisma.$badgePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Badges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {badgeCountArgs} args - Arguments to filter Badges to count.
   * @example
   * // Count the number of Badges
   * const count = await prisma.badge.count({
   *   where: {
   *     // ... the filter for the Badges we want to count
   *   }
   * })
  **/
  count<T extends badgeCountArgs>(
    args?: Prisma.Subset<T, badgeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BadgeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Badge.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BadgeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BadgeAggregateArgs>(args: Prisma.Subset<T, BadgeAggregateArgs>): Prisma.PrismaPromise<GetBadgeAggregateType<T>>

  /**
   * Group by Badge.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {badgeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends badgeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: badgeGroupByArgs['orderBy'] }
      : { orderBy?: badgeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, badgeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBadgeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the badge model
 */
readonly fields: badgeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for badge.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__badgeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  category<T extends Prisma.categoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.categoryDefaultArgs<ExtArgs>>): Prisma.Prisma__categoryClient<runtime.Types.Result.GetResult<Prisma.$categoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.badge$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.badge$userArgs<ExtArgs>>): Prisma.Prisma__userClient<runtime.Types.Result.GetResult<Prisma.$userPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  userBadges<T extends Prisma.badge$userBadgesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.badge$userBadgesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$userBadgePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the badge model
 */
export interface badgeFieldRefs {
  readonly id: Prisma.FieldRef<"badge", 'String'>
  readonly name: Prisma.FieldRef<"badge", 'String'>
  readonly description: Prisma.FieldRef<"badge", 'String'>
  readonly icon: Prisma.FieldRef<"badge", 'String'>
  readonly level: Prisma.FieldRef<"badge", 'Int'>
  readonly createdAt: Prisma.FieldRef<"badge", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"badge", 'DateTime'>
  readonly userBadgeId: Prisma.FieldRef<"badge", 'String'>
  readonly categoryId: Prisma.FieldRef<"badge", 'Int'>
  readonly userId: Prisma.FieldRef<"badge", 'String'>
}
    

// Custom InputTypes
/**
 * badge findUnique
 */
export type badgeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the badge
   */
  select?: Prisma.badgeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the badge
   */
  omit?: Prisma.badgeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.badgeInclude<ExtArgs> | null
  /**
   * Filter, which badge to fetch.
   */
  where: Prisma.badgeWhereUniqueInput
}

/**
 * badge findUniqueOrThrow
 */
export type badgeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the badge
   */
  select?: Prisma.badgeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the badge
   */
  omit?: Prisma.badgeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.badgeInclude<ExtArgs> | null
  /**
   * Filter, which badge to fetch.
   */
  where: Prisma.badgeWhereUniqueInput
}

/**
 * badge findFirst
 */
export type badgeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the badge
   */
  select?: Prisma.badgeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the badge
   */
  omit?: Prisma.badgeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.badgeInclude<ExtArgs> | null
  /**
   * Filter, which badge to fetch.
   */
  where?: Prisma.badgeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of badges to fetch.
   */
  orderBy?: Prisma.badgeOrderByWithRelationInput | Prisma.badgeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for badges.
   */
  cursor?: Prisma.badgeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` badges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` badges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of badges.
   */
  distinct?: Prisma.BadgeScalarFieldEnum | Prisma.BadgeScalarFieldEnum[]
}

/**
 * badge findFirstOrThrow
 */
export type badgeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the badge
   */
  select?: Prisma.badgeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the badge
   */
  omit?: Prisma.badgeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.badgeInclude<ExtArgs> | null
  /**
   * Filter, which badge to fetch.
   */
  where?: Prisma.badgeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of badges to fetch.
   */
  orderBy?: Prisma.badgeOrderByWithRelationInput | Prisma.badgeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for badges.
   */
  cursor?: Prisma.badgeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` badges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` badges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of badges.
   */
  distinct?: Prisma.BadgeScalarFieldEnum | Prisma.BadgeScalarFieldEnum[]
}

/**
 * badge findMany
 */
export type badgeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the badge
   */
  select?: Prisma.badgeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the badge
   */
  omit?: Prisma.badgeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.badgeInclude<ExtArgs> | null
  /**
   * Filter, which badges to fetch.
   */
  where?: Prisma.badgeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of badges to fetch.
   */
  orderBy?: Prisma.badgeOrderByWithRelationInput | Prisma.badgeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing badges.
   */
  cursor?: Prisma.badgeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` badges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` badges.
   */
  skip?: number
  distinct?: Prisma.BadgeScalarFieldEnum | Prisma.BadgeScalarFieldEnum[]
}

/**
 * badge create
 */
export type badgeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the badge
   */
  select?: Prisma.badgeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the badge
   */
  omit?: Prisma.badgeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.badgeInclude<ExtArgs> | null
  /**
   * The data needed to create a badge.
   */
  data: Prisma.XOR<Prisma.badgeCreateInput, Prisma.badgeUncheckedCreateInput>
}

/**
 * badge createMany
 */
export type badgeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many badges.
   */
  data: Prisma.badgeCreateManyInput | Prisma.badgeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * badge createManyAndReturn
 */
export type badgeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the badge
   */
  select?: Prisma.badgeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the badge
   */
  omit?: Prisma.badgeOmit<ExtArgs> | null
  /**
   * The data used to create many badges.
   */
  data: Prisma.badgeCreateManyInput | Prisma.badgeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.badgeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * badge update
 */
export type badgeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the badge
   */
  select?: Prisma.badgeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the badge
   */
  omit?: Prisma.badgeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.badgeInclude<ExtArgs> | null
  /**
   * The data needed to update a badge.
   */
  data: Prisma.XOR<Prisma.badgeUpdateInput, Prisma.badgeUncheckedUpdateInput>
  /**
   * Choose, which badge to update.
   */
  where: Prisma.badgeWhereUniqueInput
}

/**
 * badge updateMany
 */
export type badgeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update badges.
   */
  data: Prisma.XOR<Prisma.badgeUpdateManyMutationInput, Prisma.badgeUncheckedUpdateManyInput>
  /**
   * Filter which badges to update
   */
  where?: Prisma.badgeWhereInput
  /**
   * Limit how many badges to update.
   */
  limit?: number
}

/**
 * badge updateManyAndReturn
 */
export type badgeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the badge
   */
  select?: Prisma.badgeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the badge
   */
  omit?: Prisma.badgeOmit<ExtArgs> | null
  /**
   * The data used to update badges.
   */
  data: Prisma.XOR<Prisma.badgeUpdateManyMutationInput, Prisma.badgeUncheckedUpdateManyInput>
  /**
   * Filter which badges to update
   */
  where?: Prisma.badgeWhereInput
  /**
   * Limit how many badges to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.badgeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * badge upsert
 */
export type badgeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the badge
   */
  select?: Prisma.badgeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the badge
   */
  omit?: Prisma.badgeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.badgeInclude<ExtArgs> | null
  /**
   * The filter to search for the badge to update in case it exists.
   */
  where: Prisma.badgeWhereUniqueInput
  /**
   * In case the badge found by the `where` argument doesn't exist, create a new badge with this data.
   */
  create: Prisma.XOR<Prisma.badgeCreateInput, Prisma.badgeUncheckedCreateInput>
  /**
   * In case the badge was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.badgeUpdateInput, Prisma.badgeUncheckedUpdateInput>
}

/**
 * badge delete
 */
export type badgeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the badge
   */
  select?: Prisma.badgeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the badge
   */
  omit?: Prisma.badgeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.badgeInclude<ExtArgs> | null
  /**
   * Filter which badge to delete.
   */
  where: Prisma.badgeWhereUniqueInput
}

/**
 * badge deleteMany
 */
export type badgeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which badges to delete
   */
  where?: Prisma.badgeWhereInput
  /**
   * Limit how many badges to delete.
   */
  limit?: number
}

/**
 * badge.user
 */
export type badge$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user
   */
  select?: Prisma.userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user
   */
  omit?: Prisma.userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.userInclude<ExtArgs> | null
  where?: Prisma.userWhereInput
}

/**
 * badge.userBadges
 */
export type badge$userBadgesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the userBadge
   */
  select?: Prisma.userBadgeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the userBadge
   */
  omit?: Prisma.userBadgeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.userBadgeInclude<ExtArgs> | null
  where?: Prisma.userBadgeWhereInput
  orderBy?: Prisma.userBadgeOrderByWithRelationInput | Prisma.userBadgeOrderByWithRelationInput[]
  cursor?: Prisma.userBadgeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserBadgeScalarFieldEnum | Prisma.UserBadgeScalarFieldEnum[]
}

/**
 * badge without action
 */
export type badgeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the badge
   */
  select?: Prisma.badgeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the badge
   */
  omit?: Prisma.badgeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.badgeInclude<ExtArgs> | null
}
