
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `categoryChapter` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model categoryChapter
 * 
 */
export type categoryChapterModel = runtime.Types.Result.DefaultSelection<Prisma.$categoryChapterPayload>

export type AggregateCategoryChapter = {
  _count: CategoryChapterCountAggregateOutputType | null
  _avg: CategoryChapterAvgAggregateOutputType | null
  _sum: CategoryChapterSumAggregateOutputType | null
  _min: CategoryChapterMinAggregateOutputType | null
  _max: CategoryChapterMaxAggregateOutputType | null
}

export type CategoryChapterAvgAggregateOutputType = {
  id: number | null
  chapterId: number | null
}

export type CategoryChapterSumAggregateOutputType = {
  id: number | null
  chapterId: number | null
}

export type CategoryChapterMinAggregateOutputType = {
  id: number | null
  chapterId: number | null
  chapterName: string | null
  chapterDescription: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CategoryChapterMaxAggregateOutputType = {
  id: number | null
  chapterId: number | null
  chapterName: string | null
  chapterDescription: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CategoryChapterCountAggregateOutputType = {
  id: number
  chapterId: number
  chapterName: number
  chapterDescription: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CategoryChapterAvgAggregateInputType = {
  id?: true
  chapterId?: true
}

export type CategoryChapterSumAggregateInputType = {
  id?: true
  chapterId?: true
}

export type CategoryChapterMinAggregateInputType = {
  id?: true
  chapterId?: true
  chapterName?: true
  chapterDescription?: true
  createdAt?: true
  updatedAt?: true
}

export type CategoryChapterMaxAggregateInputType = {
  id?: true
  chapterId?: true
  chapterName?: true
  chapterDescription?: true
  createdAt?: true
  updatedAt?: true
}

export type CategoryChapterCountAggregateInputType = {
  id?: true
  chapterId?: true
  chapterName?: true
  chapterDescription?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CategoryChapterAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which categoryChapter to aggregate.
   */
  where?: Prisma.categoryChapterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of categoryChapters to fetch.
   */
  orderBy?: Prisma.categoryChapterOrderByWithRelationInput | Prisma.categoryChapterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.categoryChapterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` categoryChapters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` categoryChapters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned categoryChapters
  **/
  _count?: true | CategoryChapterCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CategoryChapterAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CategoryChapterSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CategoryChapterMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CategoryChapterMaxAggregateInputType
}

export type GetCategoryChapterAggregateType<T extends CategoryChapterAggregateArgs> = {
      [P in keyof T & keyof AggregateCategoryChapter]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCategoryChapter[P]>
    : Prisma.GetScalarType<T[P], AggregateCategoryChapter[P]>
}




export type categoryChapterGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.categoryChapterWhereInput
  orderBy?: Prisma.categoryChapterOrderByWithAggregationInput | Prisma.categoryChapterOrderByWithAggregationInput[]
  by: Prisma.CategoryChapterScalarFieldEnum[] | Prisma.CategoryChapterScalarFieldEnum
  having?: Prisma.categoryChapterScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CategoryChapterCountAggregateInputType | true
  _avg?: CategoryChapterAvgAggregateInputType
  _sum?: CategoryChapterSumAggregateInputType
  _min?: CategoryChapterMinAggregateInputType
  _max?: CategoryChapterMaxAggregateInputType
}

export type CategoryChapterGroupByOutputType = {
  id: number
  chapterId: number
  chapterName: string
  chapterDescription: string | null
  createdAt: Date
  updatedAt: Date | null
  _count: CategoryChapterCountAggregateOutputType | null
  _avg: CategoryChapterAvgAggregateOutputType | null
  _sum: CategoryChapterSumAggregateOutputType | null
  _min: CategoryChapterMinAggregateOutputType | null
  _max: CategoryChapterMaxAggregateOutputType | null
}

type GetCategoryChapterGroupByPayload<T extends categoryChapterGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CategoryChapterGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CategoryChapterGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CategoryChapterGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CategoryChapterGroupByOutputType[P]>
      }
    >
  >



export type categoryChapterWhereInput = {
  AND?: Prisma.categoryChapterWhereInput | Prisma.categoryChapterWhereInput[]
  OR?: Prisma.categoryChapterWhereInput[]
  NOT?: Prisma.categoryChapterWhereInput | Prisma.categoryChapterWhereInput[]
  id?: Prisma.IntFilter<"categoryChapter"> | number
  chapterId?: Prisma.IntFilter<"categoryChapter"> | number
  chapterName?: Prisma.StringFilter<"categoryChapter"> | string
  chapterDescription?: Prisma.StringNullableFilter<"categoryChapter"> | string | null
  createdAt?: Prisma.DateTimeFilter<"categoryChapter"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"categoryChapter"> | Date | string | null
  category?: Prisma.CategoryListRelationFilter
}

export type categoryChapterOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  chapterName?: Prisma.SortOrder
  chapterDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.categoryOrderByRelationAggregateInput
}

export type categoryChapterWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  chapterId?: number
  chapterName?: string
  AND?: Prisma.categoryChapterWhereInput | Prisma.categoryChapterWhereInput[]
  OR?: Prisma.categoryChapterWhereInput[]
  NOT?: Prisma.categoryChapterWhereInput | Prisma.categoryChapterWhereInput[]
  chapterDescription?: Prisma.StringNullableFilter<"categoryChapter"> | string | null
  createdAt?: Prisma.DateTimeFilter<"categoryChapter"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"categoryChapter"> | Date | string | null
  category?: Prisma.CategoryListRelationFilter
}, "id" | "chapterId" | "chapterName">

export type categoryChapterOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  chapterName?: Prisma.SortOrder
  chapterDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.categoryChapterCountOrderByAggregateInput
  _avg?: Prisma.categoryChapterAvgOrderByAggregateInput
  _max?: Prisma.categoryChapterMaxOrderByAggregateInput
  _min?: Prisma.categoryChapterMinOrderByAggregateInput
  _sum?: Prisma.categoryChapterSumOrderByAggregateInput
}

export type categoryChapterScalarWhereWithAggregatesInput = {
  AND?: Prisma.categoryChapterScalarWhereWithAggregatesInput | Prisma.categoryChapterScalarWhereWithAggregatesInput[]
  OR?: Prisma.categoryChapterScalarWhereWithAggregatesInput[]
  NOT?: Prisma.categoryChapterScalarWhereWithAggregatesInput | Prisma.categoryChapterScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"categoryChapter"> | number
  chapterId?: Prisma.IntWithAggregatesFilter<"categoryChapter"> | number
  chapterName?: Prisma.StringWithAggregatesFilter<"categoryChapter"> | string
  chapterDescription?: Prisma.StringNullableWithAggregatesFilter<"categoryChapter"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"categoryChapter"> | Date | string
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"categoryChapter"> | Date | string | null
}

export type categoryChapterCreateInput = {
  chapterId: number
  chapterName: string
  chapterDescription?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  category?: Prisma.categoryCreateNestedManyWithoutCategoryChapterInput
}

export type categoryChapterUncheckedCreateInput = {
  id?: number
  chapterId: number
  chapterName: string
  chapterDescription?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  category?: Prisma.categoryUncheckedCreateNestedManyWithoutCategoryChapterInput
}

export type categoryChapterUpdateInput = {
  chapterId?: Prisma.IntFieldUpdateOperationsInput | number
  chapterName?: Prisma.StringFieldUpdateOperationsInput | string
  chapterDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.categoryUpdateManyWithoutCategoryChapterNestedInput
}

export type categoryChapterUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  chapterId?: Prisma.IntFieldUpdateOperationsInput | number
  chapterName?: Prisma.StringFieldUpdateOperationsInput | string
  chapterDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.categoryUncheckedUpdateManyWithoutCategoryChapterNestedInput
}

export type categoryChapterCreateManyInput = {
  id?: number
  chapterId: number
  chapterName: string
  chapterDescription?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type categoryChapterUpdateManyMutationInput = {
  chapterId?: Prisma.IntFieldUpdateOperationsInput | number
  chapterName?: Prisma.StringFieldUpdateOperationsInput | string
  chapterDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type categoryChapterUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  chapterId?: Prisma.IntFieldUpdateOperationsInput | number
  chapterName?: Prisma.StringFieldUpdateOperationsInput | string
  chapterDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CategoryChapterScalarRelationFilter = {
  is?: Prisma.categoryChapterWhereInput
  isNot?: Prisma.categoryChapterWhereInput
}

export type categoryChapterCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  chapterName?: Prisma.SortOrder
  chapterDescription?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type categoryChapterAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
}

export type categoryChapterMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  chapterName?: Prisma.SortOrder
  chapterDescription?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type categoryChapterMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  chapterName?: Prisma.SortOrder
  chapterDescription?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type categoryChapterSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
}

export type categoryChapterCreateNestedOneWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.categoryChapterCreateWithoutCategoryInput, Prisma.categoryChapterUncheckedCreateWithoutCategoryInput>
  connectOrCreate?: Prisma.categoryChapterCreateOrConnectWithoutCategoryInput
  connect?: Prisma.categoryChapterWhereUniqueInput
}

export type categoryChapterUpdateOneRequiredWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.categoryChapterCreateWithoutCategoryInput, Prisma.categoryChapterUncheckedCreateWithoutCategoryInput>
  connectOrCreate?: Prisma.categoryChapterCreateOrConnectWithoutCategoryInput
  upsert?: Prisma.categoryChapterUpsertWithoutCategoryInput
  connect?: Prisma.categoryChapterWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.categoryChapterUpdateToOneWithWhereWithoutCategoryInput, Prisma.categoryChapterUpdateWithoutCategoryInput>, Prisma.categoryChapterUncheckedUpdateWithoutCategoryInput>
}

export type categoryChapterCreateWithoutCategoryInput = {
  chapterId: number
  chapterName: string
  chapterDescription?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type categoryChapterUncheckedCreateWithoutCategoryInput = {
  id?: number
  chapterId: number
  chapterName: string
  chapterDescription?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type categoryChapterCreateOrConnectWithoutCategoryInput = {
  where: Prisma.categoryChapterWhereUniqueInput
  create: Prisma.XOR<Prisma.categoryChapterCreateWithoutCategoryInput, Prisma.categoryChapterUncheckedCreateWithoutCategoryInput>
}

export type categoryChapterUpsertWithoutCategoryInput = {
  update: Prisma.XOR<Prisma.categoryChapterUpdateWithoutCategoryInput, Prisma.categoryChapterUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.categoryChapterCreateWithoutCategoryInput, Prisma.categoryChapterUncheckedCreateWithoutCategoryInput>
  where?: Prisma.categoryChapterWhereInput
}

export type categoryChapterUpdateToOneWithWhereWithoutCategoryInput = {
  where?: Prisma.categoryChapterWhereInput
  data: Prisma.XOR<Prisma.categoryChapterUpdateWithoutCategoryInput, Prisma.categoryChapterUncheckedUpdateWithoutCategoryInput>
}

export type categoryChapterUpdateWithoutCategoryInput = {
  chapterId?: Prisma.IntFieldUpdateOperationsInput | number
  chapterName?: Prisma.StringFieldUpdateOperationsInput | string
  chapterDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type categoryChapterUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  chapterId?: Prisma.IntFieldUpdateOperationsInput | number
  chapterName?: Prisma.StringFieldUpdateOperationsInput | string
  chapterDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type CategoryChapterCountOutputType
 */

export type CategoryChapterCountOutputType = {
  category: number
}

export type CategoryChapterCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | CategoryChapterCountOutputTypeCountCategoryArgs
}

/**
 * CategoryChapterCountOutputType without action
 */
export type CategoryChapterCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CategoryChapterCountOutputType
   */
  select?: Prisma.CategoryChapterCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CategoryChapterCountOutputType without action
 */
export type CategoryChapterCountOutputTypeCountCategoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.categoryWhereInput
}


export type categoryChapterSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  chapterId?: boolean
  chapterName?: boolean
  chapterDescription?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  category?: boolean | Prisma.categoryChapter$categoryArgs<ExtArgs>
  _count?: boolean | Prisma.CategoryChapterCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["categoryChapter"]>

export type categoryChapterSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  chapterId?: boolean
  chapterName?: boolean
  chapterDescription?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["categoryChapter"]>

export type categoryChapterSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  chapterId?: boolean
  chapterName?: boolean
  chapterDescription?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["categoryChapter"]>

export type categoryChapterSelectScalar = {
  id?: boolean
  chapterId?: boolean
  chapterName?: boolean
  chapterDescription?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type categoryChapterOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "chapterId" | "chapterName" | "chapterDescription" | "createdAt" | "updatedAt", ExtArgs["result"]["categoryChapter"]>
export type categoryChapterInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.categoryChapter$categoryArgs<ExtArgs>
  _count?: boolean | Prisma.CategoryChapterCountOutputTypeDefaultArgs<ExtArgs>
}
export type categoryChapterIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type categoryChapterIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $categoryChapterPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "categoryChapter"
  objects: {
    category: Prisma.$categoryPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    chapterId: number
    chapterName: string
    chapterDescription: string | null
    createdAt: Date
    updatedAt: Date | null
  }, ExtArgs["result"]["categoryChapter"]>
  composites: {}
}

export type categoryChapterGetPayload<S extends boolean | null | undefined | categoryChapterDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$categoryChapterPayload, S>

export type categoryChapterCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<categoryChapterFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CategoryChapterCountAggregateInputType | true
  }

export interface categoryChapterDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['categoryChapter'], meta: { name: 'categoryChapter' } }
  /**
   * Find zero or one CategoryChapter that matches the filter.
   * @param {categoryChapterFindUniqueArgs} args - Arguments to find a CategoryChapter
   * @example
   * // Get one CategoryChapter
   * const categoryChapter = await prisma.categoryChapter.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends categoryChapterFindUniqueArgs>(args: Prisma.SelectSubset<T, categoryChapterFindUniqueArgs<ExtArgs>>): Prisma.Prisma__categoryChapterClient<runtime.Types.Result.GetResult<Prisma.$categoryChapterPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CategoryChapter that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {categoryChapterFindUniqueOrThrowArgs} args - Arguments to find a CategoryChapter
   * @example
   * // Get one CategoryChapter
   * const categoryChapter = await prisma.categoryChapter.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends categoryChapterFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, categoryChapterFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__categoryChapterClient<runtime.Types.Result.GetResult<Prisma.$categoryChapterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CategoryChapter that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {categoryChapterFindFirstArgs} args - Arguments to find a CategoryChapter
   * @example
   * // Get one CategoryChapter
   * const categoryChapter = await prisma.categoryChapter.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends categoryChapterFindFirstArgs>(args?: Prisma.SelectSubset<T, categoryChapterFindFirstArgs<ExtArgs>>): Prisma.Prisma__categoryChapterClient<runtime.Types.Result.GetResult<Prisma.$categoryChapterPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CategoryChapter that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {categoryChapterFindFirstOrThrowArgs} args - Arguments to find a CategoryChapter
   * @example
   * // Get one CategoryChapter
   * const categoryChapter = await prisma.categoryChapter.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends categoryChapterFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, categoryChapterFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__categoryChapterClient<runtime.Types.Result.GetResult<Prisma.$categoryChapterPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CategoryChapters that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {categoryChapterFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CategoryChapters
   * const categoryChapters = await prisma.categoryChapter.findMany()
   * 
   * // Get first 10 CategoryChapters
   * const categoryChapters = await prisma.categoryChapter.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const categoryChapterWithIdOnly = await prisma.categoryChapter.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends categoryChapterFindManyArgs>(args?: Prisma.SelectSubset<T, categoryChapterFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$categoryChapterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CategoryChapter.
   * @param {categoryChapterCreateArgs} args - Arguments to create a CategoryChapter.
   * @example
   * // Create one CategoryChapter
   * const CategoryChapter = await prisma.categoryChapter.create({
   *   data: {
   *     // ... data to create a CategoryChapter
   *   }
   * })
   * 
   */
  create<T extends categoryChapterCreateArgs>(args: Prisma.SelectSubset<T, categoryChapterCreateArgs<ExtArgs>>): Prisma.Prisma__categoryChapterClient<runtime.Types.Result.GetResult<Prisma.$categoryChapterPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CategoryChapters.
   * @param {categoryChapterCreateManyArgs} args - Arguments to create many CategoryChapters.
   * @example
   * // Create many CategoryChapters
   * const categoryChapter = await prisma.categoryChapter.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends categoryChapterCreateManyArgs>(args?: Prisma.SelectSubset<T, categoryChapterCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CategoryChapters and returns the data saved in the database.
   * @param {categoryChapterCreateManyAndReturnArgs} args - Arguments to create many CategoryChapters.
   * @example
   * // Create many CategoryChapters
   * const categoryChapter = await prisma.categoryChapter.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CategoryChapters and only return the `id`
   * const categoryChapterWithIdOnly = await prisma.categoryChapter.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends categoryChapterCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, categoryChapterCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$categoryChapterPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CategoryChapter.
   * @param {categoryChapterDeleteArgs} args - Arguments to delete one CategoryChapter.
   * @example
   * // Delete one CategoryChapter
   * const CategoryChapter = await prisma.categoryChapter.delete({
   *   where: {
   *     // ... filter to delete one CategoryChapter
   *   }
   * })
   * 
   */
  delete<T extends categoryChapterDeleteArgs>(args: Prisma.SelectSubset<T, categoryChapterDeleteArgs<ExtArgs>>): Prisma.Prisma__categoryChapterClient<runtime.Types.Result.GetResult<Prisma.$categoryChapterPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CategoryChapter.
   * @param {categoryChapterUpdateArgs} args - Arguments to update one CategoryChapter.
   * @example
   * // Update one CategoryChapter
   * const categoryChapter = await prisma.categoryChapter.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends categoryChapterUpdateArgs>(args: Prisma.SelectSubset<T, categoryChapterUpdateArgs<ExtArgs>>): Prisma.Prisma__categoryChapterClient<runtime.Types.Result.GetResult<Prisma.$categoryChapterPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CategoryChapters.
   * @param {categoryChapterDeleteManyArgs} args - Arguments to filter CategoryChapters to delete.
   * @example
   * // Delete a few CategoryChapters
   * const { count } = await prisma.categoryChapter.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends categoryChapterDeleteManyArgs>(args?: Prisma.SelectSubset<T, categoryChapterDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CategoryChapters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {categoryChapterUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CategoryChapters
   * const categoryChapter = await prisma.categoryChapter.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends categoryChapterUpdateManyArgs>(args: Prisma.SelectSubset<T, categoryChapterUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CategoryChapters and returns the data updated in the database.
   * @param {categoryChapterUpdateManyAndReturnArgs} args - Arguments to update many CategoryChapters.
   * @example
   * // Update many CategoryChapters
   * const categoryChapter = await prisma.categoryChapter.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CategoryChapters and only return the `id`
   * const categoryChapterWithIdOnly = await prisma.categoryChapter.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends categoryChapterUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, categoryChapterUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$categoryChapterPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CategoryChapter.
   * @param {categoryChapterUpsertArgs} args - Arguments to update or create a CategoryChapter.
   * @example
   * // Update or create a CategoryChapter
   * const categoryChapter = await prisma.categoryChapter.upsert({
   *   create: {
   *     // ... data to create a CategoryChapter
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CategoryChapter we want to update
   *   }
   * })
   */
  upsert<T extends categoryChapterUpsertArgs>(args: Prisma.SelectSubset<T, categoryChapterUpsertArgs<ExtArgs>>): Prisma.Prisma__categoryChapterClient<runtime.Types.Result.GetResult<Prisma.$categoryChapterPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CategoryChapters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {categoryChapterCountArgs} args - Arguments to filter CategoryChapters to count.
   * @example
   * // Count the number of CategoryChapters
   * const count = await prisma.categoryChapter.count({
   *   where: {
   *     // ... the filter for the CategoryChapters we want to count
   *   }
   * })
  **/
  count<T extends categoryChapterCountArgs>(
    args?: Prisma.Subset<T, categoryChapterCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CategoryChapterCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CategoryChapter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CategoryChapterAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CategoryChapterAggregateArgs>(args: Prisma.Subset<T, CategoryChapterAggregateArgs>): Prisma.PrismaPromise<GetCategoryChapterAggregateType<T>>

  /**
   * Group by CategoryChapter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {categoryChapterGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends categoryChapterGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: categoryChapterGroupByArgs['orderBy'] }
      : { orderBy?: categoryChapterGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, categoryChapterGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCategoryChapterGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the categoryChapter model
 */
readonly fields: categoryChapterFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for categoryChapter.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__categoryChapterClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  category<T extends Prisma.categoryChapter$categoryArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.categoryChapter$categoryArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$categoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the categoryChapter model
 */
export interface categoryChapterFieldRefs {
  readonly id: Prisma.FieldRef<"categoryChapter", 'Int'>
  readonly chapterId: Prisma.FieldRef<"categoryChapter", 'Int'>
  readonly chapterName: Prisma.FieldRef<"categoryChapter", 'String'>
  readonly chapterDescription: Prisma.FieldRef<"categoryChapter", 'String'>
  readonly createdAt: Prisma.FieldRef<"categoryChapter", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"categoryChapter", 'DateTime'>
}
    

// Custom InputTypes
/**
 * categoryChapter findUnique
 */
export type categoryChapterFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the categoryChapter
   */
  select?: Prisma.categoryChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the categoryChapter
   */
  omit?: Prisma.categoryChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.categoryChapterInclude<ExtArgs> | null
  /**
   * Filter, which categoryChapter to fetch.
   */
  where: Prisma.categoryChapterWhereUniqueInput
}

/**
 * categoryChapter findUniqueOrThrow
 */
export type categoryChapterFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the categoryChapter
   */
  select?: Prisma.categoryChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the categoryChapter
   */
  omit?: Prisma.categoryChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.categoryChapterInclude<ExtArgs> | null
  /**
   * Filter, which categoryChapter to fetch.
   */
  where: Prisma.categoryChapterWhereUniqueInput
}

/**
 * categoryChapter findFirst
 */
export type categoryChapterFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the categoryChapter
   */
  select?: Prisma.categoryChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the categoryChapter
   */
  omit?: Prisma.categoryChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.categoryChapterInclude<ExtArgs> | null
  /**
   * Filter, which categoryChapter to fetch.
   */
  where?: Prisma.categoryChapterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of categoryChapters to fetch.
   */
  orderBy?: Prisma.categoryChapterOrderByWithRelationInput | Prisma.categoryChapterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for categoryChapters.
   */
  cursor?: Prisma.categoryChapterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` categoryChapters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` categoryChapters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of categoryChapters.
   */
  distinct?: Prisma.CategoryChapterScalarFieldEnum | Prisma.CategoryChapterScalarFieldEnum[]
}

/**
 * categoryChapter findFirstOrThrow
 */
export type categoryChapterFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the categoryChapter
   */
  select?: Prisma.categoryChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the categoryChapter
   */
  omit?: Prisma.categoryChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.categoryChapterInclude<ExtArgs> | null
  /**
   * Filter, which categoryChapter to fetch.
   */
  where?: Prisma.categoryChapterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of categoryChapters to fetch.
   */
  orderBy?: Prisma.categoryChapterOrderByWithRelationInput | Prisma.categoryChapterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for categoryChapters.
   */
  cursor?: Prisma.categoryChapterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` categoryChapters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` categoryChapters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of categoryChapters.
   */
  distinct?: Prisma.CategoryChapterScalarFieldEnum | Prisma.CategoryChapterScalarFieldEnum[]
}

/**
 * categoryChapter findMany
 */
export type categoryChapterFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the categoryChapter
   */
  select?: Prisma.categoryChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the categoryChapter
   */
  omit?: Prisma.categoryChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.categoryChapterInclude<ExtArgs> | null
  /**
   * Filter, which categoryChapters to fetch.
   */
  where?: Prisma.categoryChapterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of categoryChapters to fetch.
   */
  orderBy?: Prisma.categoryChapterOrderByWithRelationInput | Prisma.categoryChapterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing categoryChapters.
   */
  cursor?: Prisma.categoryChapterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` categoryChapters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` categoryChapters.
   */
  skip?: number
  distinct?: Prisma.CategoryChapterScalarFieldEnum | Prisma.CategoryChapterScalarFieldEnum[]
}

/**
 * categoryChapter create
 */
export type categoryChapterCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the categoryChapter
   */
  select?: Prisma.categoryChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the categoryChapter
   */
  omit?: Prisma.categoryChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.categoryChapterInclude<ExtArgs> | null
  /**
   * The data needed to create a categoryChapter.
   */
  data: Prisma.XOR<Prisma.categoryChapterCreateInput, Prisma.categoryChapterUncheckedCreateInput>
}

/**
 * categoryChapter createMany
 */
export type categoryChapterCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many categoryChapters.
   */
  data: Prisma.categoryChapterCreateManyInput | Prisma.categoryChapterCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * categoryChapter createManyAndReturn
 */
export type categoryChapterCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the categoryChapter
   */
  select?: Prisma.categoryChapterSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the categoryChapter
   */
  omit?: Prisma.categoryChapterOmit<ExtArgs> | null
  /**
   * The data used to create many categoryChapters.
   */
  data: Prisma.categoryChapterCreateManyInput | Prisma.categoryChapterCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * categoryChapter update
 */
export type categoryChapterUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the categoryChapter
   */
  select?: Prisma.categoryChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the categoryChapter
   */
  omit?: Prisma.categoryChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.categoryChapterInclude<ExtArgs> | null
  /**
   * The data needed to update a categoryChapter.
   */
  data: Prisma.XOR<Prisma.categoryChapterUpdateInput, Prisma.categoryChapterUncheckedUpdateInput>
  /**
   * Choose, which categoryChapter to update.
   */
  where: Prisma.categoryChapterWhereUniqueInput
}

/**
 * categoryChapter updateMany
 */
export type categoryChapterUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update categoryChapters.
   */
  data: Prisma.XOR<Prisma.categoryChapterUpdateManyMutationInput, Prisma.categoryChapterUncheckedUpdateManyInput>
  /**
   * Filter which categoryChapters to update
   */
  where?: Prisma.categoryChapterWhereInput
  /**
   * Limit how many categoryChapters to update.
   */
  limit?: number
}

/**
 * categoryChapter updateManyAndReturn
 */
export type categoryChapterUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the categoryChapter
   */
  select?: Prisma.categoryChapterSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the categoryChapter
   */
  omit?: Prisma.categoryChapterOmit<ExtArgs> | null
  /**
   * The data used to update categoryChapters.
   */
  data: Prisma.XOR<Prisma.categoryChapterUpdateManyMutationInput, Prisma.categoryChapterUncheckedUpdateManyInput>
  /**
   * Filter which categoryChapters to update
   */
  where?: Prisma.categoryChapterWhereInput
  /**
   * Limit how many categoryChapters to update.
   */
  limit?: number
}

/**
 * categoryChapter upsert
 */
export type categoryChapterUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the categoryChapter
   */
  select?: Prisma.categoryChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the categoryChapter
   */
  omit?: Prisma.categoryChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.categoryChapterInclude<ExtArgs> | null
  /**
   * The filter to search for the categoryChapter to update in case it exists.
   */
  where: Prisma.categoryChapterWhereUniqueInput
  /**
   * In case the categoryChapter found by the `where` argument doesn't exist, create a new categoryChapter with this data.
   */
  create: Prisma.XOR<Prisma.categoryChapterCreateInput, Prisma.categoryChapterUncheckedCreateInput>
  /**
   * In case the categoryChapter was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.categoryChapterUpdateInput, Prisma.categoryChapterUncheckedUpdateInput>
}

/**
 * categoryChapter delete
 */
export type categoryChapterDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the categoryChapter
   */
  select?: Prisma.categoryChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the categoryChapter
   */
  omit?: Prisma.categoryChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.categoryChapterInclude<ExtArgs> | null
  /**
   * Filter which categoryChapter to delete.
   */
  where: Prisma.categoryChapterWhereUniqueInput
}

/**
 * categoryChapter deleteMany
 */
export type categoryChapterDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which categoryChapters to delete
   */
  where?: Prisma.categoryChapterWhereInput
  /**
   * Limit how many categoryChapters to delete.
   */
  limit?: number
}

/**
 * categoryChapter.category
 */
export type categoryChapter$categoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the category
   */
  select?: Prisma.categorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the category
   */
  omit?: Prisma.categoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.categoryInclude<ExtArgs> | null
  where?: Prisma.categoryWhereInput
  orderBy?: Prisma.categoryOrderByWithRelationInput | Prisma.categoryOrderByWithRelationInput[]
  cursor?: Prisma.categoryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CategoryScalarFieldEnum | Prisma.CategoryScalarFieldEnum[]
}

/**
 * categoryChapter without action
 */
export type categoryChapterDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the categoryChapter
   */
  select?: Prisma.categoryChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the categoryChapter
   */
  omit?: Prisma.categoryChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.categoryChapterInclude<ExtArgs> | null
}
