
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `helpOffer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model helpOffer
 * 
 */
export type helpOfferModel = runtime.Types.Result.DefaultSelection<Prisma.$helpOfferPayload>

export type AggregateHelpOffer = {
  _count: HelpOfferCountAggregateOutputType | null
  _min: HelpOfferMinAggregateOutputType | null
  _max: HelpOfferMaxAggregateOutputType | null
}

export type HelpOfferMinAggregateOutputType = {
  id: string | null
  requestId: string | null
  helperId: string | null
  offerDate: Date | null
  message: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type HelpOfferMaxAggregateOutputType = {
  id: string | null
  requestId: string | null
  helperId: string | null
  offerDate: Date | null
  message: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type HelpOfferCountAggregateOutputType = {
  id: number
  requestId: number
  helperId: number
  offerDate: number
  message: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type HelpOfferMinAggregateInputType = {
  id?: true
  requestId?: true
  helperId?: true
  offerDate?: true
  message?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type HelpOfferMaxAggregateInputType = {
  id?: true
  requestId?: true
  helperId?: true
  offerDate?: true
  message?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type HelpOfferCountAggregateInputType = {
  id?: true
  requestId?: true
  helperId?: true
  offerDate?: true
  message?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type HelpOfferAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which helpOffer to aggregate.
   */
  where?: Prisma.helpOfferWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of helpOffers to fetch.
   */
  orderBy?: Prisma.helpOfferOrderByWithRelationInput | Prisma.helpOfferOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.helpOfferWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` helpOffers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` helpOffers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned helpOffers
  **/
  _count?: true | HelpOfferCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HelpOfferMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HelpOfferMaxAggregateInputType
}

export type GetHelpOfferAggregateType<T extends HelpOfferAggregateArgs> = {
      [P in keyof T & keyof AggregateHelpOffer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHelpOffer[P]>
    : Prisma.GetScalarType<T[P], AggregateHelpOffer[P]>
}




export type helpOfferGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.helpOfferWhereInput
  orderBy?: Prisma.helpOfferOrderByWithAggregationInput | Prisma.helpOfferOrderByWithAggregationInput[]
  by: Prisma.HelpOfferScalarFieldEnum[] | Prisma.HelpOfferScalarFieldEnum
  having?: Prisma.helpOfferScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HelpOfferCountAggregateInputType | true
  _min?: HelpOfferMinAggregateInputType
  _max?: HelpOfferMaxAggregateInputType
}

export type HelpOfferGroupByOutputType = {
  id: string
  requestId: string
  helperId: string
  offerDate: Date
  message: string | null
  status: string | null
  createdAt: Date
  updatedAt: Date | null
  _count: HelpOfferCountAggregateOutputType | null
  _min: HelpOfferMinAggregateOutputType | null
  _max: HelpOfferMaxAggregateOutputType | null
}

type GetHelpOfferGroupByPayload<T extends helpOfferGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HelpOfferGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HelpOfferGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HelpOfferGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HelpOfferGroupByOutputType[P]>
      }
    >
  >



export type helpOfferWhereInput = {
  AND?: Prisma.helpOfferWhereInput | Prisma.helpOfferWhereInput[]
  OR?: Prisma.helpOfferWhereInput[]
  NOT?: Prisma.helpOfferWhereInput | Prisma.helpOfferWhereInput[]
  id?: Prisma.StringFilter<"helpOffer"> | string
  requestId?: Prisma.StringFilter<"helpOffer"> | string
  helperId?: Prisma.StringFilter<"helpOffer"> | string
  offerDate?: Prisma.DateTimeFilter<"helpOffer"> | Date | string
  message?: Prisma.StringNullableFilter<"helpOffer"> | string | null
  status?: Prisma.StringNullableFilter<"helpOffer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"helpOffer"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"helpOffer"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.userWhereInput>
  helpRequest?: Prisma.XOR<Prisma.HelpRequestScalarRelationFilter, Prisma.helpRequestWhereInput>
}

export type helpOfferOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  helperId?: Prisma.SortOrder
  offerDate?: Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.userOrderByWithRelationInput
  helpRequest?: Prisma.helpRequestOrderByWithRelationInput
}

export type helpOfferWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.helpOfferWhereInput | Prisma.helpOfferWhereInput[]
  OR?: Prisma.helpOfferWhereInput[]
  NOT?: Prisma.helpOfferWhereInput | Prisma.helpOfferWhereInput[]
  requestId?: Prisma.StringFilter<"helpOffer"> | string
  helperId?: Prisma.StringFilter<"helpOffer"> | string
  offerDate?: Prisma.DateTimeFilter<"helpOffer"> | Date | string
  message?: Prisma.StringNullableFilter<"helpOffer"> | string | null
  status?: Prisma.StringNullableFilter<"helpOffer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"helpOffer"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"helpOffer"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.userWhereInput>
  helpRequest?: Prisma.XOR<Prisma.HelpRequestScalarRelationFilter, Prisma.helpRequestWhereInput>
}, "id">

export type helpOfferOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  helperId?: Prisma.SortOrder
  offerDate?: Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.helpOfferCountOrderByAggregateInput
  _max?: Prisma.helpOfferMaxOrderByAggregateInput
  _min?: Prisma.helpOfferMinOrderByAggregateInput
}

export type helpOfferScalarWhereWithAggregatesInput = {
  AND?: Prisma.helpOfferScalarWhereWithAggregatesInput | Prisma.helpOfferScalarWhereWithAggregatesInput[]
  OR?: Prisma.helpOfferScalarWhereWithAggregatesInput[]
  NOT?: Prisma.helpOfferScalarWhereWithAggregatesInput | Prisma.helpOfferScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"helpOffer"> | string
  requestId?: Prisma.StringWithAggregatesFilter<"helpOffer"> | string
  helperId?: Prisma.StringWithAggregatesFilter<"helpOffer"> | string
  offerDate?: Prisma.DateTimeWithAggregatesFilter<"helpOffer"> | Date | string
  message?: Prisma.StringNullableWithAggregatesFilter<"helpOffer"> | string | null
  status?: Prisma.StringNullableWithAggregatesFilter<"helpOffer"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"helpOffer"> | Date | string
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"helpOffer"> | Date | string | null
}

export type helpOfferCreateInput = {
  id?: string
  offerDate: Date | string
  message?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  user: Prisma.userCreateNestedOneWithoutHelpOfferInput
  helpRequest: Prisma.helpRequestCreateNestedOneWithoutHelpOfferInput
}

export type helpOfferUncheckedCreateInput = {
  id?: string
  requestId: string
  helperId: string
  offerDate: Date | string
  message?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type helpOfferUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  offerDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.userUpdateOneRequiredWithoutHelpOfferNestedInput
  helpRequest?: Prisma.helpRequestUpdateOneRequiredWithoutHelpOfferNestedInput
}

export type helpOfferUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  helperId?: Prisma.StringFieldUpdateOperationsInput | string
  offerDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type helpOfferCreateManyInput = {
  id?: string
  requestId: string
  helperId: string
  offerDate: Date | string
  message?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type helpOfferUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  offerDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type helpOfferUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  helperId?: Prisma.StringFieldUpdateOperationsInput | string
  offerDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type helpOfferCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  helperId?: Prisma.SortOrder
  offerDate?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type helpOfferMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  helperId?: Prisma.SortOrder
  offerDate?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type helpOfferMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  helperId?: Prisma.SortOrder
  offerDate?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type HelpOfferListRelationFilter = {
  every?: Prisma.helpOfferWhereInput
  some?: Prisma.helpOfferWhereInput
  none?: Prisma.helpOfferWhereInput
}

export type helpOfferOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type helpOfferCreateNestedManyWithoutHelpRequestInput = {
  create?: Prisma.XOR<Prisma.helpOfferCreateWithoutHelpRequestInput, Prisma.helpOfferUncheckedCreateWithoutHelpRequestInput> | Prisma.helpOfferCreateWithoutHelpRequestInput[] | Prisma.helpOfferUncheckedCreateWithoutHelpRequestInput[]
  connectOrCreate?: Prisma.helpOfferCreateOrConnectWithoutHelpRequestInput | Prisma.helpOfferCreateOrConnectWithoutHelpRequestInput[]
  createMany?: Prisma.helpOfferCreateManyHelpRequestInputEnvelope
  connect?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
}

export type helpOfferUncheckedCreateNestedManyWithoutHelpRequestInput = {
  create?: Prisma.XOR<Prisma.helpOfferCreateWithoutHelpRequestInput, Prisma.helpOfferUncheckedCreateWithoutHelpRequestInput> | Prisma.helpOfferCreateWithoutHelpRequestInput[] | Prisma.helpOfferUncheckedCreateWithoutHelpRequestInput[]
  connectOrCreate?: Prisma.helpOfferCreateOrConnectWithoutHelpRequestInput | Prisma.helpOfferCreateOrConnectWithoutHelpRequestInput[]
  createMany?: Prisma.helpOfferCreateManyHelpRequestInputEnvelope
  connect?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
}

export type helpOfferUpdateManyWithoutHelpRequestNestedInput = {
  create?: Prisma.XOR<Prisma.helpOfferCreateWithoutHelpRequestInput, Prisma.helpOfferUncheckedCreateWithoutHelpRequestInput> | Prisma.helpOfferCreateWithoutHelpRequestInput[] | Prisma.helpOfferUncheckedCreateWithoutHelpRequestInput[]
  connectOrCreate?: Prisma.helpOfferCreateOrConnectWithoutHelpRequestInput | Prisma.helpOfferCreateOrConnectWithoutHelpRequestInput[]
  upsert?: Prisma.helpOfferUpsertWithWhereUniqueWithoutHelpRequestInput | Prisma.helpOfferUpsertWithWhereUniqueWithoutHelpRequestInput[]
  createMany?: Prisma.helpOfferCreateManyHelpRequestInputEnvelope
  set?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  disconnect?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  delete?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  connect?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  update?: Prisma.helpOfferUpdateWithWhereUniqueWithoutHelpRequestInput | Prisma.helpOfferUpdateWithWhereUniqueWithoutHelpRequestInput[]
  updateMany?: Prisma.helpOfferUpdateManyWithWhereWithoutHelpRequestInput | Prisma.helpOfferUpdateManyWithWhereWithoutHelpRequestInput[]
  deleteMany?: Prisma.helpOfferScalarWhereInput | Prisma.helpOfferScalarWhereInput[]
}

export type helpOfferUncheckedUpdateManyWithoutHelpRequestNestedInput = {
  create?: Prisma.XOR<Prisma.helpOfferCreateWithoutHelpRequestInput, Prisma.helpOfferUncheckedCreateWithoutHelpRequestInput> | Prisma.helpOfferCreateWithoutHelpRequestInput[] | Prisma.helpOfferUncheckedCreateWithoutHelpRequestInput[]
  connectOrCreate?: Prisma.helpOfferCreateOrConnectWithoutHelpRequestInput | Prisma.helpOfferCreateOrConnectWithoutHelpRequestInput[]
  upsert?: Prisma.helpOfferUpsertWithWhereUniqueWithoutHelpRequestInput | Prisma.helpOfferUpsertWithWhereUniqueWithoutHelpRequestInput[]
  createMany?: Prisma.helpOfferCreateManyHelpRequestInputEnvelope
  set?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  disconnect?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  delete?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  connect?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  update?: Prisma.helpOfferUpdateWithWhereUniqueWithoutHelpRequestInput | Prisma.helpOfferUpdateWithWhereUniqueWithoutHelpRequestInput[]
  updateMany?: Prisma.helpOfferUpdateManyWithWhereWithoutHelpRequestInput | Prisma.helpOfferUpdateManyWithWhereWithoutHelpRequestInput[]
  deleteMany?: Prisma.helpOfferScalarWhereInput | Prisma.helpOfferScalarWhereInput[]
}

export type helpOfferCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.helpOfferCreateWithoutUserInput, Prisma.helpOfferUncheckedCreateWithoutUserInput> | Prisma.helpOfferCreateWithoutUserInput[] | Prisma.helpOfferUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.helpOfferCreateOrConnectWithoutUserInput | Prisma.helpOfferCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.helpOfferCreateManyUserInputEnvelope
  connect?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
}

export type helpOfferUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.helpOfferCreateWithoutUserInput, Prisma.helpOfferUncheckedCreateWithoutUserInput> | Prisma.helpOfferCreateWithoutUserInput[] | Prisma.helpOfferUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.helpOfferCreateOrConnectWithoutUserInput | Prisma.helpOfferCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.helpOfferCreateManyUserInputEnvelope
  connect?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
}

export type helpOfferUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.helpOfferCreateWithoutUserInput, Prisma.helpOfferUncheckedCreateWithoutUserInput> | Prisma.helpOfferCreateWithoutUserInput[] | Prisma.helpOfferUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.helpOfferCreateOrConnectWithoutUserInput | Prisma.helpOfferCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.helpOfferUpsertWithWhereUniqueWithoutUserInput | Prisma.helpOfferUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.helpOfferCreateManyUserInputEnvelope
  set?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  disconnect?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  delete?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  connect?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  update?: Prisma.helpOfferUpdateWithWhereUniqueWithoutUserInput | Prisma.helpOfferUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.helpOfferUpdateManyWithWhereWithoutUserInput | Prisma.helpOfferUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.helpOfferScalarWhereInput | Prisma.helpOfferScalarWhereInput[]
}

export type helpOfferUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.helpOfferCreateWithoutUserInput, Prisma.helpOfferUncheckedCreateWithoutUserInput> | Prisma.helpOfferCreateWithoutUserInput[] | Prisma.helpOfferUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.helpOfferCreateOrConnectWithoutUserInput | Prisma.helpOfferCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.helpOfferUpsertWithWhereUniqueWithoutUserInput | Prisma.helpOfferUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.helpOfferCreateManyUserInputEnvelope
  set?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  disconnect?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  delete?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  connect?: Prisma.helpOfferWhereUniqueInput | Prisma.helpOfferWhereUniqueInput[]
  update?: Prisma.helpOfferUpdateWithWhereUniqueWithoutUserInput | Prisma.helpOfferUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.helpOfferUpdateManyWithWhereWithoutUserInput | Prisma.helpOfferUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.helpOfferScalarWhereInput | Prisma.helpOfferScalarWhereInput[]
}

export type helpOfferCreateWithoutHelpRequestInput = {
  id?: string
  offerDate: Date | string
  message?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  user: Prisma.userCreateNestedOneWithoutHelpOfferInput
}

export type helpOfferUncheckedCreateWithoutHelpRequestInput = {
  id?: string
  helperId: string
  offerDate: Date | string
  message?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type helpOfferCreateOrConnectWithoutHelpRequestInput = {
  where: Prisma.helpOfferWhereUniqueInput
  create: Prisma.XOR<Prisma.helpOfferCreateWithoutHelpRequestInput, Prisma.helpOfferUncheckedCreateWithoutHelpRequestInput>
}

export type helpOfferCreateManyHelpRequestInputEnvelope = {
  data: Prisma.helpOfferCreateManyHelpRequestInput | Prisma.helpOfferCreateManyHelpRequestInput[]
  skipDuplicates?: boolean
}

export type helpOfferUpsertWithWhereUniqueWithoutHelpRequestInput = {
  where: Prisma.helpOfferWhereUniqueInput
  update: Prisma.XOR<Prisma.helpOfferUpdateWithoutHelpRequestInput, Prisma.helpOfferUncheckedUpdateWithoutHelpRequestInput>
  create: Prisma.XOR<Prisma.helpOfferCreateWithoutHelpRequestInput, Prisma.helpOfferUncheckedCreateWithoutHelpRequestInput>
}

export type helpOfferUpdateWithWhereUniqueWithoutHelpRequestInput = {
  where: Prisma.helpOfferWhereUniqueInput
  data: Prisma.XOR<Prisma.helpOfferUpdateWithoutHelpRequestInput, Prisma.helpOfferUncheckedUpdateWithoutHelpRequestInput>
}

export type helpOfferUpdateManyWithWhereWithoutHelpRequestInput = {
  where: Prisma.helpOfferScalarWhereInput
  data: Prisma.XOR<Prisma.helpOfferUpdateManyMutationInput, Prisma.helpOfferUncheckedUpdateManyWithoutHelpRequestInput>
}

export type helpOfferScalarWhereInput = {
  AND?: Prisma.helpOfferScalarWhereInput | Prisma.helpOfferScalarWhereInput[]
  OR?: Prisma.helpOfferScalarWhereInput[]
  NOT?: Prisma.helpOfferScalarWhereInput | Prisma.helpOfferScalarWhereInput[]
  id?: Prisma.StringFilter<"helpOffer"> | string
  requestId?: Prisma.StringFilter<"helpOffer"> | string
  helperId?: Prisma.StringFilter<"helpOffer"> | string
  offerDate?: Prisma.DateTimeFilter<"helpOffer"> | Date | string
  message?: Prisma.StringNullableFilter<"helpOffer"> | string | null
  status?: Prisma.StringNullableFilter<"helpOffer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"helpOffer"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"helpOffer"> | Date | string | null
}

export type helpOfferCreateWithoutUserInput = {
  id?: string
  offerDate: Date | string
  message?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  helpRequest: Prisma.helpRequestCreateNestedOneWithoutHelpOfferInput
}

export type helpOfferUncheckedCreateWithoutUserInput = {
  id?: string
  requestId: string
  offerDate: Date | string
  message?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type helpOfferCreateOrConnectWithoutUserInput = {
  where: Prisma.helpOfferWhereUniqueInput
  create: Prisma.XOR<Prisma.helpOfferCreateWithoutUserInput, Prisma.helpOfferUncheckedCreateWithoutUserInput>
}

export type helpOfferCreateManyUserInputEnvelope = {
  data: Prisma.helpOfferCreateManyUserInput | Prisma.helpOfferCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type helpOfferUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.helpOfferWhereUniqueInput
  update: Prisma.XOR<Prisma.helpOfferUpdateWithoutUserInput, Prisma.helpOfferUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.helpOfferCreateWithoutUserInput, Prisma.helpOfferUncheckedCreateWithoutUserInput>
}

export type helpOfferUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.helpOfferWhereUniqueInput
  data: Prisma.XOR<Prisma.helpOfferUpdateWithoutUserInput, Prisma.helpOfferUncheckedUpdateWithoutUserInput>
}

export type helpOfferUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.helpOfferScalarWhereInput
  data: Prisma.XOR<Prisma.helpOfferUpdateManyMutationInput, Prisma.helpOfferUncheckedUpdateManyWithoutUserInput>
}

export type helpOfferCreateManyHelpRequestInput = {
  id?: string
  helperId: string
  offerDate: Date | string
  message?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type helpOfferUpdateWithoutHelpRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  offerDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.userUpdateOneRequiredWithoutHelpOfferNestedInput
}

export type helpOfferUncheckedUpdateWithoutHelpRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  helperId?: Prisma.StringFieldUpdateOperationsInput | string
  offerDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type helpOfferUncheckedUpdateManyWithoutHelpRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  helperId?: Prisma.StringFieldUpdateOperationsInput | string
  offerDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type helpOfferCreateManyUserInput = {
  id?: string
  requestId: string
  offerDate: Date | string
  message?: string | null
  status?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type helpOfferUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  offerDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  helpRequest?: Prisma.helpRequestUpdateOneRequiredWithoutHelpOfferNestedInput
}

export type helpOfferUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  offerDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type helpOfferUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  offerDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type helpOfferSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestId?: boolean
  helperId?: boolean
  offerDate?: boolean
  message?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
  helpRequest?: boolean | Prisma.helpRequestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["helpOffer"]>

export type helpOfferSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestId?: boolean
  helperId?: boolean
  offerDate?: boolean
  message?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
  helpRequest?: boolean | Prisma.helpRequestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["helpOffer"]>

export type helpOfferSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestId?: boolean
  helperId?: boolean
  offerDate?: boolean
  message?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
  helpRequest?: boolean | Prisma.helpRequestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["helpOffer"]>

export type helpOfferSelectScalar = {
  id?: boolean
  requestId?: boolean
  helperId?: boolean
  offerDate?: boolean
  message?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type helpOfferOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "requestId" | "helperId" | "offerDate" | "message" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["helpOffer"]>
export type helpOfferInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
  helpRequest?: boolean | Prisma.helpRequestDefaultArgs<ExtArgs>
}
export type helpOfferIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
  helpRequest?: boolean | Prisma.helpRequestDefaultArgs<ExtArgs>
}
export type helpOfferIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
  helpRequest?: boolean | Prisma.helpRequestDefaultArgs<ExtArgs>
}

export type $helpOfferPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "helpOffer"
  objects: {
    user: Prisma.$userPayload<ExtArgs>
    helpRequest: Prisma.$helpRequestPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    requestId: string
    helperId: string
    offerDate: Date
    message: string | null
    status: string | null
    createdAt: Date
    updatedAt: Date | null
  }, ExtArgs["result"]["helpOffer"]>
  composites: {}
}

export type helpOfferGetPayload<S extends boolean | null | undefined | helpOfferDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$helpOfferPayload, S>

export type helpOfferCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<helpOfferFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HelpOfferCountAggregateInputType | true
  }

export interface helpOfferDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['helpOffer'], meta: { name: 'helpOffer' } }
  /**
   * Find zero or one HelpOffer that matches the filter.
   * @param {helpOfferFindUniqueArgs} args - Arguments to find a HelpOffer
   * @example
   * // Get one HelpOffer
   * const helpOffer = await prisma.helpOffer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends helpOfferFindUniqueArgs>(args: Prisma.SelectSubset<T, helpOfferFindUniqueArgs<ExtArgs>>): Prisma.Prisma__helpOfferClient<runtime.Types.Result.GetResult<Prisma.$helpOfferPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one HelpOffer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {helpOfferFindUniqueOrThrowArgs} args - Arguments to find a HelpOffer
   * @example
   * // Get one HelpOffer
   * const helpOffer = await prisma.helpOffer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends helpOfferFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, helpOfferFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__helpOfferClient<runtime.Types.Result.GetResult<Prisma.$helpOfferPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HelpOffer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {helpOfferFindFirstArgs} args - Arguments to find a HelpOffer
   * @example
   * // Get one HelpOffer
   * const helpOffer = await prisma.helpOffer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends helpOfferFindFirstArgs>(args?: Prisma.SelectSubset<T, helpOfferFindFirstArgs<ExtArgs>>): Prisma.Prisma__helpOfferClient<runtime.Types.Result.GetResult<Prisma.$helpOfferPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HelpOffer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {helpOfferFindFirstOrThrowArgs} args - Arguments to find a HelpOffer
   * @example
   * // Get one HelpOffer
   * const helpOffer = await prisma.helpOffer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends helpOfferFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, helpOfferFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__helpOfferClient<runtime.Types.Result.GetResult<Prisma.$helpOfferPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more HelpOffers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {helpOfferFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all HelpOffers
   * const helpOffers = await prisma.helpOffer.findMany()
   * 
   * // Get first 10 HelpOffers
   * const helpOffers = await prisma.helpOffer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const helpOfferWithIdOnly = await prisma.helpOffer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends helpOfferFindManyArgs>(args?: Prisma.SelectSubset<T, helpOfferFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$helpOfferPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a HelpOffer.
   * @param {helpOfferCreateArgs} args - Arguments to create a HelpOffer.
   * @example
   * // Create one HelpOffer
   * const HelpOffer = await prisma.helpOffer.create({
   *   data: {
   *     // ... data to create a HelpOffer
   *   }
   * })
   * 
   */
  create<T extends helpOfferCreateArgs>(args: Prisma.SelectSubset<T, helpOfferCreateArgs<ExtArgs>>): Prisma.Prisma__helpOfferClient<runtime.Types.Result.GetResult<Prisma.$helpOfferPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many HelpOffers.
   * @param {helpOfferCreateManyArgs} args - Arguments to create many HelpOffers.
   * @example
   * // Create many HelpOffers
   * const helpOffer = await prisma.helpOffer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends helpOfferCreateManyArgs>(args?: Prisma.SelectSubset<T, helpOfferCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many HelpOffers and returns the data saved in the database.
   * @param {helpOfferCreateManyAndReturnArgs} args - Arguments to create many HelpOffers.
   * @example
   * // Create many HelpOffers
   * const helpOffer = await prisma.helpOffer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many HelpOffers and only return the `id`
   * const helpOfferWithIdOnly = await prisma.helpOffer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends helpOfferCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, helpOfferCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$helpOfferPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a HelpOffer.
   * @param {helpOfferDeleteArgs} args - Arguments to delete one HelpOffer.
   * @example
   * // Delete one HelpOffer
   * const HelpOffer = await prisma.helpOffer.delete({
   *   where: {
   *     // ... filter to delete one HelpOffer
   *   }
   * })
   * 
   */
  delete<T extends helpOfferDeleteArgs>(args: Prisma.SelectSubset<T, helpOfferDeleteArgs<ExtArgs>>): Prisma.Prisma__helpOfferClient<runtime.Types.Result.GetResult<Prisma.$helpOfferPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one HelpOffer.
   * @param {helpOfferUpdateArgs} args - Arguments to update one HelpOffer.
   * @example
   * // Update one HelpOffer
   * const helpOffer = await prisma.helpOffer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends helpOfferUpdateArgs>(args: Prisma.SelectSubset<T, helpOfferUpdateArgs<ExtArgs>>): Prisma.Prisma__helpOfferClient<runtime.Types.Result.GetResult<Prisma.$helpOfferPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more HelpOffers.
   * @param {helpOfferDeleteManyArgs} args - Arguments to filter HelpOffers to delete.
   * @example
   * // Delete a few HelpOffers
   * const { count } = await prisma.helpOffer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends helpOfferDeleteManyArgs>(args?: Prisma.SelectSubset<T, helpOfferDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HelpOffers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {helpOfferUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many HelpOffers
   * const helpOffer = await prisma.helpOffer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends helpOfferUpdateManyArgs>(args: Prisma.SelectSubset<T, helpOfferUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HelpOffers and returns the data updated in the database.
   * @param {helpOfferUpdateManyAndReturnArgs} args - Arguments to update many HelpOffers.
   * @example
   * // Update many HelpOffers
   * const helpOffer = await prisma.helpOffer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more HelpOffers and only return the `id`
   * const helpOfferWithIdOnly = await prisma.helpOffer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends helpOfferUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, helpOfferUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$helpOfferPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one HelpOffer.
   * @param {helpOfferUpsertArgs} args - Arguments to update or create a HelpOffer.
   * @example
   * // Update or create a HelpOffer
   * const helpOffer = await prisma.helpOffer.upsert({
   *   create: {
   *     // ... data to create a HelpOffer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the HelpOffer we want to update
   *   }
   * })
   */
  upsert<T extends helpOfferUpsertArgs>(args: Prisma.SelectSubset<T, helpOfferUpsertArgs<ExtArgs>>): Prisma.Prisma__helpOfferClient<runtime.Types.Result.GetResult<Prisma.$helpOfferPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of HelpOffers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {helpOfferCountArgs} args - Arguments to filter HelpOffers to count.
   * @example
   * // Count the number of HelpOffers
   * const count = await prisma.helpOffer.count({
   *   where: {
   *     // ... the filter for the HelpOffers we want to count
   *   }
   * })
  **/
  count<T extends helpOfferCountArgs>(
    args?: Prisma.Subset<T, helpOfferCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HelpOfferCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a HelpOffer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HelpOfferAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HelpOfferAggregateArgs>(args: Prisma.Subset<T, HelpOfferAggregateArgs>): Prisma.PrismaPromise<GetHelpOfferAggregateType<T>>

  /**
   * Group by HelpOffer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {helpOfferGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends helpOfferGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: helpOfferGroupByArgs['orderBy'] }
      : { orderBy?: helpOfferGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, helpOfferGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHelpOfferGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the helpOffer model
 */
readonly fields: helpOfferFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for helpOffer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__helpOfferClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.userDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.userDefaultArgs<ExtArgs>>): Prisma.Prisma__userClient<runtime.Types.Result.GetResult<Prisma.$userPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  helpRequest<T extends Prisma.helpRequestDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.helpRequestDefaultArgs<ExtArgs>>): Prisma.Prisma__helpRequestClient<runtime.Types.Result.GetResult<Prisma.$helpRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the helpOffer model
 */
export interface helpOfferFieldRefs {
  readonly id: Prisma.FieldRef<"helpOffer", 'String'>
  readonly requestId: Prisma.FieldRef<"helpOffer", 'String'>
  readonly helperId: Prisma.FieldRef<"helpOffer", 'String'>
  readonly offerDate: Prisma.FieldRef<"helpOffer", 'DateTime'>
  readonly message: Prisma.FieldRef<"helpOffer", 'String'>
  readonly status: Prisma.FieldRef<"helpOffer", 'String'>
  readonly createdAt: Prisma.FieldRef<"helpOffer", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"helpOffer", 'DateTime'>
}
    

// Custom InputTypes
/**
 * helpOffer findUnique
 */
export type helpOfferFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the helpOffer
   */
  select?: Prisma.helpOfferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the helpOffer
   */
  omit?: Prisma.helpOfferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.helpOfferInclude<ExtArgs> | null
  /**
   * Filter, which helpOffer to fetch.
   */
  where: Prisma.helpOfferWhereUniqueInput
}

/**
 * helpOffer findUniqueOrThrow
 */
export type helpOfferFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the helpOffer
   */
  select?: Prisma.helpOfferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the helpOffer
   */
  omit?: Prisma.helpOfferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.helpOfferInclude<ExtArgs> | null
  /**
   * Filter, which helpOffer to fetch.
   */
  where: Prisma.helpOfferWhereUniqueInput
}

/**
 * helpOffer findFirst
 */
export type helpOfferFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the helpOffer
   */
  select?: Prisma.helpOfferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the helpOffer
   */
  omit?: Prisma.helpOfferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.helpOfferInclude<ExtArgs> | null
  /**
   * Filter, which helpOffer to fetch.
   */
  where?: Prisma.helpOfferWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of helpOffers to fetch.
   */
  orderBy?: Prisma.helpOfferOrderByWithRelationInput | Prisma.helpOfferOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for helpOffers.
   */
  cursor?: Prisma.helpOfferWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` helpOffers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` helpOffers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of helpOffers.
   */
  distinct?: Prisma.HelpOfferScalarFieldEnum | Prisma.HelpOfferScalarFieldEnum[]
}

/**
 * helpOffer findFirstOrThrow
 */
export type helpOfferFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the helpOffer
   */
  select?: Prisma.helpOfferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the helpOffer
   */
  omit?: Prisma.helpOfferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.helpOfferInclude<ExtArgs> | null
  /**
   * Filter, which helpOffer to fetch.
   */
  where?: Prisma.helpOfferWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of helpOffers to fetch.
   */
  orderBy?: Prisma.helpOfferOrderByWithRelationInput | Prisma.helpOfferOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for helpOffers.
   */
  cursor?: Prisma.helpOfferWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` helpOffers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` helpOffers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of helpOffers.
   */
  distinct?: Prisma.HelpOfferScalarFieldEnum | Prisma.HelpOfferScalarFieldEnum[]
}

/**
 * helpOffer findMany
 */
export type helpOfferFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the helpOffer
   */
  select?: Prisma.helpOfferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the helpOffer
   */
  omit?: Prisma.helpOfferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.helpOfferInclude<ExtArgs> | null
  /**
   * Filter, which helpOffers to fetch.
   */
  where?: Prisma.helpOfferWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of helpOffers to fetch.
   */
  orderBy?: Prisma.helpOfferOrderByWithRelationInput | Prisma.helpOfferOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing helpOffers.
   */
  cursor?: Prisma.helpOfferWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` helpOffers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` helpOffers.
   */
  skip?: number
  distinct?: Prisma.HelpOfferScalarFieldEnum | Prisma.HelpOfferScalarFieldEnum[]
}

/**
 * helpOffer create
 */
export type helpOfferCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the helpOffer
   */
  select?: Prisma.helpOfferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the helpOffer
   */
  omit?: Prisma.helpOfferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.helpOfferInclude<ExtArgs> | null
  /**
   * The data needed to create a helpOffer.
   */
  data: Prisma.XOR<Prisma.helpOfferCreateInput, Prisma.helpOfferUncheckedCreateInput>
}

/**
 * helpOffer createMany
 */
export type helpOfferCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many helpOffers.
   */
  data: Prisma.helpOfferCreateManyInput | Prisma.helpOfferCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * helpOffer createManyAndReturn
 */
export type helpOfferCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the helpOffer
   */
  select?: Prisma.helpOfferSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the helpOffer
   */
  omit?: Prisma.helpOfferOmit<ExtArgs> | null
  /**
   * The data used to create many helpOffers.
   */
  data: Prisma.helpOfferCreateManyInput | Prisma.helpOfferCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.helpOfferIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * helpOffer update
 */
export type helpOfferUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the helpOffer
   */
  select?: Prisma.helpOfferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the helpOffer
   */
  omit?: Prisma.helpOfferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.helpOfferInclude<ExtArgs> | null
  /**
   * The data needed to update a helpOffer.
   */
  data: Prisma.XOR<Prisma.helpOfferUpdateInput, Prisma.helpOfferUncheckedUpdateInput>
  /**
   * Choose, which helpOffer to update.
   */
  where: Prisma.helpOfferWhereUniqueInput
}

/**
 * helpOffer updateMany
 */
export type helpOfferUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update helpOffers.
   */
  data: Prisma.XOR<Prisma.helpOfferUpdateManyMutationInput, Prisma.helpOfferUncheckedUpdateManyInput>
  /**
   * Filter which helpOffers to update
   */
  where?: Prisma.helpOfferWhereInput
  /**
   * Limit how many helpOffers to update.
   */
  limit?: number
}

/**
 * helpOffer updateManyAndReturn
 */
export type helpOfferUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the helpOffer
   */
  select?: Prisma.helpOfferSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the helpOffer
   */
  omit?: Prisma.helpOfferOmit<ExtArgs> | null
  /**
   * The data used to update helpOffers.
   */
  data: Prisma.XOR<Prisma.helpOfferUpdateManyMutationInput, Prisma.helpOfferUncheckedUpdateManyInput>
  /**
   * Filter which helpOffers to update
   */
  where?: Prisma.helpOfferWhereInput
  /**
   * Limit how many helpOffers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.helpOfferIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * helpOffer upsert
 */
export type helpOfferUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the helpOffer
   */
  select?: Prisma.helpOfferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the helpOffer
   */
  omit?: Prisma.helpOfferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.helpOfferInclude<ExtArgs> | null
  /**
   * The filter to search for the helpOffer to update in case it exists.
   */
  where: Prisma.helpOfferWhereUniqueInput
  /**
   * In case the helpOffer found by the `where` argument doesn't exist, create a new helpOffer with this data.
   */
  create: Prisma.XOR<Prisma.helpOfferCreateInput, Prisma.helpOfferUncheckedCreateInput>
  /**
   * In case the helpOffer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.helpOfferUpdateInput, Prisma.helpOfferUncheckedUpdateInput>
}

/**
 * helpOffer delete
 */
export type helpOfferDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the helpOffer
   */
  select?: Prisma.helpOfferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the helpOffer
   */
  omit?: Prisma.helpOfferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.helpOfferInclude<ExtArgs> | null
  /**
   * Filter which helpOffer to delete.
   */
  where: Prisma.helpOfferWhereUniqueInput
}

/**
 * helpOffer deleteMany
 */
export type helpOfferDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which helpOffers to delete
   */
  where?: Prisma.helpOfferWhereInput
  /**
   * Limit how many helpOffers to delete.
   */
  limit?: number
}

/**
 * helpOffer without action
 */
export type helpOfferDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the helpOffer
   */
  select?: Prisma.helpOfferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the helpOffer
   */
  omit?: Prisma.helpOfferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.helpOfferInclude<ExtArgs> | null
}
