
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `serviceRating` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model serviceRating
 * 
 */
export type serviceRatingModel = runtime.Types.Result.DefaultSelection<Prisma.$serviceRatingPayload>

export type AggregateServiceRating = {
  _count: ServiceRatingCountAggregateOutputType | null
  _avg: ServiceRatingAvgAggregateOutputType | null
  _sum: ServiceRatingSumAggregateOutputType | null
  _min: ServiceRatingMinAggregateOutputType | null
  _max: ServiceRatingMaxAggregateOutputType | null
}

export type ServiceRatingAvgAggregateOutputType = {
  rating: number | null
}

export type ServiceRatingSumAggregateOutputType = {
  rating: number | null
}

export type ServiceRatingMinAggregateOutputType = {
  serviceId: string | null
  userId: string | null
  rating: number | null
  comment: string | null
  ratingDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  id: string | null
}

export type ServiceRatingMaxAggregateOutputType = {
  serviceId: string | null
  userId: string | null
  rating: number | null
  comment: string | null
  ratingDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  id: string | null
}

export type ServiceRatingCountAggregateOutputType = {
  serviceId: number
  userId: number
  rating: number
  comment: number
  ratingDate: number
  createdAt: number
  updatedAt: number
  id: number
  _all: number
}


export type ServiceRatingAvgAggregateInputType = {
  rating?: true
}

export type ServiceRatingSumAggregateInputType = {
  rating?: true
}

export type ServiceRatingMinAggregateInputType = {
  serviceId?: true
  userId?: true
  rating?: true
  comment?: true
  ratingDate?: true
  createdAt?: true
  updatedAt?: true
  id?: true
}

export type ServiceRatingMaxAggregateInputType = {
  serviceId?: true
  userId?: true
  rating?: true
  comment?: true
  ratingDate?: true
  createdAt?: true
  updatedAt?: true
  id?: true
}

export type ServiceRatingCountAggregateInputType = {
  serviceId?: true
  userId?: true
  rating?: true
  comment?: true
  ratingDate?: true
  createdAt?: true
  updatedAt?: true
  id?: true
  _all?: true
}

export type ServiceRatingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which serviceRating to aggregate.
   */
  where?: Prisma.serviceRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of serviceRatings to fetch.
   */
  orderBy?: Prisma.serviceRatingOrderByWithRelationInput | Prisma.serviceRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.serviceRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` serviceRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` serviceRatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned serviceRatings
  **/
  _count?: true | ServiceRatingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ServiceRatingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ServiceRatingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ServiceRatingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ServiceRatingMaxAggregateInputType
}

export type GetServiceRatingAggregateType<T extends ServiceRatingAggregateArgs> = {
      [P in keyof T & keyof AggregateServiceRating]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateServiceRating[P]>
    : Prisma.GetScalarType<T[P], AggregateServiceRating[P]>
}




export type serviceRatingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.serviceRatingWhereInput
  orderBy?: Prisma.serviceRatingOrderByWithAggregationInput | Prisma.serviceRatingOrderByWithAggregationInput[]
  by: Prisma.ServiceRatingScalarFieldEnum[] | Prisma.ServiceRatingScalarFieldEnum
  having?: Prisma.serviceRatingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ServiceRatingCountAggregateInputType | true
  _avg?: ServiceRatingAvgAggregateInputType
  _sum?: ServiceRatingSumAggregateInputType
  _min?: ServiceRatingMinAggregateInputType
  _max?: ServiceRatingMaxAggregateInputType
}

export type ServiceRatingGroupByOutputType = {
  serviceId: string
  userId: string
  rating: number
  comment: string | null
  ratingDate: Date | null
  createdAt: Date
  updatedAt: Date | null
  id: string
  _count: ServiceRatingCountAggregateOutputType | null
  _avg: ServiceRatingAvgAggregateOutputType | null
  _sum: ServiceRatingSumAggregateOutputType | null
  _min: ServiceRatingMinAggregateOutputType | null
  _max: ServiceRatingMaxAggregateOutputType | null
}

type GetServiceRatingGroupByPayload<T extends serviceRatingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ServiceRatingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ServiceRatingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ServiceRatingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ServiceRatingGroupByOutputType[P]>
      }
    >
  >



export type serviceRatingWhereInput = {
  AND?: Prisma.serviceRatingWhereInput | Prisma.serviceRatingWhereInput[]
  OR?: Prisma.serviceRatingWhereInput[]
  NOT?: Prisma.serviceRatingWhereInput | Prisma.serviceRatingWhereInput[]
  serviceId?: Prisma.StringFilter<"serviceRating"> | string
  userId?: Prisma.StringFilter<"serviceRating"> | string
  rating?: Prisma.IntFilter<"serviceRating"> | number
  comment?: Prisma.StringNullableFilter<"serviceRating"> | string | null
  ratingDate?: Prisma.DateTimeNullableFilter<"serviceRating"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"serviceRating"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"serviceRating"> | Date | string | null
  id?: Prisma.StringFilter<"serviceRating"> | string
  localService?: Prisma.XOR<Prisma.LocalServiceScalarRelationFilter, Prisma.localServiceWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.userWhereInput>
}

export type serviceRatingOrderByWithRelationInput = {
  serviceId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  comment?: Prisma.SortOrderInput | Prisma.SortOrder
  ratingDate?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  id?: Prisma.SortOrder
  localService?: Prisma.localServiceOrderByWithRelationInput
  user?: Prisma.userOrderByWithRelationInput
}

export type serviceRatingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.serviceRatingWhereInput | Prisma.serviceRatingWhereInput[]
  OR?: Prisma.serviceRatingWhereInput[]
  NOT?: Prisma.serviceRatingWhereInput | Prisma.serviceRatingWhereInput[]
  serviceId?: Prisma.StringFilter<"serviceRating"> | string
  userId?: Prisma.StringFilter<"serviceRating"> | string
  rating?: Prisma.IntFilter<"serviceRating"> | number
  comment?: Prisma.StringNullableFilter<"serviceRating"> | string | null
  ratingDate?: Prisma.DateTimeNullableFilter<"serviceRating"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"serviceRating"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"serviceRating"> | Date | string | null
  localService?: Prisma.XOR<Prisma.LocalServiceScalarRelationFilter, Prisma.localServiceWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.userWhereInput>
}, "id">

export type serviceRatingOrderByWithAggregationInput = {
  serviceId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  comment?: Prisma.SortOrderInput | Prisma.SortOrder
  ratingDate?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  id?: Prisma.SortOrder
  _count?: Prisma.serviceRatingCountOrderByAggregateInput
  _avg?: Prisma.serviceRatingAvgOrderByAggregateInput
  _max?: Prisma.serviceRatingMaxOrderByAggregateInput
  _min?: Prisma.serviceRatingMinOrderByAggregateInput
  _sum?: Prisma.serviceRatingSumOrderByAggregateInput
}

export type serviceRatingScalarWhereWithAggregatesInput = {
  AND?: Prisma.serviceRatingScalarWhereWithAggregatesInput | Prisma.serviceRatingScalarWhereWithAggregatesInput[]
  OR?: Prisma.serviceRatingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.serviceRatingScalarWhereWithAggregatesInput | Prisma.serviceRatingScalarWhereWithAggregatesInput[]
  serviceId?: Prisma.StringWithAggregatesFilter<"serviceRating"> | string
  userId?: Prisma.StringWithAggregatesFilter<"serviceRating"> | string
  rating?: Prisma.IntWithAggregatesFilter<"serviceRating"> | number
  comment?: Prisma.StringNullableWithAggregatesFilter<"serviceRating"> | string | null
  ratingDate?: Prisma.DateTimeNullableWithAggregatesFilter<"serviceRating"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"serviceRating"> | Date | string
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"serviceRating"> | Date | string | null
  id?: Prisma.StringWithAggregatesFilter<"serviceRating"> | string
}

export type serviceRatingCreateInput = {
  rating: number
  comment?: string | null
  ratingDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  id?: string
  localService: Prisma.localServiceCreateNestedOneWithoutServiceRatingInput
  user: Prisma.userCreateNestedOneWithoutServiceRatingInput
}

export type serviceRatingUncheckedCreateInput = {
  serviceId: string
  userId: string
  rating: number
  comment?: string | null
  ratingDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  id?: string
}

export type serviceRatingUpdateInput = {
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ratingDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.StringFieldUpdateOperationsInput | string
  localService?: Prisma.localServiceUpdateOneRequiredWithoutServiceRatingNestedInput
  user?: Prisma.userUpdateOneRequiredWithoutServiceRatingNestedInput
}

export type serviceRatingUncheckedUpdateInput = {
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ratingDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type serviceRatingCreateManyInput = {
  serviceId: string
  userId: string
  rating: number
  comment?: string | null
  ratingDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  id?: string
}

export type serviceRatingUpdateManyMutationInput = {
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ratingDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type serviceRatingUncheckedUpdateManyInput = {
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ratingDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ServiceRatingListRelationFilter = {
  every?: Prisma.serviceRatingWhereInput
  some?: Prisma.serviceRatingWhereInput
  none?: Prisma.serviceRatingWhereInput
}

export type serviceRatingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type serviceRatingCountOrderByAggregateInput = {
  serviceId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  comment?: Prisma.SortOrder
  ratingDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  id?: Prisma.SortOrder
}

export type serviceRatingAvgOrderByAggregateInput = {
  rating?: Prisma.SortOrder
}

export type serviceRatingMaxOrderByAggregateInput = {
  serviceId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  comment?: Prisma.SortOrder
  ratingDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  id?: Prisma.SortOrder
}

export type serviceRatingMinOrderByAggregateInput = {
  serviceId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  comment?: Prisma.SortOrder
  ratingDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  id?: Prisma.SortOrder
}

export type serviceRatingSumOrderByAggregateInput = {
  rating?: Prisma.SortOrder
}

export type serviceRatingCreateNestedManyWithoutLocalServiceInput = {
  create?: Prisma.XOR<Prisma.serviceRatingCreateWithoutLocalServiceInput, Prisma.serviceRatingUncheckedCreateWithoutLocalServiceInput> | Prisma.serviceRatingCreateWithoutLocalServiceInput[] | Prisma.serviceRatingUncheckedCreateWithoutLocalServiceInput[]
  connectOrCreate?: Prisma.serviceRatingCreateOrConnectWithoutLocalServiceInput | Prisma.serviceRatingCreateOrConnectWithoutLocalServiceInput[]
  createMany?: Prisma.serviceRatingCreateManyLocalServiceInputEnvelope
  connect?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
}

export type serviceRatingUncheckedCreateNestedManyWithoutLocalServiceInput = {
  create?: Prisma.XOR<Prisma.serviceRatingCreateWithoutLocalServiceInput, Prisma.serviceRatingUncheckedCreateWithoutLocalServiceInput> | Prisma.serviceRatingCreateWithoutLocalServiceInput[] | Prisma.serviceRatingUncheckedCreateWithoutLocalServiceInput[]
  connectOrCreate?: Prisma.serviceRatingCreateOrConnectWithoutLocalServiceInput | Prisma.serviceRatingCreateOrConnectWithoutLocalServiceInput[]
  createMany?: Prisma.serviceRatingCreateManyLocalServiceInputEnvelope
  connect?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
}

export type serviceRatingUpdateManyWithoutLocalServiceNestedInput = {
  create?: Prisma.XOR<Prisma.serviceRatingCreateWithoutLocalServiceInput, Prisma.serviceRatingUncheckedCreateWithoutLocalServiceInput> | Prisma.serviceRatingCreateWithoutLocalServiceInput[] | Prisma.serviceRatingUncheckedCreateWithoutLocalServiceInput[]
  connectOrCreate?: Prisma.serviceRatingCreateOrConnectWithoutLocalServiceInput | Prisma.serviceRatingCreateOrConnectWithoutLocalServiceInput[]
  upsert?: Prisma.serviceRatingUpsertWithWhereUniqueWithoutLocalServiceInput | Prisma.serviceRatingUpsertWithWhereUniqueWithoutLocalServiceInput[]
  createMany?: Prisma.serviceRatingCreateManyLocalServiceInputEnvelope
  set?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  disconnect?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  delete?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  connect?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  update?: Prisma.serviceRatingUpdateWithWhereUniqueWithoutLocalServiceInput | Prisma.serviceRatingUpdateWithWhereUniqueWithoutLocalServiceInput[]
  updateMany?: Prisma.serviceRatingUpdateManyWithWhereWithoutLocalServiceInput | Prisma.serviceRatingUpdateManyWithWhereWithoutLocalServiceInput[]
  deleteMany?: Prisma.serviceRatingScalarWhereInput | Prisma.serviceRatingScalarWhereInput[]
}

export type serviceRatingUncheckedUpdateManyWithoutLocalServiceNestedInput = {
  create?: Prisma.XOR<Prisma.serviceRatingCreateWithoutLocalServiceInput, Prisma.serviceRatingUncheckedCreateWithoutLocalServiceInput> | Prisma.serviceRatingCreateWithoutLocalServiceInput[] | Prisma.serviceRatingUncheckedCreateWithoutLocalServiceInput[]
  connectOrCreate?: Prisma.serviceRatingCreateOrConnectWithoutLocalServiceInput | Prisma.serviceRatingCreateOrConnectWithoutLocalServiceInput[]
  upsert?: Prisma.serviceRatingUpsertWithWhereUniqueWithoutLocalServiceInput | Prisma.serviceRatingUpsertWithWhereUniqueWithoutLocalServiceInput[]
  createMany?: Prisma.serviceRatingCreateManyLocalServiceInputEnvelope
  set?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  disconnect?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  delete?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  connect?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  update?: Prisma.serviceRatingUpdateWithWhereUniqueWithoutLocalServiceInput | Prisma.serviceRatingUpdateWithWhereUniqueWithoutLocalServiceInput[]
  updateMany?: Prisma.serviceRatingUpdateManyWithWhereWithoutLocalServiceInput | Prisma.serviceRatingUpdateManyWithWhereWithoutLocalServiceInput[]
  deleteMany?: Prisma.serviceRatingScalarWhereInput | Prisma.serviceRatingScalarWhereInput[]
}

export type serviceRatingCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.serviceRatingCreateWithoutUserInput, Prisma.serviceRatingUncheckedCreateWithoutUserInput> | Prisma.serviceRatingCreateWithoutUserInput[] | Prisma.serviceRatingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.serviceRatingCreateOrConnectWithoutUserInput | Prisma.serviceRatingCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.serviceRatingCreateManyUserInputEnvelope
  connect?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
}

export type serviceRatingUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.serviceRatingCreateWithoutUserInput, Prisma.serviceRatingUncheckedCreateWithoutUserInput> | Prisma.serviceRatingCreateWithoutUserInput[] | Prisma.serviceRatingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.serviceRatingCreateOrConnectWithoutUserInput | Prisma.serviceRatingCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.serviceRatingCreateManyUserInputEnvelope
  connect?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
}

export type serviceRatingUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.serviceRatingCreateWithoutUserInput, Prisma.serviceRatingUncheckedCreateWithoutUserInput> | Prisma.serviceRatingCreateWithoutUserInput[] | Prisma.serviceRatingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.serviceRatingCreateOrConnectWithoutUserInput | Prisma.serviceRatingCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.serviceRatingUpsertWithWhereUniqueWithoutUserInput | Prisma.serviceRatingUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.serviceRatingCreateManyUserInputEnvelope
  set?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  disconnect?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  delete?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  connect?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  update?: Prisma.serviceRatingUpdateWithWhereUniqueWithoutUserInput | Prisma.serviceRatingUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.serviceRatingUpdateManyWithWhereWithoutUserInput | Prisma.serviceRatingUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.serviceRatingScalarWhereInput | Prisma.serviceRatingScalarWhereInput[]
}

export type serviceRatingUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.serviceRatingCreateWithoutUserInput, Prisma.serviceRatingUncheckedCreateWithoutUserInput> | Prisma.serviceRatingCreateWithoutUserInput[] | Prisma.serviceRatingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.serviceRatingCreateOrConnectWithoutUserInput | Prisma.serviceRatingCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.serviceRatingUpsertWithWhereUniqueWithoutUserInput | Prisma.serviceRatingUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.serviceRatingCreateManyUserInputEnvelope
  set?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  disconnect?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  delete?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  connect?: Prisma.serviceRatingWhereUniqueInput | Prisma.serviceRatingWhereUniqueInput[]
  update?: Prisma.serviceRatingUpdateWithWhereUniqueWithoutUserInput | Prisma.serviceRatingUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.serviceRatingUpdateManyWithWhereWithoutUserInput | Prisma.serviceRatingUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.serviceRatingScalarWhereInput | Prisma.serviceRatingScalarWhereInput[]
}

export type serviceRatingCreateWithoutLocalServiceInput = {
  rating: number
  comment?: string | null
  ratingDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  id?: string
  user: Prisma.userCreateNestedOneWithoutServiceRatingInput
}

export type serviceRatingUncheckedCreateWithoutLocalServiceInput = {
  userId: string
  rating: number
  comment?: string | null
  ratingDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  id?: string
}

export type serviceRatingCreateOrConnectWithoutLocalServiceInput = {
  where: Prisma.serviceRatingWhereUniqueInput
  create: Prisma.XOR<Prisma.serviceRatingCreateWithoutLocalServiceInput, Prisma.serviceRatingUncheckedCreateWithoutLocalServiceInput>
}

export type serviceRatingCreateManyLocalServiceInputEnvelope = {
  data: Prisma.serviceRatingCreateManyLocalServiceInput | Prisma.serviceRatingCreateManyLocalServiceInput[]
  skipDuplicates?: boolean
}

export type serviceRatingUpsertWithWhereUniqueWithoutLocalServiceInput = {
  where: Prisma.serviceRatingWhereUniqueInput
  update: Prisma.XOR<Prisma.serviceRatingUpdateWithoutLocalServiceInput, Prisma.serviceRatingUncheckedUpdateWithoutLocalServiceInput>
  create: Prisma.XOR<Prisma.serviceRatingCreateWithoutLocalServiceInput, Prisma.serviceRatingUncheckedCreateWithoutLocalServiceInput>
}

export type serviceRatingUpdateWithWhereUniqueWithoutLocalServiceInput = {
  where: Prisma.serviceRatingWhereUniqueInput
  data: Prisma.XOR<Prisma.serviceRatingUpdateWithoutLocalServiceInput, Prisma.serviceRatingUncheckedUpdateWithoutLocalServiceInput>
}

export type serviceRatingUpdateManyWithWhereWithoutLocalServiceInput = {
  where: Prisma.serviceRatingScalarWhereInput
  data: Prisma.XOR<Prisma.serviceRatingUpdateManyMutationInput, Prisma.serviceRatingUncheckedUpdateManyWithoutLocalServiceInput>
}

export type serviceRatingScalarWhereInput = {
  AND?: Prisma.serviceRatingScalarWhereInput | Prisma.serviceRatingScalarWhereInput[]
  OR?: Prisma.serviceRatingScalarWhereInput[]
  NOT?: Prisma.serviceRatingScalarWhereInput | Prisma.serviceRatingScalarWhereInput[]
  serviceId?: Prisma.StringFilter<"serviceRating"> | string
  userId?: Prisma.StringFilter<"serviceRating"> | string
  rating?: Prisma.IntFilter<"serviceRating"> | number
  comment?: Prisma.StringNullableFilter<"serviceRating"> | string | null
  ratingDate?: Prisma.DateTimeNullableFilter<"serviceRating"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"serviceRating"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"serviceRating"> | Date | string | null
  id?: Prisma.StringFilter<"serviceRating"> | string
}

export type serviceRatingCreateWithoutUserInput = {
  rating: number
  comment?: string | null
  ratingDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  id?: string
  localService: Prisma.localServiceCreateNestedOneWithoutServiceRatingInput
}

export type serviceRatingUncheckedCreateWithoutUserInput = {
  serviceId: string
  rating: number
  comment?: string | null
  ratingDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  id?: string
}

export type serviceRatingCreateOrConnectWithoutUserInput = {
  where: Prisma.serviceRatingWhereUniqueInput
  create: Prisma.XOR<Prisma.serviceRatingCreateWithoutUserInput, Prisma.serviceRatingUncheckedCreateWithoutUserInput>
}

export type serviceRatingCreateManyUserInputEnvelope = {
  data: Prisma.serviceRatingCreateManyUserInput | Prisma.serviceRatingCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type serviceRatingUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.serviceRatingWhereUniqueInput
  update: Prisma.XOR<Prisma.serviceRatingUpdateWithoutUserInput, Prisma.serviceRatingUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.serviceRatingCreateWithoutUserInput, Prisma.serviceRatingUncheckedCreateWithoutUserInput>
}

export type serviceRatingUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.serviceRatingWhereUniqueInput
  data: Prisma.XOR<Prisma.serviceRatingUpdateWithoutUserInput, Prisma.serviceRatingUncheckedUpdateWithoutUserInput>
}

export type serviceRatingUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.serviceRatingScalarWhereInput
  data: Prisma.XOR<Prisma.serviceRatingUpdateManyMutationInput, Prisma.serviceRatingUncheckedUpdateManyWithoutUserInput>
}

export type serviceRatingCreateManyLocalServiceInput = {
  userId: string
  rating: number
  comment?: string | null
  ratingDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  id?: string
}

export type serviceRatingUpdateWithoutLocalServiceInput = {
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ratingDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.userUpdateOneRequiredWithoutServiceRatingNestedInput
}

export type serviceRatingUncheckedUpdateWithoutLocalServiceInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ratingDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type serviceRatingUncheckedUpdateManyWithoutLocalServiceInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ratingDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type serviceRatingCreateManyUserInput = {
  serviceId: string
  rating: number
  comment?: string | null
  ratingDate?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  id?: string
}

export type serviceRatingUpdateWithoutUserInput = {
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ratingDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.StringFieldUpdateOperationsInput | string
  localService?: Prisma.localServiceUpdateOneRequiredWithoutServiceRatingNestedInput
}

export type serviceRatingUncheckedUpdateWithoutUserInput = {
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ratingDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type serviceRatingUncheckedUpdateManyWithoutUserInput = {
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ratingDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.StringFieldUpdateOperationsInput | string
}



export type serviceRatingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  serviceId?: boolean
  userId?: boolean
  rating?: boolean
  comment?: boolean
  ratingDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  id?: boolean
  localService?: boolean | Prisma.localServiceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceRating"]>

export type serviceRatingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  serviceId?: boolean
  userId?: boolean
  rating?: boolean
  comment?: boolean
  ratingDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  id?: boolean
  localService?: boolean | Prisma.localServiceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceRating"]>

export type serviceRatingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  serviceId?: boolean
  userId?: boolean
  rating?: boolean
  comment?: boolean
  ratingDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  id?: boolean
  localService?: boolean | Prisma.localServiceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceRating"]>

export type serviceRatingSelectScalar = {
  serviceId?: boolean
  userId?: boolean
  rating?: boolean
  comment?: boolean
  ratingDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  id?: boolean
}

export type serviceRatingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"serviceId" | "userId" | "rating" | "comment" | "ratingDate" | "createdAt" | "updatedAt" | "id", ExtArgs["result"]["serviceRating"]>
export type serviceRatingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  localService?: boolean | Prisma.localServiceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}
export type serviceRatingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  localService?: boolean | Prisma.localServiceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}
export type serviceRatingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  localService?: boolean | Prisma.localServiceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}

export type $serviceRatingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "serviceRating"
  objects: {
    localService: Prisma.$localServicePayload<ExtArgs>
    user: Prisma.$userPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    serviceId: string
    userId: string
    rating: number
    comment: string | null
    ratingDate: Date | null
    createdAt: Date
    updatedAt: Date | null
    id: string
  }, ExtArgs["result"]["serviceRating"]>
  composites: {}
}

export type serviceRatingGetPayload<S extends boolean | null | undefined | serviceRatingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$serviceRatingPayload, S>

export type serviceRatingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<serviceRatingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ServiceRatingCountAggregateInputType | true
  }

export interface serviceRatingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['serviceRating'], meta: { name: 'serviceRating' } }
  /**
   * Find zero or one ServiceRating that matches the filter.
   * @param {serviceRatingFindUniqueArgs} args - Arguments to find a ServiceRating
   * @example
   * // Get one ServiceRating
   * const serviceRating = await prisma.serviceRating.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends serviceRatingFindUniqueArgs>(args: Prisma.SelectSubset<T, serviceRatingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__serviceRatingClient<runtime.Types.Result.GetResult<Prisma.$serviceRatingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ServiceRating that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {serviceRatingFindUniqueOrThrowArgs} args - Arguments to find a ServiceRating
   * @example
   * // Get one ServiceRating
   * const serviceRating = await prisma.serviceRating.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends serviceRatingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, serviceRatingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__serviceRatingClient<runtime.Types.Result.GetResult<Prisma.$serviceRatingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceRating that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {serviceRatingFindFirstArgs} args - Arguments to find a ServiceRating
   * @example
   * // Get one ServiceRating
   * const serviceRating = await prisma.serviceRating.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends serviceRatingFindFirstArgs>(args?: Prisma.SelectSubset<T, serviceRatingFindFirstArgs<ExtArgs>>): Prisma.Prisma__serviceRatingClient<runtime.Types.Result.GetResult<Prisma.$serviceRatingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceRating that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {serviceRatingFindFirstOrThrowArgs} args - Arguments to find a ServiceRating
   * @example
   * // Get one ServiceRating
   * const serviceRating = await prisma.serviceRating.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends serviceRatingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, serviceRatingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__serviceRatingClient<runtime.Types.Result.GetResult<Prisma.$serviceRatingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ServiceRatings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {serviceRatingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ServiceRatings
   * const serviceRatings = await prisma.serviceRating.findMany()
   * 
   * // Get first 10 ServiceRatings
   * const serviceRatings = await prisma.serviceRating.findMany({ take: 10 })
   * 
   * // Only select the `serviceId`
   * const serviceRatingWithServiceIdOnly = await prisma.serviceRating.findMany({ select: { serviceId: true } })
   * 
   */
  findMany<T extends serviceRatingFindManyArgs>(args?: Prisma.SelectSubset<T, serviceRatingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$serviceRatingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ServiceRating.
   * @param {serviceRatingCreateArgs} args - Arguments to create a ServiceRating.
   * @example
   * // Create one ServiceRating
   * const ServiceRating = await prisma.serviceRating.create({
   *   data: {
   *     // ... data to create a ServiceRating
   *   }
   * })
   * 
   */
  create<T extends serviceRatingCreateArgs>(args: Prisma.SelectSubset<T, serviceRatingCreateArgs<ExtArgs>>): Prisma.Prisma__serviceRatingClient<runtime.Types.Result.GetResult<Prisma.$serviceRatingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ServiceRatings.
   * @param {serviceRatingCreateManyArgs} args - Arguments to create many ServiceRatings.
   * @example
   * // Create many ServiceRatings
   * const serviceRating = await prisma.serviceRating.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends serviceRatingCreateManyArgs>(args?: Prisma.SelectSubset<T, serviceRatingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ServiceRatings and returns the data saved in the database.
   * @param {serviceRatingCreateManyAndReturnArgs} args - Arguments to create many ServiceRatings.
   * @example
   * // Create many ServiceRatings
   * const serviceRating = await prisma.serviceRating.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ServiceRatings and only return the `serviceId`
   * const serviceRatingWithServiceIdOnly = await prisma.serviceRating.createManyAndReturn({
   *   select: { serviceId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends serviceRatingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, serviceRatingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$serviceRatingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ServiceRating.
   * @param {serviceRatingDeleteArgs} args - Arguments to delete one ServiceRating.
   * @example
   * // Delete one ServiceRating
   * const ServiceRating = await prisma.serviceRating.delete({
   *   where: {
   *     // ... filter to delete one ServiceRating
   *   }
   * })
   * 
   */
  delete<T extends serviceRatingDeleteArgs>(args: Prisma.SelectSubset<T, serviceRatingDeleteArgs<ExtArgs>>): Prisma.Prisma__serviceRatingClient<runtime.Types.Result.GetResult<Prisma.$serviceRatingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ServiceRating.
   * @param {serviceRatingUpdateArgs} args - Arguments to update one ServiceRating.
   * @example
   * // Update one ServiceRating
   * const serviceRating = await prisma.serviceRating.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends serviceRatingUpdateArgs>(args: Prisma.SelectSubset<T, serviceRatingUpdateArgs<ExtArgs>>): Prisma.Prisma__serviceRatingClient<runtime.Types.Result.GetResult<Prisma.$serviceRatingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ServiceRatings.
   * @param {serviceRatingDeleteManyArgs} args - Arguments to filter ServiceRatings to delete.
   * @example
   * // Delete a few ServiceRatings
   * const { count } = await prisma.serviceRating.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends serviceRatingDeleteManyArgs>(args?: Prisma.SelectSubset<T, serviceRatingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceRatings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {serviceRatingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ServiceRatings
   * const serviceRating = await prisma.serviceRating.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends serviceRatingUpdateManyArgs>(args: Prisma.SelectSubset<T, serviceRatingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceRatings and returns the data updated in the database.
   * @param {serviceRatingUpdateManyAndReturnArgs} args - Arguments to update many ServiceRatings.
   * @example
   * // Update many ServiceRatings
   * const serviceRating = await prisma.serviceRating.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ServiceRatings and only return the `serviceId`
   * const serviceRatingWithServiceIdOnly = await prisma.serviceRating.updateManyAndReturn({
   *   select: { serviceId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends serviceRatingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, serviceRatingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$serviceRatingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ServiceRating.
   * @param {serviceRatingUpsertArgs} args - Arguments to update or create a ServiceRating.
   * @example
   * // Update or create a ServiceRating
   * const serviceRating = await prisma.serviceRating.upsert({
   *   create: {
   *     // ... data to create a ServiceRating
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ServiceRating we want to update
   *   }
   * })
   */
  upsert<T extends serviceRatingUpsertArgs>(args: Prisma.SelectSubset<T, serviceRatingUpsertArgs<ExtArgs>>): Prisma.Prisma__serviceRatingClient<runtime.Types.Result.GetResult<Prisma.$serviceRatingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ServiceRatings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {serviceRatingCountArgs} args - Arguments to filter ServiceRatings to count.
   * @example
   * // Count the number of ServiceRatings
   * const count = await prisma.serviceRating.count({
   *   where: {
   *     // ... the filter for the ServiceRatings we want to count
   *   }
   * })
  **/
  count<T extends serviceRatingCountArgs>(
    args?: Prisma.Subset<T, serviceRatingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ServiceRatingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ServiceRating.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceRatingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ServiceRatingAggregateArgs>(args: Prisma.Subset<T, ServiceRatingAggregateArgs>): Prisma.PrismaPromise<GetServiceRatingAggregateType<T>>

  /**
   * Group by ServiceRating.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {serviceRatingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends serviceRatingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: serviceRatingGroupByArgs['orderBy'] }
      : { orderBy?: serviceRatingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, serviceRatingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetServiceRatingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the serviceRating model
 */
readonly fields: serviceRatingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for serviceRating.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__serviceRatingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  localService<T extends Prisma.localServiceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.localServiceDefaultArgs<ExtArgs>>): Prisma.Prisma__localServiceClient<runtime.Types.Result.GetResult<Prisma.$localServicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.userDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.userDefaultArgs<ExtArgs>>): Prisma.Prisma__userClient<runtime.Types.Result.GetResult<Prisma.$userPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the serviceRating model
 */
export interface serviceRatingFieldRefs {
  readonly serviceId: Prisma.FieldRef<"serviceRating", 'String'>
  readonly userId: Prisma.FieldRef<"serviceRating", 'String'>
  readonly rating: Prisma.FieldRef<"serviceRating", 'Int'>
  readonly comment: Prisma.FieldRef<"serviceRating", 'String'>
  readonly ratingDate: Prisma.FieldRef<"serviceRating", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"serviceRating", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"serviceRating", 'DateTime'>
  readonly id: Prisma.FieldRef<"serviceRating", 'String'>
}
    

// Custom InputTypes
/**
 * serviceRating findUnique
 */
export type serviceRatingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the serviceRating
   */
  select?: Prisma.serviceRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the serviceRating
   */
  omit?: Prisma.serviceRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.serviceRatingInclude<ExtArgs> | null
  /**
   * Filter, which serviceRating to fetch.
   */
  where: Prisma.serviceRatingWhereUniqueInput
}

/**
 * serviceRating findUniqueOrThrow
 */
export type serviceRatingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the serviceRating
   */
  select?: Prisma.serviceRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the serviceRating
   */
  omit?: Prisma.serviceRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.serviceRatingInclude<ExtArgs> | null
  /**
   * Filter, which serviceRating to fetch.
   */
  where: Prisma.serviceRatingWhereUniqueInput
}

/**
 * serviceRating findFirst
 */
export type serviceRatingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the serviceRating
   */
  select?: Prisma.serviceRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the serviceRating
   */
  omit?: Prisma.serviceRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.serviceRatingInclude<ExtArgs> | null
  /**
   * Filter, which serviceRating to fetch.
   */
  where?: Prisma.serviceRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of serviceRatings to fetch.
   */
  orderBy?: Prisma.serviceRatingOrderByWithRelationInput | Prisma.serviceRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for serviceRatings.
   */
  cursor?: Prisma.serviceRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` serviceRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` serviceRatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of serviceRatings.
   */
  distinct?: Prisma.ServiceRatingScalarFieldEnum | Prisma.ServiceRatingScalarFieldEnum[]
}

/**
 * serviceRating findFirstOrThrow
 */
export type serviceRatingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the serviceRating
   */
  select?: Prisma.serviceRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the serviceRating
   */
  omit?: Prisma.serviceRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.serviceRatingInclude<ExtArgs> | null
  /**
   * Filter, which serviceRating to fetch.
   */
  where?: Prisma.serviceRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of serviceRatings to fetch.
   */
  orderBy?: Prisma.serviceRatingOrderByWithRelationInput | Prisma.serviceRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for serviceRatings.
   */
  cursor?: Prisma.serviceRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` serviceRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` serviceRatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of serviceRatings.
   */
  distinct?: Prisma.ServiceRatingScalarFieldEnum | Prisma.ServiceRatingScalarFieldEnum[]
}

/**
 * serviceRating findMany
 */
export type serviceRatingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the serviceRating
   */
  select?: Prisma.serviceRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the serviceRating
   */
  omit?: Prisma.serviceRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.serviceRatingInclude<ExtArgs> | null
  /**
   * Filter, which serviceRatings to fetch.
   */
  where?: Prisma.serviceRatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of serviceRatings to fetch.
   */
  orderBy?: Prisma.serviceRatingOrderByWithRelationInput | Prisma.serviceRatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing serviceRatings.
   */
  cursor?: Prisma.serviceRatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` serviceRatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` serviceRatings.
   */
  skip?: number
  distinct?: Prisma.ServiceRatingScalarFieldEnum | Prisma.ServiceRatingScalarFieldEnum[]
}

/**
 * serviceRating create
 */
export type serviceRatingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the serviceRating
   */
  select?: Prisma.serviceRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the serviceRating
   */
  omit?: Prisma.serviceRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.serviceRatingInclude<ExtArgs> | null
  /**
   * The data needed to create a serviceRating.
   */
  data: Prisma.XOR<Prisma.serviceRatingCreateInput, Prisma.serviceRatingUncheckedCreateInput>
}

/**
 * serviceRating createMany
 */
export type serviceRatingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many serviceRatings.
   */
  data: Prisma.serviceRatingCreateManyInput | Prisma.serviceRatingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * serviceRating createManyAndReturn
 */
export type serviceRatingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the serviceRating
   */
  select?: Prisma.serviceRatingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the serviceRating
   */
  omit?: Prisma.serviceRatingOmit<ExtArgs> | null
  /**
   * The data used to create many serviceRatings.
   */
  data: Prisma.serviceRatingCreateManyInput | Prisma.serviceRatingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.serviceRatingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * serviceRating update
 */
export type serviceRatingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the serviceRating
   */
  select?: Prisma.serviceRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the serviceRating
   */
  omit?: Prisma.serviceRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.serviceRatingInclude<ExtArgs> | null
  /**
   * The data needed to update a serviceRating.
   */
  data: Prisma.XOR<Prisma.serviceRatingUpdateInput, Prisma.serviceRatingUncheckedUpdateInput>
  /**
   * Choose, which serviceRating to update.
   */
  where: Prisma.serviceRatingWhereUniqueInput
}

/**
 * serviceRating updateMany
 */
export type serviceRatingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update serviceRatings.
   */
  data: Prisma.XOR<Prisma.serviceRatingUpdateManyMutationInput, Prisma.serviceRatingUncheckedUpdateManyInput>
  /**
   * Filter which serviceRatings to update
   */
  where?: Prisma.serviceRatingWhereInput
  /**
   * Limit how many serviceRatings to update.
   */
  limit?: number
}

/**
 * serviceRating updateManyAndReturn
 */
export type serviceRatingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the serviceRating
   */
  select?: Prisma.serviceRatingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the serviceRating
   */
  omit?: Prisma.serviceRatingOmit<ExtArgs> | null
  /**
   * The data used to update serviceRatings.
   */
  data: Prisma.XOR<Prisma.serviceRatingUpdateManyMutationInput, Prisma.serviceRatingUncheckedUpdateManyInput>
  /**
   * Filter which serviceRatings to update
   */
  where?: Prisma.serviceRatingWhereInput
  /**
   * Limit how many serviceRatings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.serviceRatingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * serviceRating upsert
 */
export type serviceRatingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the serviceRating
   */
  select?: Prisma.serviceRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the serviceRating
   */
  omit?: Prisma.serviceRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.serviceRatingInclude<ExtArgs> | null
  /**
   * The filter to search for the serviceRating to update in case it exists.
   */
  where: Prisma.serviceRatingWhereUniqueInput
  /**
   * In case the serviceRating found by the `where` argument doesn't exist, create a new serviceRating with this data.
   */
  create: Prisma.XOR<Prisma.serviceRatingCreateInput, Prisma.serviceRatingUncheckedCreateInput>
  /**
   * In case the serviceRating was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.serviceRatingUpdateInput, Prisma.serviceRatingUncheckedUpdateInput>
}

/**
 * serviceRating delete
 */
export type serviceRatingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the serviceRating
   */
  select?: Prisma.serviceRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the serviceRating
   */
  omit?: Prisma.serviceRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.serviceRatingInclude<ExtArgs> | null
  /**
   * Filter which serviceRating to delete.
   */
  where: Prisma.serviceRatingWhereUniqueInput
}

/**
 * serviceRating deleteMany
 */
export type serviceRatingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which serviceRatings to delete
   */
  where?: Prisma.serviceRatingWhereInput
  /**
   * Limit how many serviceRatings to delete.
   */
  limit?: number
}

/**
 * serviceRating without action
 */
export type serviceRatingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the serviceRating
   */
  select?: Prisma.serviceRatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the serviceRating
   */
  omit?: Prisma.serviceRatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.serviceRatingInclude<ExtArgs> | null
}
