
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `trustCircle` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model trustCircle
 * 
 */
export type trustCircleModel = runtime.Types.Result.DefaultSelection<Prisma.$trustCirclePayload>

export type AggregateTrustCircle = {
  _count: TrustCircleCountAggregateOutputType | null
  _min: TrustCircleMinAggregateOutputType | null
  _max: TrustCircleMaxAggregateOutputType | null
}

export type TrustCircleMinAggregateOutputType = {
  userId: string | null
  contactId: string | null
  dateAdded: Date | null
  accessLevel: string | null
  createdAt: Date | null
  updatedAt: Date | null
  id: string | null
}

export type TrustCircleMaxAggregateOutputType = {
  userId: string | null
  contactId: string | null
  dateAdded: Date | null
  accessLevel: string | null
  createdAt: Date | null
  updatedAt: Date | null
  id: string | null
}

export type TrustCircleCountAggregateOutputType = {
  userId: number
  contactId: number
  dateAdded: number
  accessLevel: number
  createdAt: number
  updatedAt: number
  id: number
  _all: number
}


export type TrustCircleMinAggregateInputType = {
  userId?: true
  contactId?: true
  dateAdded?: true
  accessLevel?: true
  createdAt?: true
  updatedAt?: true
  id?: true
}

export type TrustCircleMaxAggregateInputType = {
  userId?: true
  contactId?: true
  dateAdded?: true
  accessLevel?: true
  createdAt?: true
  updatedAt?: true
  id?: true
}

export type TrustCircleCountAggregateInputType = {
  userId?: true
  contactId?: true
  dateAdded?: true
  accessLevel?: true
  createdAt?: true
  updatedAt?: true
  id?: true
  _all?: true
}

export type TrustCircleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which trustCircle to aggregate.
   */
  where?: Prisma.trustCircleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of trustCircles to fetch.
   */
  orderBy?: Prisma.trustCircleOrderByWithRelationInput | Prisma.trustCircleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.trustCircleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` trustCircles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` trustCircles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned trustCircles
  **/
  _count?: true | TrustCircleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TrustCircleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TrustCircleMaxAggregateInputType
}

export type GetTrustCircleAggregateType<T extends TrustCircleAggregateArgs> = {
      [P in keyof T & keyof AggregateTrustCircle]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTrustCircle[P]>
    : Prisma.GetScalarType<T[P], AggregateTrustCircle[P]>
}




export type trustCircleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.trustCircleWhereInput
  orderBy?: Prisma.trustCircleOrderByWithAggregationInput | Prisma.trustCircleOrderByWithAggregationInput[]
  by: Prisma.TrustCircleScalarFieldEnum[] | Prisma.TrustCircleScalarFieldEnum
  having?: Prisma.trustCircleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TrustCircleCountAggregateInputType | true
  _min?: TrustCircleMinAggregateInputType
  _max?: TrustCircleMaxAggregateInputType
}

export type TrustCircleGroupByOutputType = {
  userId: string
  contactId: string
  dateAdded: Date
  accessLevel: string
  createdAt: Date
  updatedAt: Date | null
  id: string
  _count: TrustCircleCountAggregateOutputType | null
  _min: TrustCircleMinAggregateOutputType | null
  _max: TrustCircleMaxAggregateOutputType | null
}

type GetTrustCircleGroupByPayload<T extends trustCircleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TrustCircleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TrustCircleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TrustCircleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TrustCircleGroupByOutputType[P]>
      }
    >
  >



export type trustCircleWhereInput = {
  AND?: Prisma.trustCircleWhereInput | Prisma.trustCircleWhereInput[]
  OR?: Prisma.trustCircleWhereInput[]
  NOT?: Prisma.trustCircleWhereInput | Prisma.trustCircleWhereInput[]
  userId?: Prisma.StringFilter<"trustCircle"> | string
  contactId?: Prisma.StringFilter<"trustCircle"> | string
  dateAdded?: Prisma.DateTimeFilter<"trustCircle"> | Date | string
  accessLevel?: Prisma.StringFilter<"trustCircle"> | string
  createdAt?: Prisma.DateTimeFilter<"trustCircle"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"trustCircle"> | Date | string | null
  id?: Prisma.StringFilter<"trustCircle"> | string
}

export type trustCircleOrderByWithRelationInput = {
  userId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  dateAdded?: Prisma.SortOrder
  accessLevel?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  id?: Prisma.SortOrder
}

export type trustCircleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.trustCircleWhereInput | Prisma.trustCircleWhereInput[]
  OR?: Prisma.trustCircleWhereInput[]
  NOT?: Prisma.trustCircleWhereInput | Prisma.trustCircleWhereInput[]
  userId?: Prisma.StringFilter<"trustCircle"> | string
  contactId?: Prisma.StringFilter<"trustCircle"> | string
  dateAdded?: Prisma.DateTimeFilter<"trustCircle"> | Date | string
  accessLevel?: Prisma.StringFilter<"trustCircle"> | string
  createdAt?: Prisma.DateTimeFilter<"trustCircle"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"trustCircle"> | Date | string | null
}, "id">

export type trustCircleOrderByWithAggregationInput = {
  userId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  dateAdded?: Prisma.SortOrder
  accessLevel?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  id?: Prisma.SortOrder
  _count?: Prisma.trustCircleCountOrderByAggregateInput
  _max?: Prisma.trustCircleMaxOrderByAggregateInput
  _min?: Prisma.trustCircleMinOrderByAggregateInput
}

export type trustCircleScalarWhereWithAggregatesInput = {
  AND?: Prisma.trustCircleScalarWhereWithAggregatesInput | Prisma.trustCircleScalarWhereWithAggregatesInput[]
  OR?: Prisma.trustCircleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.trustCircleScalarWhereWithAggregatesInput | Prisma.trustCircleScalarWhereWithAggregatesInput[]
  userId?: Prisma.StringWithAggregatesFilter<"trustCircle"> | string
  contactId?: Prisma.StringWithAggregatesFilter<"trustCircle"> | string
  dateAdded?: Prisma.DateTimeWithAggregatesFilter<"trustCircle"> | Date | string
  accessLevel?: Prisma.StringWithAggregatesFilter<"trustCircle"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"trustCircle"> | Date | string
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"trustCircle"> | Date | string | null
  id?: Prisma.StringWithAggregatesFilter<"trustCircle"> | string
}

export type trustCircleCreateInput = {
  userId: string
  contactId: string
  dateAdded: Date | string
  accessLevel: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
  id?: string
}

export type trustCircleUncheckedCreateInput = {
  userId: string
  contactId: string
  dateAdded: Date | string
  accessLevel: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
  id?: string
}

export type trustCircleUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.StringFieldUpdateOperationsInput | string
  dateAdded?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accessLevel?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type trustCircleUncheckedUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.StringFieldUpdateOperationsInput | string
  dateAdded?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accessLevel?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type trustCircleCreateManyInput = {
  userId: string
  contactId: string
  dateAdded: Date | string
  accessLevel: string
  createdAt?: Date | string
  updatedAt?: Date | string | null
  id?: string
}

export type trustCircleUpdateManyMutationInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.StringFieldUpdateOperationsInput | string
  dateAdded?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accessLevel?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type trustCircleUncheckedUpdateManyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  contactId?: Prisma.StringFieldUpdateOperationsInput | string
  dateAdded?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accessLevel?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type trustCircleCountOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  dateAdded?: Prisma.SortOrder
  accessLevel?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  id?: Prisma.SortOrder
}

export type trustCircleMaxOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  dateAdded?: Prisma.SortOrder
  accessLevel?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  id?: Prisma.SortOrder
}

export type trustCircleMinOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  contactId?: Prisma.SortOrder
  dateAdded?: Prisma.SortOrder
  accessLevel?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  id?: Prisma.SortOrder
}



export type trustCircleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  contactId?: boolean
  dateAdded?: boolean
  accessLevel?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  id?: boolean
}, ExtArgs["result"]["trustCircle"]>

export type trustCircleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  contactId?: boolean
  dateAdded?: boolean
  accessLevel?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  id?: boolean
}, ExtArgs["result"]["trustCircle"]>

export type trustCircleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  contactId?: boolean
  dateAdded?: boolean
  accessLevel?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  id?: boolean
}, ExtArgs["result"]["trustCircle"]>

export type trustCircleSelectScalar = {
  userId?: boolean
  contactId?: boolean
  dateAdded?: boolean
  accessLevel?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  id?: boolean
}

export type trustCircleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"userId" | "contactId" | "dateAdded" | "accessLevel" | "createdAt" | "updatedAt" | "id", ExtArgs["result"]["trustCircle"]>

export type $trustCirclePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "trustCircle"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    userId: string
    contactId: string
    dateAdded: Date
    accessLevel: string
    createdAt: Date
    updatedAt: Date | null
    id: string
  }, ExtArgs["result"]["trustCircle"]>
  composites: {}
}

export type trustCircleGetPayload<S extends boolean | null | undefined | trustCircleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$trustCirclePayload, S>

export type trustCircleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<trustCircleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TrustCircleCountAggregateInputType | true
  }

export interface trustCircleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['trustCircle'], meta: { name: 'trustCircle' } }
  /**
   * Find zero or one TrustCircle that matches the filter.
   * @param {trustCircleFindUniqueArgs} args - Arguments to find a TrustCircle
   * @example
   * // Get one TrustCircle
   * const trustCircle = await prisma.trustCircle.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends trustCircleFindUniqueArgs>(args: Prisma.SelectSubset<T, trustCircleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__trustCircleClient<runtime.Types.Result.GetResult<Prisma.$trustCirclePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TrustCircle that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {trustCircleFindUniqueOrThrowArgs} args - Arguments to find a TrustCircle
   * @example
   * // Get one TrustCircle
   * const trustCircle = await prisma.trustCircle.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends trustCircleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, trustCircleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__trustCircleClient<runtime.Types.Result.GetResult<Prisma.$trustCirclePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TrustCircle that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {trustCircleFindFirstArgs} args - Arguments to find a TrustCircle
   * @example
   * // Get one TrustCircle
   * const trustCircle = await prisma.trustCircle.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends trustCircleFindFirstArgs>(args?: Prisma.SelectSubset<T, trustCircleFindFirstArgs<ExtArgs>>): Prisma.Prisma__trustCircleClient<runtime.Types.Result.GetResult<Prisma.$trustCirclePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TrustCircle that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {trustCircleFindFirstOrThrowArgs} args - Arguments to find a TrustCircle
   * @example
   * // Get one TrustCircle
   * const trustCircle = await prisma.trustCircle.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends trustCircleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, trustCircleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__trustCircleClient<runtime.Types.Result.GetResult<Prisma.$trustCirclePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TrustCircles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {trustCircleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TrustCircles
   * const trustCircles = await prisma.trustCircle.findMany()
   * 
   * // Get first 10 TrustCircles
   * const trustCircles = await prisma.trustCircle.findMany({ take: 10 })
   * 
   * // Only select the `userId`
   * const trustCircleWithUserIdOnly = await prisma.trustCircle.findMany({ select: { userId: true } })
   * 
   */
  findMany<T extends trustCircleFindManyArgs>(args?: Prisma.SelectSubset<T, trustCircleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$trustCirclePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TrustCircle.
   * @param {trustCircleCreateArgs} args - Arguments to create a TrustCircle.
   * @example
   * // Create one TrustCircle
   * const TrustCircle = await prisma.trustCircle.create({
   *   data: {
   *     // ... data to create a TrustCircle
   *   }
   * })
   * 
   */
  create<T extends trustCircleCreateArgs>(args: Prisma.SelectSubset<T, trustCircleCreateArgs<ExtArgs>>): Prisma.Prisma__trustCircleClient<runtime.Types.Result.GetResult<Prisma.$trustCirclePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TrustCircles.
   * @param {trustCircleCreateManyArgs} args - Arguments to create many TrustCircles.
   * @example
   * // Create many TrustCircles
   * const trustCircle = await prisma.trustCircle.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends trustCircleCreateManyArgs>(args?: Prisma.SelectSubset<T, trustCircleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TrustCircles and returns the data saved in the database.
   * @param {trustCircleCreateManyAndReturnArgs} args - Arguments to create many TrustCircles.
   * @example
   * // Create many TrustCircles
   * const trustCircle = await prisma.trustCircle.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TrustCircles and only return the `userId`
   * const trustCircleWithUserIdOnly = await prisma.trustCircle.createManyAndReturn({
   *   select: { userId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends trustCircleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, trustCircleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$trustCirclePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TrustCircle.
   * @param {trustCircleDeleteArgs} args - Arguments to delete one TrustCircle.
   * @example
   * // Delete one TrustCircle
   * const TrustCircle = await prisma.trustCircle.delete({
   *   where: {
   *     // ... filter to delete one TrustCircle
   *   }
   * })
   * 
   */
  delete<T extends trustCircleDeleteArgs>(args: Prisma.SelectSubset<T, trustCircleDeleteArgs<ExtArgs>>): Prisma.Prisma__trustCircleClient<runtime.Types.Result.GetResult<Prisma.$trustCirclePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TrustCircle.
   * @param {trustCircleUpdateArgs} args - Arguments to update one TrustCircle.
   * @example
   * // Update one TrustCircle
   * const trustCircle = await prisma.trustCircle.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends trustCircleUpdateArgs>(args: Prisma.SelectSubset<T, trustCircleUpdateArgs<ExtArgs>>): Prisma.Prisma__trustCircleClient<runtime.Types.Result.GetResult<Prisma.$trustCirclePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TrustCircles.
   * @param {trustCircleDeleteManyArgs} args - Arguments to filter TrustCircles to delete.
   * @example
   * // Delete a few TrustCircles
   * const { count } = await prisma.trustCircle.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends trustCircleDeleteManyArgs>(args?: Prisma.SelectSubset<T, trustCircleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TrustCircles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {trustCircleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TrustCircles
   * const trustCircle = await prisma.trustCircle.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends trustCircleUpdateManyArgs>(args: Prisma.SelectSubset<T, trustCircleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TrustCircles and returns the data updated in the database.
   * @param {trustCircleUpdateManyAndReturnArgs} args - Arguments to update many TrustCircles.
   * @example
   * // Update many TrustCircles
   * const trustCircle = await prisma.trustCircle.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TrustCircles and only return the `userId`
   * const trustCircleWithUserIdOnly = await prisma.trustCircle.updateManyAndReturn({
   *   select: { userId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends trustCircleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, trustCircleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$trustCirclePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TrustCircle.
   * @param {trustCircleUpsertArgs} args - Arguments to update or create a TrustCircle.
   * @example
   * // Update or create a TrustCircle
   * const trustCircle = await prisma.trustCircle.upsert({
   *   create: {
   *     // ... data to create a TrustCircle
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TrustCircle we want to update
   *   }
   * })
   */
  upsert<T extends trustCircleUpsertArgs>(args: Prisma.SelectSubset<T, trustCircleUpsertArgs<ExtArgs>>): Prisma.Prisma__trustCircleClient<runtime.Types.Result.GetResult<Prisma.$trustCirclePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TrustCircles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {trustCircleCountArgs} args - Arguments to filter TrustCircles to count.
   * @example
   * // Count the number of TrustCircles
   * const count = await prisma.trustCircle.count({
   *   where: {
   *     // ... the filter for the TrustCircles we want to count
   *   }
   * })
  **/
  count<T extends trustCircleCountArgs>(
    args?: Prisma.Subset<T, trustCircleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TrustCircleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TrustCircle.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrustCircleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TrustCircleAggregateArgs>(args: Prisma.Subset<T, TrustCircleAggregateArgs>): Prisma.PrismaPromise<GetTrustCircleAggregateType<T>>

  /**
   * Group by TrustCircle.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {trustCircleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends trustCircleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: trustCircleGroupByArgs['orderBy'] }
      : { orderBy?: trustCircleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, trustCircleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTrustCircleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the trustCircle model
 */
readonly fields: trustCircleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for trustCircle.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__trustCircleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the trustCircle model
 */
export interface trustCircleFieldRefs {
  readonly userId: Prisma.FieldRef<"trustCircle", 'String'>
  readonly contactId: Prisma.FieldRef<"trustCircle", 'String'>
  readonly dateAdded: Prisma.FieldRef<"trustCircle", 'DateTime'>
  readonly accessLevel: Prisma.FieldRef<"trustCircle", 'String'>
  readonly createdAt: Prisma.FieldRef<"trustCircle", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"trustCircle", 'DateTime'>
  readonly id: Prisma.FieldRef<"trustCircle", 'String'>
}
    

// Custom InputTypes
/**
 * trustCircle findUnique
 */
export type trustCircleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the trustCircle
   */
  select?: Prisma.trustCircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the trustCircle
   */
  omit?: Prisma.trustCircleOmit<ExtArgs> | null
  /**
   * Filter, which trustCircle to fetch.
   */
  where: Prisma.trustCircleWhereUniqueInput
}

/**
 * trustCircle findUniqueOrThrow
 */
export type trustCircleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the trustCircle
   */
  select?: Prisma.trustCircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the trustCircle
   */
  omit?: Prisma.trustCircleOmit<ExtArgs> | null
  /**
   * Filter, which trustCircle to fetch.
   */
  where: Prisma.trustCircleWhereUniqueInput
}

/**
 * trustCircle findFirst
 */
export type trustCircleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the trustCircle
   */
  select?: Prisma.trustCircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the trustCircle
   */
  omit?: Prisma.trustCircleOmit<ExtArgs> | null
  /**
   * Filter, which trustCircle to fetch.
   */
  where?: Prisma.trustCircleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of trustCircles to fetch.
   */
  orderBy?: Prisma.trustCircleOrderByWithRelationInput | Prisma.trustCircleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for trustCircles.
   */
  cursor?: Prisma.trustCircleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` trustCircles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` trustCircles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of trustCircles.
   */
  distinct?: Prisma.TrustCircleScalarFieldEnum | Prisma.TrustCircleScalarFieldEnum[]
}

/**
 * trustCircle findFirstOrThrow
 */
export type trustCircleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the trustCircle
   */
  select?: Prisma.trustCircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the trustCircle
   */
  omit?: Prisma.trustCircleOmit<ExtArgs> | null
  /**
   * Filter, which trustCircle to fetch.
   */
  where?: Prisma.trustCircleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of trustCircles to fetch.
   */
  orderBy?: Prisma.trustCircleOrderByWithRelationInput | Prisma.trustCircleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for trustCircles.
   */
  cursor?: Prisma.trustCircleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` trustCircles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` trustCircles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of trustCircles.
   */
  distinct?: Prisma.TrustCircleScalarFieldEnum | Prisma.TrustCircleScalarFieldEnum[]
}

/**
 * trustCircle findMany
 */
export type trustCircleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the trustCircle
   */
  select?: Prisma.trustCircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the trustCircle
   */
  omit?: Prisma.trustCircleOmit<ExtArgs> | null
  /**
   * Filter, which trustCircles to fetch.
   */
  where?: Prisma.trustCircleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of trustCircles to fetch.
   */
  orderBy?: Prisma.trustCircleOrderByWithRelationInput | Prisma.trustCircleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing trustCircles.
   */
  cursor?: Prisma.trustCircleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` trustCircles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` trustCircles.
   */
  skip?: number
  distinct?: Prisma.TrustCircleScalarFieldEnum | Prisma.TrustCircleScalarFieldEnum[]
}

/**
 * trustCircle create
 */
export type trustCircleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the trustCircle
   */
  select?: Prisma.trustCircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the trustCircle
   */
  omit?: Prisma.trustCircleOmit<ExtArgs> | null
  /**
   * The data needed to create a trustCircle.
   */
  data: Prisma.XOR<Prisma.trustCircleCreateInput, Prisma.trustCircleUncheckedCreateInput>
}

/**
 * trustCircle createMany
 */
export type trustCircleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many trustCircles.
   */
  data: Prisma.trustCircleCreateManyInput | Prisma.trustCircleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * trustCircle createManyAndReturn
 */
export type trustCircleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the trustCircle
   */
  select?: Prisma.trustCircleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the trustCircle
   */
  omit?: Prisma.trustCircleOmit<ExtArgs> | null
  /**
   * The data used to create many trustCircles.
   */
  data: Prisma.trustCircleCreateManyInput | Prisma.trustCircleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * trustCircle update
 */
export type trustCircleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the trustCircle
   */
  select?: Prisma.trustCircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the trustCircle
   */
  omit?: Prisma.trustCircleOmit<ExtArgs> | null
  /**
   * The data needed to update a trustCircle.
   */
  data: Prisma.XOR<Prisma.trustCircleUpdateInput, Prisma.trustCircleUncheckedUpdateInput>
  /**
   * Choose, which trustCircle to update.
   */
  where: Prisma.trustCircleWhereUniqueInput
}

/**
 * trustCircle updateMany
 */
export type trustCircleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update trustCircles.
   */
  data: Prisma.XOR<Prisma.trustCircleUpdateManyMutationInput, Prisma.trustCircleUncheckedUpdateManyInput>
  /**
   * Filter which trustCircles to update
   */
  where?: Prisma.trustCircleWhereInput
  /**
   * Limit how many trustCircles to update.
   */
  limit?: number
}

/**
 * trustCircle updateManyAndReturn
 */
export type trustCircleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the trustCircle
   */
  select?: Prisma.trustCircleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the trustCircle
   */
  omit?: Prisma.trustCircleOmit<ExtArgs> | null
  /**
   * The data used to update trustCircles.
   */
  data: Prisma.XOR<Prisma.trustCircleUpdateManyMutationInput, Prisma.trustCircleUncheckedUpdateManyInput>
  /**
   * Filter which trustCircles to update
   */
  where?: Prisma.trustCircleWhereInput
  /**
   * Limit how many trustCircles to update.
   */
  limit?: number
}

/**
 * trustCircle upsert
 */
export type trustCircleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the trustCircle
   */
  select?: Prisma.trustCircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the trustCircle
   */
  omit?: Prisma.trustCircleOmit<ExtArgs> | null
  /**
   * The filter to search for the trustCircle to update in case it exists.
   */
  where: Prisma.trustCircleWhereUniqueInput
  /**
   * In case the trustCircle found by the `where` argument doesn't exist, create a new trustCircle with this data.
   */
  create: Prisma.XOR<Prisma.trustCircleCreateInput, Prisma.trustCircleUncheckedCreateInput>
  /**
   * In case the trustCircle was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.trustCircleUpdateInput, Prisma.trustCircleUncheckedUpdateInput>
}

/**
 * trustCircle delete
 */
export type trustCircleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the trustCircle
   */
  select?: Prisma.trustCircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the trustCircle
   */
  omit?: Prisma.trustCircleOmit<ExtArgs> | null
  /**
   * Filter which trustCircle to delete.
   */
  where: Prisma.trustCircleWhereUniqueInput
}

/**
 * trustCircle deleteMany
 */
export type trustCircleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which trustCircles to delete
   */
  where?: Prisma.trustCircleWhereInput
  /**
   * Limit how many trustCircles to delete.
   */
  limit?: number
}

/**
 * trustCircle without action
 */
export type trustCircleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the trustCircle
   */
  select?: Prisma.trustCircleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the trustCircle
   */
  omit?: Prisma.trustCircleOmit<ExtArgs> | null
}
