
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `urbanIssueReport` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model urbanIssueReport
 * 
 */
export type urbanIssueReportModel = runtime.Types.Result.DefaultSelection<Prisma.$urbanIssueReportPayload>

export type AggregateUrbanIssueReport = {
  _count: UrbanIssueReportCountAggregateOutputType | null
  _avg: UrbanIssueReportAvgAggregateOutputType | null
  _sum: UrbanIssueReportSumAggregateOutputType | null
  _min: UrbanIssueReportMinAggregateOutputType | null
  _max: UrbanIssueReportMaxAggregateOutputType | null
}

export type UrbanIssueReportAvgAggregateOutputType = {
  categoryId: number | null
}

export type UrbanIssueReportSumAggregateOutputType = {
  categoryId: number | null
}

export type UrbanIssueReportMinAggregateOutputType = {
  id: string | null
  userId: string | null
  description: string | null
  address: string | null
  gpsCoordinates: string | null
  reportDate: Date | null
  status: string | null
  cityReference: string | null
  createdAt: Date | null
  updatedAt: Date | null
  categoryId: number | null
}

export type UrbanIssueReportMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  description: string | null
  address: string | null
  gpsCoordinates: string | null
  reportDate: Date | null
  status: string | null
  cityReference: string | null
  createdAt: Date | null
  updatedAt: Date | null
  categoryId: number | null
}

export type UrbanIssueReportCountAggregateOutputType = {
  id: number
  userId: number
  description: number
  address: number
  gpsCoordinates: number
  reportDate: number
  status: number
  cityReference: number
  createdAt: number
  updatedAt: number
  categoryId: number
  _all: number
}


export type UrbanIssueReportAvgAggregateInputType = {
  categoryId?: true
}

export type UrbanIssueReportSumAggregateInputType = {
  categoryId?: true
}

export type UrbanIssueReportMinAggregateInputType = {
  id?: true
  userId?: true
  description?: true
  address?: true
  gpsCoordinates?: true
  reportDate?: true
  status?: true
  cityReference?: true
  createdAt?: true
  updatedAt?: true
  categoryId?: true
}

export type UrbanIssueReportMaxAggregateInputType = {
  id?: true
  userId?: true
  description?: true
  address?: true
  gpsCoordinates?: true
  reportDate?: true
  status?: true
  cityReference?: true
  createdAt?: true
  updatedAt?: true
  categoryId?: true
}

export type UrbanIssueReportCountAggregateInputType = {
  id?: true
  userId?: true
  description?: true
  address?: true
  gpsCoordinates?: true
  reportDate?: true
  status?: true
  cityReference?: true
  createdAt?: true
  updatedAt?: true
  categoryId?: true
  _all?: true
}

export type UrbanIssueReportAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which urbanIssueReport to aggregate.
   */
  where?: Prisma.urbanIssueReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of urbanIssueReports to fetch.
   */
  orderBy?: Prisma.urbanIssueReportOrderByWithRelationInput | Prisma.urbanIssueReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.urbanIssueReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` urbanIssueReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` urbanIssueReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned urbanIssueReports
  **/
  _count?: true | UrbanIssueReportCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UrbanIssueReportAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UrbanIssueReportSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UrbanIssueReportMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UrbanIssueReportMaxAggregateInputType
}

export type GetUrbanIssueReportAggregateType<T extends UrbanIssueReportAggregateArgs> = {
      [P in keyof T & keyof AggregateUrbanIssueReport]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUrbanIssueReport[P]>
    : Prisma.GetScalarType<T[P], AggregateUrbanIssueReport[P]>
}




export type urbanIssueReportGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.urbanIssueReportWhereInput
  orderBy?: Prisma.urbanIssueReportOrderByWithAggregationInput | Prisma.urbanIssueReportOrderByWithAggregationInput[]
  by: Prisma.UrbanIssueReportScalarFieldEnum[] | Prisma.UrbanIssueReportScalarFieldEnum
  having?: Prisma.urbanIssueReportScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UrbanIssueReportCountAggregateInputType | true
  _avg?: UrbanIssueReportAvgAggregateInputType
  _sum?: UrbanIssueReportSumAggregateInputType
  _min?: UrbanIssueReportMinAggregateInputType
  _max?: UrbanIssueReportMaxAggregateInputType
}

export type UrbanIssueReportGroupByOutputType = {
  id: string
  userId: string
  description: string
  address: string
  gpsCoordinates: string | null
  reportDate: Date
  status: string | null
  cityReference: string | null
  createdAt: Date
  updatedAt: Date | null
  categoryId: number
  _count: UrbanIssueReportCountAggregateOutputType | null
  _avg: UrbanIssueReportAvgAggregateOutputType | null
  _sum: UrbanIssueReportSumAggregateOutputType | null
  _min: UrbanIssueReportMinAggregateOutputType | null
  _max: UrbanIssueReportMaxAggregateOutputType | null
}

type GetUrbanIssueReportGroupByPayload<T extends urbanIssueReportGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UrbanIssueReportGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UrbanIssueReportGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UrbanIssueReportGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UrbanIssueReportGroupByOutputType[P]>
      }
    >
  >



export type urbanIssueReportWhereInput = {
  AND?: Prisma.urbanIssueReportWhereInput | Prisma.urbanIssueReportWhereInput[]
  OR?: Prisma.urbanIssueReportWhereInput[]
  NOT?: Prisma.urbanIssueReportWhereInput | Prisma.urbanIssueReportWhereInput[]
  id?: Prisma.StringFilter<"urbanIssueReport"> | string
  userId?: Prisma.StringFilter<"urbanIssueReport"> | string
  description?: Prisma.StringFilter<"urbanIssueReport"> | string
  address?: Prisma.StringFilter<"urbanIssueReport"> | string
  gpsCoordinates?: Prisma.StringNullableFilter<"urbanIssueReport"> | string | null
  reportDate?: Prisma.DateTimeFilter<"urbanIssueReport"> | Date | string
  status?: Prisma.StringNullableFilter<"urbanIssueReport"> | string | null
  cityReference?: Prisma.StringNullableFilter<"urbanIssueReport"> | string | null
  createdAt?: Prisma.DateTimeFilter<"urbanIssueReport"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"urbanIssueReport"> | Date | string | null
  categoryId?: Prisma.IntFilter<"urbanIssueReport"> | number
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.categoryWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.userWhereInput>
}

export type urbanIssueReportOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  address?: Prisma.SortOrder
  gpsCoordinates?: Prisma.SortOrderInput | Prisma.SortOrder
  reportDate?: Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  cityReference?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  category?: Prisma.categoryOrderByWithRelationInput
  user?: Prisma.userOrderByWithRelationInput
}

export type urbanIssueReportWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.urbanIssueReportWhereInput | Prisma.urbanIssueReportWhereInput[]
  OR?: Prisma.urbanIssueReportWhereInput[]
  NOT?: Prisma.urbanIssueReportWhereInput | Prisma.urbanIssueReportWhereInput[]
  userId?: Prisma.StringFilter<"urbanIssueReport"> | string
  description?: Prisma.StringFilter<"urbanIssueReport"> | string
  address?: Prisma.StringFilter<"urbanIssueReport"> | string
  gpsCoordinates?: Prisma.StringNullableFilter<"urbanIssueReport"> | string | null
  reportDate?: Prisma.DateTimeFilter<"urbanIssueReport"> | Date | string
  status?: Prisma.StringNullableFilter<"urbanIssueReport"> | string | null
  cityReference?: Prisma.StringNullableFilter<"urbanIssueReport"> | string | null
  createdAt?: Prisma.DateTimeFilter<"urbanIssueReport"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"urbanIssueReport"> | Date | string | null
  categoryId?: Prisma.IntFilter<"urbanIssueReport"> | number
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.categoryWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.userWhereInput>
}, "id">

export type urbanIssueReportOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  address?: Prisma.SortOrder
  gpsCoordinates?: Prisma.SortOrderInput | Prisma.SortOrder
  reportDate?: Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  cityReference?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  _count?: Prisma.urbanIssueReportCountOrderByAggregateInput
  _avg?: Prisma.urbanIssueReportAvgOrderByAggregateInput
  _max?: Prisma.urbanIssueReportMaxOrderByAggregateInput
  _min?: Prisma.urbanIssueReportMinOrderByAggregateInput
  _sum?: Prisma.urbanIssueReportSumOrderByAggregateInput
}

export type urbanIssueReportScalarWhereWithAggregatesInput = {
  AND?: Prisma.urbanIssueReportScalarWhereWithAggregatesInput | Prisma.urbanIssueReportScalarWhereWithAggregatesInput[]
  OR?: Prisma.urbanIssueReportScalarWhereWithAggregatesInput[]
  NOT?: Prisma.urbanIssueReportScalarWhereWithAggregatesInput | Prisma.urbanIssueReportScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"urbanIssueReport"> | string
  userId?: Prisma.StringWithAggregatesFilter<"urbanIssueReport"> | string
  description?: Prisma.StringWithAggregatesFilter<"urbanIssueReport"> | string
  address?: Prisma.StringWithAggregatesFilter<"urbanIssueReport"> | string
  gpsCoordinates?: Prisma.StringNullableWithAggregatesFilter<"urbanIssueReport"> | string | null
  reportDate?: Prisma.DateTimeWithAggregatesFilter<"urbanIssueReport"> | Date | string
  status?: Prisma.StringNullableWithAggregatesFilter<"urbanIssueReport"> | string | null
  cityReference?: Prisma.StringNullableWithAggregatesFilter<"urbanIssueReport"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"urbanIssueReport"> | Date | string
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"urbanIssueReport"> | Date | string | null
  categoryId?: Prisma.IntWithAggregatesFilter<"urbanIssueReport"> | number
}

export type urbanIssueReportCreateInput = {
  id?: string
  description: string
  address: string
  gpsCoordinates?: string | null
  reportDate: Date | string
  status?: string | null
  cityReference?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  category: Prisma.categoryCreateNestedOneWithoutUrbanIssueReportInput
  user: Prisma.userCreateNestedOneWithoutUrbanIssueReportInput
}

export type urbanIssueReportUncheckedCreateInput = {
  id?: string
  userId: string
  description: string
  address: string
  gpsCoordinates?: string | null
  reportDate: Date | string
  status?: string | null
  cityReference?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  categoryId: number
}

export type urbanIssueReportUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  gpsCoordinates?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cityReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.categoryUpdateOneRequiredWithoutUrbanIssueReportNestedInput
  user?: Prisma.userUpdateOneRequiredWithoutUrbanIssueReportNestedInput
}

export type urbanIssueReportUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  gpsCoordinates?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cityReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categoryId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type urbanIssueReportCreateManyInput = {
  id?: string
  userId: string
  description: string
  address: string
  gpsCoordinates?: string | null
  reportDate: Date | string
  status?: string | null
  cityReference?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  categoryId: number
}

export type urbanIssueReportUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  gpsCoordinates?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cityReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type urbanIssueReportUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  gpsCoordinates?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cityReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categoryId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UrbanIssueReportListRelationFilter = {
  every?: Prisma.urbanIssueReportWhereInput
  some?: Prisma.urbanIssueReportWhereInput
  none?: Prisma.urbanIssueReportWhereInput
}

export type urbanIssueReportOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type urbanIssueReportCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  address?: Prisma.SortOrder
  gpsCoordinates?: Prisma.SortOrder
  reportDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  cityReference?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
}

export type urbanIssueReportAvgOrderByAggregateInput = {
  categoryId?: Prisma.SortOrder
}

export type urbanIssueReportMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  address?: Prisma.SortOrder
  gpsCoordinates?: Prisma.SortOrder
  reportDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  cityReference?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
}

export type urbanIssueReportMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  address?: Prisma.SortOrder
  gpsCoordinates?: Prisma.SortOrder
  reportDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  cityReference?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
}

export type urbanIssueReportSumOrderByAggregateInput = {
  categoryId?: Prisma.SortOrder
}

export type urbanIssueReportCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.urbanIssueReportCreateWithoutCategoryInput, Prisma.urbanIssueReportUncheckedCreateWithoutCategoryInput> | Prisma.urbanIssueReportCreateWithoutCategoryInput[] | Prisma.urbanIssueReportUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.urbanIssueReportCreateOrConnectWithoutCategoryInput | Prisma.urbanIssueReportCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.urbanIssueReportCreateManyCategoryInputEnvelope
  connect?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
}

export type urbanIssueReportUncheckedCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.urbanIssueReportCreateWithoutCategoryInput, Prisma.urbanIssueReportUncheckedCreateWithoutCategoryInput> | Prisma.urbanIssueReportCreateWithoutCategoryInput[] | Prisma.urbanIssueReportUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.urbanIssueReportCreateOrConnectWithoutCategoryInput | Prisma.urbanIssueReportCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.urbanIssueReportCreateManyCategoryInputEnvelope
  connect?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
}

export type urbanIssueReportUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.urbanIssueReportCreateWithoutCategoryInput, Prisma.urbanIssueReportUncheckedCreateWithoutCategoryInput> | Prisma.urbanIssueReportCreateWithoutCategoryInput[] | Prisma.urbanIssueReportUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.urbanIssueReportCreateOrConnectWithoutCategoryInput | Prisma.urbanIssueReportCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.urbanIssueReportUpsertWithWhereUniqueWithoutCategoryInput | Prisma.urbanIssueReportUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.urbanIssueReportCreateManyCategoryInputEnvelope
  set?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  disconnect?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  delete?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  connect?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  update?: Prisma.urbanIssueReportUpdateWithWhereUniqueWithoutCategoryInput | Prisma.urbanIssueReportUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.urbanIssueReportUpdateManyWithWhereWithoutCategoryInput | Prisma.urbanIssueReportUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.urbanIssueReportScalarWhereInput | Prisma.urbanIssueReportScalarWhereInput[]
}

export type urbanIssueReportUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.urbanIssueReportCreateWithoutCategoryInput, Prisma.urbanIssueReportUncheckedCreateWithoutCategoryInput> | Prisma.urbanIssueReportCreateWithoutCategoryInput[] | Prisma.urbanIssueReportUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.urbanIssueReportCreateOrConnectWithoutCategoryInput | Prisma.urbanIssueReportCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.urbanIssueReportUpsertWithWhereUniqueWithoutCategoryInput | Prisma.urbanIssueReportUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.urbanIssueReportCreateManyCategoryInputEnvelope
  set?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  disconnect?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  delete?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  connect?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  update?: Prisma.urbanIssueReportUpdateWithWhereUniqueWithoutCategoryInput | Prisma.urbanIssueReportUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.urbanIssueReportUpdateManyWithWhereWithoutCategoryInput | Prisma.urbanIssueReportUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.urbanIssueReportScalarWhereInput | Prisma.urbanIssueReportScalarWhereInput[]
}

export type urbanIssueReportCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.urbanIssueReportCreateWithoutUserInput, Prisma.urbanIssueReportUncheckedCreateWithoutUserInput> | Prisma.urbanIssueReportCreateWithoutUserInput[] | Prisma.urbanIssueReportUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.urbanIssueReportCreateOrConnectWithoutUserInput | Prisma.urbanIssueReportCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.urbanIssueReportCreateManyUserInputEnvelope
  connect?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
}

export type urbanIssueReportUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.urbanIssueReportCreateWithoutUserInput, Prisma.urbanIssueReportUncheckedCreateWithoutUserInput> | Prisma.urbanIssueReportCreateWithoutUserInput[] | Prisma.urbanIssueReportUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.urbanIssueReportCreateOrConnectWithoutUserInput | Prisma.urbanIssueReportCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.urbanIssueReportCreateManyUserInputEnvelope
  connect?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
}

export type urbanIssueReportUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.urbanIssueReportCreateWithoutUserInput, Prisma.urbanIssueReportUncheckedCreateWithoutUserInput> | Prisma.urbanIssueReportCreateWithoutUserInput[] | Prisma.urbanIssueReportUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.urbanIssueReportCreateOrConnectWithoutUserInput | Prisma.urbanIssueReportCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.urbanIssueReportUpsertWithWhereUniqueWithoutUserInput | Prisma.urbanIssueReportUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.urbanIssueReportCreateManyUserInputEnvelope
  set?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  disconnect?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  delete?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  connect?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  update?: Prisma.urbanIssueReportUpdateWithWhereUniqueWithoutUserInput | Prisma.urbanIssueReportUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.urbanIssueReportUpdateManyWithWhereWithoutUserInput | Prisma.urbanIssueReportUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.urbanIssueReportScalarWhereInput | Prisma.urbanIssueReportScalarWhereInput[]
}

export type urbanIssueReportUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.urbanIssueReportCreateWithoutUserInput, Prisma.urbanIssueReportUncheckedCreateWithoutUserInput> | Prisma.urbanIssueReportCreateWithoutUserInput[] | Prisma.urbanIssueReportUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.urbanIssueReportCreateOrConnectWithoutUserInput | Prisma.urbanIssueReportCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.urbanIssueReportUpsertWithWhereUniqueWithoutUserInput | Prisma.urbanIssueReportUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.urbanIssueReportCreateManyUserInputEnvelope
  set?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  disconnect?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  delete?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  connect?: Prisma.urbanIssueReportWhereUniqueInput | Prisma.urbanIssueReportWhereUniqueInput[]
  update?: Prisma.urbanIssueReportUpdateWithWhereUniqueWithoutUserInput | Prisma.urbanIssueReportUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.urbanIssueReportUpdateManyWithWhereWithoutUserInput | Prisma.urbanIssueReportUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.urbanIssueReportScalarWhereInput | Prisma.urbanIssueReportScalarWhereInput[]
}

export type urbanIssueReportCreateWithoutCategoryInput = {
  id?: string
  description: string
  address: string
  gpsCoordinates?: string | null
  reportDate: Date | string
  status?: string | null
  cityReference?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  user: Prisma.userCreateNestedOneWithoutUrbanIssueReportInput
}

export type urbanIssueReportUncheckedCreateWithoutCategoryInput = {
  id?: string
  userId: string
  description: string
  address: string
  gpsCoordinates?: string | null
  reportDate: Date | string
  status?: string | null
  cityReference?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type urbanIssueReportCreateOrConnectWithoutCategoryInput = {
  where: Prisma.urbanIssueReportWhereUniqueInput
  create: Prisma.XOR<Prisma.urbanIssueReportCreateWithoutCategoryInput, Prisma.urbanIssueReportUncheckedCreateWithoutCategoryInput>
}

export type urbanIssueReportCreateManyCategoryInputEnvelope = {
  data: Prisma.urbanIssueReportCreateManyCategoryInput | Prisma.urbanIssueReportCreateManyCategoryInput[]
  skipDuplicates?: boolean
}

export type urbanIssueReportUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.urbanIssueReportWhereUniqueInput
  update: Prisma.XOR<Prisma.urbanIssueReportUpdateWithoutCategoryInput, Prisma.urbanIssueReportUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.urbanIssueReportCreateWithoutCategoryInput, Prisma.urbanIssueReportUncheckedCreateWithoutCategoryInput>
}

export type urbanIssueReportUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.urbanIssueReportWhereUniqueInput
  data: Prisma.XOR<Prisma.urbanIssueReportUpdateWithoutCategoryInput, Prisma.urbanIssueReportUncheckedUpdateWithoutCategoryInput>
}

export type urbanIssueReportUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.urbanIssueReportScalarWhereInput
  data: Prisma.XOR<Prisma.urbanIssueReportUpdateManyMutationInput, Prisma.urbanIssueReportUncheckedUpdateManyWithoutCategoryInput>
}

export type urbanIssueReportScalarWhereInput = {
  AND?: Prisma.urbanIssueReportScalarWhereInput | Prisma.urbanIssueReportScalarWhereInput[]
  OR?: Prisma.urbanIssueReportScalarWhereInput[]
  NOT?: Prisma.urbanIssueReportScalarWhereInput | Prisma.urbanIssueReportScalarWhereInput[]
  id?: Prisma.StringFilter<"urbanIssueReport"> | string
  userId?: Prisma.StringFilter<"urbanIssueReport"> | string
  description?: Prisma.StringFilter<"urbanIssueReport"> | string
  address?: Prisma.StringFilter<"urbanIssueReport"> | string
  gpsCoordinates?: Prisma.StringNullableFilter<"urbanIssueReport"> | string | null
  reportDate?: Prisma.DateTimeFilter<"urbanIssueReport"> | Date | string
  status?: Prisma.StringNullableFilter<"urbanIssueReport"> | string | null
  cityReference?: Prisma.StringNullableFilter<"urbanIssueReport"> | string | null
  createdAt?: Prisma.DateTimeFilter<"urbanIssueReport"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"urbanIssueReport"> | Date | string | null
  categoryId?: Prisma.IntFilter<"urbanIssueReport"> | number
}

export type urbanIssueReportCreateWithoutUserInput = {
  id?: string
  description: string
  address: string
  gpsCoordinates?: string | null
  reportDate: Date | string
  status?: string | null
  cityReference?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  category: Prisma.categoryCreateNestedOneWithoutUrbanIssueReportInput
}

export type urbanIssueReportUncheckedCreateWithoutUserInput = {
  id?: string
  description: string
  address: string
  gpsCoordinates?: string | null
  reportDate: Date | string
  status?: string | null
  cityReference?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  categoryId: number
}

export type urbanIssueReportCreateOrConnectWithoutUserInput = {
  where: Prisma.urbanIssueReportWhereUniqueInput
  create: Prisma.XOR<Prisma.urbanIssueReportCreateWithoutUserInput, Prisma.urbanIssueReportUncheckedCreateWithoutUserInput>
}

export type urbanIssueReportCreateManyUserInputEnvelope = {
  data: Prisma.urbanIssueReportCreateManyUserInput | Prisma.urbanIssueReportCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type urbanIssueReportUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.urbanIssueReportWhereUniqueInput
  update: Prisma.XOR<Prisma.urbanIssueReportUpdateWithoutUserInput, Prisma.urbanIssueReportUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.urbanIssueReportCreateWithoutUserInput, Prisma.urbanIssueReportUncheckedCreateWithoutUserInput>
}

export type urbanIssueReportUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.urbanIssueReportWhereUniqueInput
  data: Prisma.XOR<Prisma.urbanIssueReportUpdateWithoutUserInput, Prisma.urbanIssueReportUncheckedUpdateWithoutUserInput>
}

export type urbanIssueReportUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.urbanIssueReportScalarWhereInput
  data: Prisma.XOR<Prisma.urbanIssueReportUpdateManyMutationInput, Prisma.urbanIssueReportUncheckedUpdateManyWithoutUserInput>
}

export type urbanIssueReportCreateManyCategoryInput = {
  id?: string
  userId: string
  description: string
  address: string
  gpsCoordinates?: string | null
  reportDate: Date | string
  status?: string | null
  cityReference?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type urbanIssueReportUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  gpsCoordinates?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cityReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.userUpdateOneRequiredWithoutUrbanIssueReportNestedInput
}

export type urbanIssueReportUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  gpsCoordinates?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cityReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type urbanIssueReportUncheckedUpdateManyWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  gpsCoordinates?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cityReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type urbanIssueReportCreateManyUserInput = {
  id?: string
  description: string
  address: string
  gpsCoordinates?: string | null
  reportDate: Date | string
  status?: string | null
  cityReference?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
  categoryId: number
}

export type urbanIssueReportUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  gpsCoordinates?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cityReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.categoryUpdateOneRequiredWithoutUrbanIssueReportNestedInput
}

export type urbanIssueReportUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  gpsCoordinates?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cityReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categoryId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type urbanIssueReportUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  gpsCoordinates?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cityReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categoryId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type urbanIssueReportSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  description?: boolean
  address?: boolean
  gpsCoordinates?: boolean
  reportDate?: boolean
  status?: boolean
  cityReference?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  categoryId?: boolean
  category?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}, ExtArgs["result"]["urbanIssueReport"]>

export type urbanIssueReportSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  description?: boolean
  address?: boolean
  gpsCoordinates?: boolean
  reportDate?: boolean
  status?: boolean
  cityReference?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  categoryId?: boolean
  category?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}, ExtArgs["result"]["urbanIssueReport"]>

export type urbanIssueReportSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  description?: boolean
  address?: boolean
  gpsCoordinates?: boolean
  reportDate?: boolean
  status?: boolean
  cityReference?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  categoryId?: boolean
  category?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}, ExtArgs["result"]["urbanIssueReport"]>

export type urbanIssueReportSelectScalar = {
  id?: boolean
  userId?: boolean
  description?: boolean
  address?: boolean
  gpsCoordinates?: boolean
  reportDate?: boolean
  status?: boolean
  cityReference?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  categoryId?: boolean
}

export type urbanIssueReportOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "description" | "address" | "gpsCoordinates" | "reportDate" | "status" | "cityReference" | "createdAt" | "updatedAt" | "categoryId", ExtArgs["result"]["urbanIssueReport"]>
export type urbanIssueReportInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}
export type urbanIssueReportIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}
export type urbanIssueReportIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
}

export type $urbanIssueReportPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "urbanIssueReport"
  objects: {
    category: Prisma.$categoryPayload<ExtArgs>
    user: Prisma.$userPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    description: string
    address: string
    gpsCoordinates: string | null
    reportDate: Date
    status: string | null
    cityReference: string | null
    createdAt: Date
    updatedAt: Date | null
    categoryId: number
  }, ExtArgs["result"]["urbanIssueReport"]>
  composites: {}
}

export type urbanIssueReportGetPayload<S extends boolean | null | undefined | urbanIssueReportDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$urbanIssueReportPayload, S>

export type urbanIssueReportCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<urbanIssueReportFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UrbanIssueReportCountAggregateInputType | true
  }

export interface urbanIssueReportDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['urbanIssueReport'], meta: { name: 'urbanIssueReport' } }
  /**
   * Find zero or one UrbanIssueReport that matches the filter.
   * @param {urbanIssueReportFindUniqueArgs} args - Arguments to find a UrbanIssueReport
   * @example
   * // Get one UrbanIssueReport
   * const urbanIssueReport = await prisma.urbanIssueReport.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends urbanIssueReportFindUniqueArgs>(args: Prisma.SelectSubset<T, urbanIssueReportFindUniqueArgs<ExtArgs>>): Prisma.Prisma__urbanIssueReportClient<runtime.Types.Result.GetResult<Prisma.$urbanIssueReportPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UrbanIssueReport that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {urbanIssueReportFindUniqueOrThrowArgs} args - Arguments to find a UrbanIssueReport
   * @example
   * // Get one UrbanIssueReport
   * const urbanIssueReport = await prisma.urbanIssueReport.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends urbanIssueReportFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, urbanIssueReportFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__urbanIssueReportClient<runtime.Types.Result.GetResult<Prisma.$urbanIssueReportPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UrbanIssueReport that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {urbanIssueReportFindFirstArgs} args - Arguments to find a UrbanIssueReport
   * @example
   * // Get one UrbanIssueReport
   * const urbanIssueReport = await prisma.urbanIssueReport.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends urbanIssueReportFindFirstArgs>(args?: Prisma.SelectSubset<T, urbanIssueReportFindFirstArgs<ExtArgs>>): Prisma.Prisma__urbanIssueReportClient<runtime.Types.Result.GetResult<Prisma.$urbanIssueReportPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UrbanIssueReport that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {urbanIssueReportFindFirstOrThrowArgs} args - Arguments to find a UrbanIssueReport
   * @example
   * // Get one UrbanIssueReport
   * const urbanIssueReport = await prisma.urbanIssueReport.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends urbanIssueReportFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, urbanIssueReportFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__urbanIssueReportClient<runtime.Types.Result.GetResult<Prisma.$urbanIssueReportPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UrbanIssueReports that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {urbanIssueReportFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UrbanIssueReports
   * const urbanIssueReports = await prisma.urbanIssueReport.findMany()
   * 
   * // Get first 10 UrbanIssueReports
   * const urbanIssueReports = await prisma.urbanIssueReport.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const urbanIssueReportWithIdOnly = await prisma.urbanIssueReport.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends urbanIssueReportFindManyArgs>(args?: Prisma.SelectSubset<T, urbanIssueReportFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$urbanIssueReportPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UrbanIssueReport.
   * @param {urbanIssueReportCreateArgs} args - Arguments to create a UrbanIssueReport.
   * @example
   * // Create one UrbanIssueReport
   * const UrbanIssueReport = await prisma.urbanIssueReport.create({
   *   data: {
   *     // ... data to create a UrbanIssueReport
   *   }
   * })
   * 
   */
  create<T extends urbanIssueReportCreateArgs>(args: Prisma.SelectSubset<T, urbanIssueReportCreateArgs<ExtArgs>>): Prisma.Prisma__urbanIssueReportClient<runtime.Types.Result.GetResult<Prisma.$urbanIssueReportPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UrbanIssueReports.
   * @param {urbanIssueReportCreateManyArgs} args - Arguments to create many UrbanIssueReports.
   * @example
   * // Create many UrbanIssueReports
   * const urbanIssueReport = await prisma.urbanIssueReport.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends urbanIssueReportCreateManyArgs>(args?: Prisma.SelectSubset<T, urbanIssueReportCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UrbanIssueReports and returns the data saved in the database.
   * @param {urbanIssueReportCreateManyAndReturnArgs} args - Arguments to create many UrbanIssueReports.
   * @example
   * // Create many UrbanIssueReports
   * const urbanIssueReport = await prisma.urbanIssueReport.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UrbanIssueReports and only return the `id`
   * const urbanIssueReportWithIdOnly = await prisma.urbanIssueReport.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends urbanIssueReportCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, urbanIssueReportCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$urbanIssueReportPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UrbanIssueReport.
   * @param {urbanIssueReportDeleteArgs} args - Arguments to delete one UrbanIssueReport.
   * @example
   * // Delete one UrbanIssueReport
   * const UrbanIssueReport = await prisma.urbanIssueReport.delete({
   *   where: {
   *     // ... filter to delete one UrbanIssueReport
   *   }
   * })
   * 
   */
  delete<T extends urbanIssueReportDeleteArgs>(args: Prisma.SelectSubset<T, urbanIssueReportDeleteArgs<ExtArgs>>): Prisma.Prisma__urbanIssueReportClient<runtime.Types.Result.GetResult<Prisma.$urbanIssueReportPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UrbanIssueReport.
   * @param {urbanIssueReportUpdateArgs} args - Arguments to update one UrbanIssueReport.
   * @example
   * // Update one UrbanIssueReport
   * const urbanIssueReport = await prisma.urbanIssueReport.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends urbanIssueReportUpdateArgs>(args: Prisma.SelectSubset<T, urbanIssueReportUpdateArgs<ExtArgs>>): Prisma.Prisma__urbanIssueReportClient<runtime.Types.Result.GetResult<Prisma.$urbanIssueReportPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UrbanIssueReports.
   * @param {urbanIssueReportDeleteManyArgs} args - Arguments to filter UrbanIssueReports to delete.
   * @example
   * // Delete a few UrbanIssueReports
   * const { count } = await prisma.urbanIssueReport.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends urbanIssueReportDeleteManyArgs>(args?: Prisma.SelectSubset<T, urbanIssueReportDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UrbanIssueReports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {urbanIssueReportUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UrbanIssueReports
   * const urbanIssueReport = await prisma.urbanIssueReport.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends urbanIssueReportUpdateManyArgs>(args: Prisma.SelectSubset<T, urbanIssueReportUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UrbanIssueReports and returns the data updated in the database.
   * @param {urbanIssueReportUpdateManyAndReturnArgs} args - Arguments to update many UrbanIssueReports.
   * @example
   * // Update many UrbanIssueReports
   * const urbanIssueReport = await prisma.urbanIssueReport.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UrbanIssueReports and only return the `id`
   * const urbanIssueReportWithIdOnly = await prisma.urbanIssueReport.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends urbanIssueReportUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, urbanIssueReportUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$urbanIssueReportPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UrbanIssueReport.
   * @param {urbanIssueReportUpsertArgs} args - Arguments to update or create a UrbanIssueReport.
   * @example
   * // Update or create a UrbanIssueReport
   * const urbanIssueReport = await prisma.urbanIssueReport.upsert({
   *   create: {
   *     // ... data to create a UrbanIssueReport
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UrbanIssueReport we want to update
   *   }
   * })
   */
  upsert<T extends urbanIssueReportUpsertArgs>(args: Prisma.SelectSubset<T, urbanIssueReportUpsertArgs<ExtArgs>>): Prisma.Prisma__urbanIssueReportClient<runtime.Types.Result.GetResult<Prisma.$urbanIssueReportPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UrbanIssueReports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {urbanIssueReportCountArgs} args - Arguments to filter UrbanIssueReports to count.
   * @example
   * // Count the number of UrbanIssueReports
   * const count = await prisma.urbanIssueReport.count({
   *   where: {
   *     // ... the filter for the UrbanIssueReports we want to count
   *   }
   * })
  **/
  count<T extends urbanIssueReportCountArgs>(
    args?: Prisma.Subset<T, urbanIssueReportCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UrbanIssueReportCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UrbanIssueReport.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UrbanIssueReportAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UrbanIssueReportAggregateArgs>(args: Prisma.Subset<T, UrbanIssueReportAggregateArgs>): Prisma.PrismaPromise<GetUrbanIssueReportAggregateType<T>>

  /**
   * Group by UrbanIssueReport.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {urbanIssueReportGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends urbanIssueReportGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: urbanIssueReportGroupByArgs['orderBy'] }
      : { orderBy?: urbanIssueReportGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, urbanIssueReportGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUrbanIssueReportGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the urbanIssueReport model
 */
readonly fields: urbanIssueReportFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for urbanIssueReport.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__urbanIssueReportClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  category<T extends Prisma.categoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.categoryDefaultArgs<ExtArgs>>): Prisma.Prisma__categoryClient<runtime.Types.Result.GetResult<Prisma.$categoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.userDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.userDefaultArgs<ExtArgs>>): Prisma.Prisma__userClient<runtime.Types.Result.GetResult<Prisma.$userPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the urbanIssueReport model
 */
export interface urbanIssueReportFieldRefs {
  readonly id: Prisma.FieldRef<"urbanIssueReport", 'String'>
  readonly userId: Prisma.FieldRef<"urbanIssueReport", 'String'>
  readonly description: Prisma.FieldRef<"urbanIssueReport", 'String'>
  readonly address: Prisma.FieldRef<"urbanIssueReport", 'String'>
  readonly gpsCoordinates: Prisma.FieldRef<"urbanIssueReport", 'String'>
  readonly reportDate: Prisma.FieldRef<"urbanIssueReport", 'DateTime'>
  readonly status: Prisma.FieldRef<"urbanIssueReport", 'String'>
  readonly cityReference: Prisma.FieldRef<"urbanIssueReport", 'String'>
  readonly createdAt: Prisma.FieldRef<"urbanIssueReport", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"urbanIssueReport", 'DateTime'>
  readonly categoryId: Prisma.FieldRef<"urbanIssueReport", 'Int'>
}
    

// Custom InputTypes
/**
 * urbanIssueReport findUnique
 */
export type urbanIssueReportFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the urbanIssueReport
   */
  select?: Prisma.urbanIssueReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the urbanIssueReport
   */
  omit?: Prisma.urbanIssueReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.urbanIssueReportInclude<ExtArgs> | null
  /**
   * Filter, which urbanIssueReport to fetch.
   */
  where: Prisma.urbanIssueReportWhereUniqueInput
}

/**
 * urbanIssueReport findUniqueOrThrow
 */
export type urbanIssueReportFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the urbanIssueReport
   */
  select?: Prisma.urbanIssueReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the urbanIssueReport
   */
  omit?: Prisma.urbanIssueReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.urbanIssueReportInclude<ExtArgs> | null
  /**
   * Filter, which urbanIssueReport to fetch.
   */
  where: Prisma.urbanIssueReportWhereUniqueInput
}

/**
 * urbanIssueReport findFirst
 */
export type urbanIssueReportFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the urbanIssueReport
   */
  select?: Prisma.urbanIssueReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the urbanIssueReport
   */
  omit?: Prisma.urbanIssueReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.urbanIssueReportInclude<ExtArgs> | null
  /**
   * Filter, which urbanIssueReport to fetch.
   */
  where?: Prisma.urbanIssueReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of urbanIssueReports to fetch.
   */
  orderBy?: Prisma.urbanIssueReportOrderByWithRelationInput | Prisma.urbanIssueReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for urbanIssueReports.
   */
  cursor?: Prisma.urbanIssueReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` urbanIssueReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` urbanIssueReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of urbanIssueReports.
   */
  distinct?: Prisma.UrbanIssueReportScalarFieldEnum | Prisma.UrbanIssueReportScalarFieldEnum[]
}

/**
 * urbanIssueReport findFirstOrThrow
 */
export type urbanIssueReportFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the urbanIssueReport
   */
  select?: Prisma.urbanIssueReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the urbanIssueReport
   */
  omit?: Prisma.urbanIssueReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.urbanIssueReportInclude<ExtArgs> | null
  /**
   * Filter, which urbanIssueReport to fetch.
   */
  where?: Prisma.urbanIssueReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of urbanIssueReports to fetch.
   */
  orderBy?: Prisma.urbanIssueReportOrderByWithRelationInput | Prisma.urbanIssueReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for urbanIssueReports.
   */
  cursor?: Prisma.urbanIssueReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` urbanIssueReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` urbanIssueReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of urbanIssueReports.
   */
  distinct?: Prisma.UrbanIssueReportScalarFieldEnum | Prisma.UrbanIssueReportScalarFieldEnum[]
}

/**
 * urbanIssueReport findMany
 */
export type urbanIssueReportFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the urbanIssueReport
   */
  select?: Prisma.urbanIssueReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the urbanIssueReport
   */
  omit?: Prisma.urbanIssueReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.urbanIssueReportInclude<ExtArgs> | null
  /**
   * Filter, which urbanIssueReports to fetch.
   */
  where?: Prisma.urbanIssueReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of urbanIssueReports to fetch.
   */
  orderBy?: Prisma.urbanIssueReportOrderByWithRelationInput | Prisma.urbanIssueReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing urbanIssueReports.
   */
  cursor?: Prisma.urbanIssueReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` urbanIssueReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` urbanIssueReports.
   */
  skip?: number
  distinct?: Prisma.UrbanIssueReportScalarFieldEnum | Prisma.UrbanIssueReportScalarFieldEnum[]
}

/**
 * urbanIssueReport create
 */
export type urbanIssueReportCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the urbanIssueReport
   */
  select?: Prisma.urbanIssueReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the urbanIssueReport
   */
  omit?: Prisma.urbanIssueReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.urbanIssueReportInclude<ExtArgs> | null
  /**
   * The data needed to create a urbanIssueReport.
   */
  data: Prisma.XOR<Prisma.urbanIssueReportCreateInput, Prisma.urbanIssueReportUncheckedCreateInput>
}

/**
 * urbanIssueReport createMany
 */
export type urbanIssueReportCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many urbanIssueReports.
   */
  data: Prisma.urbanIssueReportCreateManyInput | Prisma.urbanIssueReportCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * urbanIssueReport createManyAndReturn
 */
export type urbanIssueReportCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the urbanIssueReport
   */
  select?: Prisma.urbanIssueReportSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the urbanIssueReport
   */
  omit?: Prisma.urbanIssueReportOmit<ExtArgs> | null
  /**
   * The data used to create many urbanIssueReports.
   */
  data: Prisma.urbanIssueReportCreateManyInput | Prisma.urbanIssueReportCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.urbanIssueReportIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * urbanIssueReport update
 */
export type urbanIssueReportUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the urbanIssueReport
   */
  select?: Prisma.urbanIssueReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the urbanIssueReport
   */
  omit?: Prisma.urbanIssueReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.urbanIssueReportInclude<ExtArgs> | null
  /**
   * The data needed to update a urbanIssueReport.
   */
  data: Prisma.XOR<Prisma.urbanIssueReportUpdateInput, Prisma.urbanIssueReportUncheckedUpdateInput>
  /**
   * Choose, which urbanIssueReport to update.
   */
  where: Prisma.urbanIssueReportWhereUniqueInput
}

/**
 * urbanIssueReport updateMany
 */
export type urbanIssueReportUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update urbanIssueReports.
   */
  data: Prisma.XOR<Prisma.urbanIssueReportUpdateManyMutationInput, Prisma.urbanIssueReportUncheckedUpdateManyInput>
  /**
   * Filter which urbanIssueReports to update
   */
  where?: Prisma.urbanIssueReportWhereInput
  /**
   * Limit how many urbanIssueReports to update.
   */
  limit?: number
}

/**
 * urbanIssueReport updateManyAndReturn
 */
export type urbanIssueReportUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the urbanIssueReport
   */
  select?: Prisma.urbanIssueReportSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the urbanIssueReport
   */
  omit?: Prisma.urbanIssueReportOmit<ExtArgs> | null
  /**
   * The data used to update urbanIssueReports.
   */
  data: Prisma.XOR<Prisma.urbanIssueReportUpdateManyMutationInput, Prisma.urbanIssueReportUncheckedUpdateManyInput>
  /**
   * Filter which urbanIssueReports to update
   */
  where?: Prisma.urbanIssueReportWhereInput
  /**
   * Limit how many urbanIssueReports to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.urbanIssueReportIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * urbanIssueReport upsert
 */
export type urbanIssueReportUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the urbanIssueReport
   */
  select?: Prisma.urbanIssueReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the urbanIssueReport
   */
  omit?: Prisma.urbanIssueReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.urbanIssueReportInclude<ExtArgs> | null
  /**
   * The filter to search for the urbanIssueReport to update in case it exists.
   */
  where: Prisma.urbanIssueReportWhereUniqueInput
  /**
   * In case the urbanIssueReport found by the `where` argument doesn't exist, create a new urbanIssueReport with this data.
   */
  create: Prisma.XOR<Prisma.urbanIssueReportCreateInput, Prisma.urbanIssueReportUncheckedCreateInput>
  /**
   * In case the urbanIssueReport was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.urbanIssueReportUpdateInput, Prisma.urbanIssueReportUncheckedUpdateInput>
}

/**
 * urbanIssueReport delete
 */
export type urbanIssueReportDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the urbanIssueReport
   */
  select?: Prisma.urbanIssueReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the urbanIssueReport
   */
  omit?: Prisma.urbanIssueReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.urbanIssueReportInclude<ExtArgs> | null
  /**
   * Filter which urbanIssueReport to delete.
   */
  where: Prisma.urbanIssueReportWhereUniqueInput
}

/**
 * urbanIssueReport deleteMany
 */
export type urbanIssueReportDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which urbanIssueReports to delete
   */
  where?: Prisma.urbanIssueReportWhereInput
  /**
   * Limit how many urbanIssueReports to delete.
   */
  limit?: number
}

/**
 * urbanIssueReport without action
 */
export type urbanIssueReportDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the urbanIssueReport
   */
  select?: Prisma.urbanIssueReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the urbanIssueReport
   */
  omit?: Prisma.urbanIssueReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.urbanIssueReportInclude<ExtArgs> | null
}
